### ISSUE TITLE
qemu-system-x86_0.0_all.deb being version 0 allow update to full version

### ISSUE THREAD

**Issue by Augusto7743** [PJ-Singh-001/Cubic#109]
Hello.
Thanks for reading my topic.

Thanks very much creating the qemu-system-x86_0.0_all.deb. Thus was possible install Cubic without qemu.
However if doing an "sudo apt upgrade" having enabled an repository with qemu will install an new full qemu.
If the qemu-system-x86_0.0_all.deb have an high number version can avoid it.

Thanks for reply and for your good Cubic.

**Comment by PJ-Singh-001** [comment]
I had thought about this, but it is hard to predict what is considered a "high" version number for all versioning schemes, because `apt` simply does an ASCI comparison rather than parsing a sting and interpreting it, the way we humans do. To avoid potential problems in the future, I had settled on using something that started with "0".

Nevertheless, your suggestion is worth consideration if Qemu sticks with their versioning scheme. For example, `9.9` is less than `98.1` only because (looking at the character in the second position) `.` is less than `8` in ASCII.

In the mean time, to prevent Qemu from being installed, you can hold back the `qemu-system-x86` package...

    sudo apt-mark hold qemu-system-x86

**Comment by Augusto7743** [comment]
Thanks very much for your reply.
