### ISSUE TITLE
Can't install anything

### ISSUE THREAD

**Issue by jm2342** [PJ-Singh-001/Cubic#110]
I'm trying to customize a xubuntu-22.04.1-desktop-amd64.iso, using cubic 2022.06.72, running on an older xubuntu 20.04.01 LTS live system (booted from usb). 

"apt update" fails in the virtual environment, or rather, the signature verification fails:

>Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]                                         
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease                                                            
Err:2 http://archive.ubuntu.com/ubuntu jammy InRelease                                  
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [114 kB]
Err:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
Err:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
Fetched 224 kB in 3s (84.4 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
W: http://archive.ubuntu.com/ubuntu/dists/jammy/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/ubuntu-keyring-2012-cdimage.gpg are ignored as the file is not readable by user '_apt' executing apt-key.
W: http://archive.ubuntu.com/ubuntu/dists/jammy/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/ubuntu-keyring-2018-archive.gpg are ignored as the file is not readable by user '_apt' executing apt-key.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://archive.ubuntu.com/ubuntu jammy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
W: http://security.ubuntu.com/ubuntu/dists/jammy-security/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/ubuntu-keyring-2012-cdimage.gpg are ignored as the file is not readable by user '_apt' executing apt-key.
W: http://security.ubuntu.com/ubuntu/dists/jammy-security/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/ubuntu-keyring-2018-archive.gpg are ignored as the file is not readable by user '_apt' executing apt-key.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://security.ubuntu.com/ubuntu jammy-security InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
W: http://archive.ubuntu.com/ubuntu/dists/jammy-updates/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/ubuntu-keyring-2012-cdimage.gpg are ignored as the file is not readable by user '_apt' executing apt-key.
W: http://archive.ubuntu.com/ubuntu/dists/jammy-updates/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/ubuntu-keyring-2018-archive.gpg are ignored as the file is not readable by user '_apt' executing apt-key.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://archive.ubuntu.com/ubuntu jammy-updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/jammy-security/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy-updates/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
W: Some index files failed to download. They have been ignored, or old ones used instead.

Same issue for adding repositories. Consequently, nothing can be installed.

Is this due to:

- running on a live system?
- different xubuntu versions?
- cubic being outdated (something about how apt-key is deprecated and key management is done differently now)?
- something else entirely?

Thanks and sorry to bother you with what might not even be cubic-related.

**Comment by PJ-Singh-001** [comment]
Make sure you have Internet access and DNS resolution in the [Virtual environment](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page) in Cubic.

    ping github.com

Make sure you've added the official Ubuntu repositories to your `/etc/sources.list` file.
(Usually, these are not enabled on the original ISO).

    add-apt-repository --yes main
    add-apt-repository --yes restricted
    add-apt-repository --yes universe
    add-apt-repository --yes multiverse

The `add-apt-repository` command is available from the [software-properties-common](https://packages.ubuntu.com/jammy/software-properties-common) package, which you may need to install first (if `apt install` works).

If that does not work, this may be a similar issue to [Unable to use apt commands with 22.04 (Jammy) ISO file](https://github.com/PJ-Singh-001/Cubic/issues/67). There seems to be an issue with `apt`, when attempting to customize a _newer_ version of Ubuntu, while running Cubic from an _older_ version of Ubuntu. This used to not be an issue with prior versions of Ubuntu, but something seems to have changed with `apt` recently that may be preventing this from working. Unfortunately, I do not have a work-around for that problem at the moment.

Regarding running Cubic in a Live ISO, be aware that you will need a *LOT* of memory to get this to work.

- You will need at least 3GB for the running OS.
- On top of that you will need about 20GB in order to extract the original ISO, add packages, and create a new ISO.
- You may also run into issues when [Testing](https://github.com/PJ-Singh-001/Cubic/wiki/Finish-Test-Page) the generated ISO in Cubic.

So make sure that you have enough memory.

I can't be sure your issue is not due to memory limitations in a Live (ISO) Environment. If you tried to run a persistent Live ISO or tried mounting a USB as a disk to save Cubic working files, this may work, but writing files to the USB will be arduously slow during the [Generation](https://github.com/PJ-Singh-001/Cubic/wiki/Generate-Page) step.

I do recommend installing Cubic on a "bare metal" system with enough free disk space (~20-25 GB) for the working files, so you do not need as much RAM.

Since you are trying to run Cubic from a Live (ISO) Environment, what happens if you try to install Cubic in a 22.04.1 Live Environment, and try to customize the `xubuntu-22.04.1-desktop-amd64.iso` from there?

**Comment by jm2342** [comment]
Alright, running everything in 22.04.1 Live works, so it was the version mismatch (which I didn't try right away because I imagined it  the least likely). Max RAM usage was around 17 GB btw (as observed in taskmanager). Thanks again.

**Comment by PJ-Singh-001** [comment]
OK, good.
I'm going to close this issue.
I still have  18.04.6 and the ISO being customized is 20.04.

**Comment by PJ-Singh-001** [comment]
OK, good.
(And thanks for sharing the max RAM usage for customizing Xubuntu in a Live Environment).

I'm going to close this issue.
However, I still have  "[Unable to use apt commands with 22.04 (Jammy) ISO file](https://github.com/PJ-Singh-001/Cubic/issues/67)" open.
If I figure out a work-around for the version mismatch problem, I'll post it there.
