### ISSUE TITLE
Why custom ISO asks for user and password if I want to run it in live mode?

### ISSUE THREAD

**Issue by md-redwan-hossain** [PJ-Singh-001/Cubic#111]
Hey. 
I have created a custom ISO of Ubuntu budgie. Everything went smoothly and booted with Ventoy, but when I attempts to use try Ubuntu budgie button, it asks for username and pasdword which I never set during customizing the ISO. What is the id and password by the way?

**Comment by PJ-Singh-001** [comment]
Usually, each Ubuntu based distribution has a default user id and password for the live user.

For Ubuntu (GNOME), I believe the user id is `ubuntu` and the password is blank. This may be different for Budgie, and you may want to check on the Budgie forums.

However, I'm surprised the Live environment is asking you for a user and password. This may be do to some customization you did?

What happens if you create an ISO using Cubic, but make *no* customizations?

**Comment by md-redwan-hossain** [comment]
Update: I added a user with a password. But alas, it successfully logs in then a black screen is shown for 4-5 sec, then it fallbacks to the login screen again.

**Comment by PJ-Singh-001** [comment]
I've seen this happen when the desktop manager crashes while attempting to login.
(For me this happened when I tried to customize the Gnome Shell theme, but I had errors in my customizations).

Have you tried just creating an ISO using Cubic without making _any_ changes?
What happens in that case?

**Comment by PJ-Singh-001** [comment]
I haven't heard back from you, so I'll assume you no longer have this issue.
