### ISSUE TITLE
How to create persistent and non-persistent options for custom Live USB?

### ISSUE THREAD

**Issue by greenpython28** [PJ-Singh-001/Cubic#112]
Hey there, thanks for sharing Cubic with us! It's been so easy to use and such a help so far!
Anyways, I wanted to ask a question. 
How would I go about making a live .iso with two separate modes?
Mode 1- Live OS with persistence
Mode 2- Simple Live OS without persistence, no changes saved, and after shutdown everything is cleared.
Even if someone has set up their Live OS with persistence, if they want to go anonymous I want them to be able to use Mode 2
I never plan to install this OS to my disk.

Many thanks in advance!

**Comment by PJ-Singh-001** [comment]
If I recall, you would set this up on the [Options Page](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page), [Boot Tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#boot-tab).

Give me some time, and I'll dig up my notes on this.

**Comment by greenpython28** [comment]
Ok thanks so much

**Comment by PJ-Singh-001** [comment]
[Here are detailed instructions](https://github.com/PJ-Singh-001/Cubic/issues/8#issuecomment-1014019760) with screenshots. These are for Xubuntu, but you can adapt them to your Distro.

For Ubuntu (GNOME) the following should work...

On the [Options Page](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page), [Boot Tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#boot-tab), identify the configuration files needed to boot your system. For Ubuntu (GNOME), the default files are already visible (filtered for you). But you can see all of the files by clicking the filter <kbd>![image](https://user-images.githubusercontent.com/19394936/197910164-f677255e-0253-4434-b471-1ac1e6022d5f.png)</kbd> button in the header bar.

The two default files for Ubuntu are `/boot/grub/grub.cfg` and `/boot/grub/loopback.cfg`. Edit these files...

 1. Make a copy of the "Try or Install Ubuntu" menu entry section.
 2. Then, edit your copy, and rename it. For example add "(Persistence)" at the end of the name. 
 3. Add the keyword `persistent` just before `quiet splash`.

    It should look something like this...

        .
        .
        .
        menuentry "Try or Install Ubuntu (Persistent)" {
	        set gfxpayload=keep
	        linux	/casper/vmlinuz boot=casper file=/cdrom/preseed/ubuntu.seed maybe-ubiquity persistent quiet splash --- 
	        initrd	/casper/initrd.gz
        }
        menuentry "Try or Install Ubuntu" {
	        set gfxpayload=keep
	        linux	/casper/vmlinuz boot=casper file=/cdrom/preseed/ubuntu.seed maybe-ubiquity quiet splash --- 
	        initrd	/casper/initrd.gz
        }
        .
        .
        .

4. Generate your Custom ISO.
5. Burn your ISO using a program like [Startup Disk Creator](https://packages.ubuntu.com/jammy/usb-creator-gtk).
6. Boot into the ISO, and select your new "Persistent" menu item from the Grub menu.

    Note that you will need a partition on the USB to store the persistence. Fortunately, the first time you boot into the ISO by selecting your new "Persistent" option from the ISO's Grub menu, a partition named `writable` will automatically be created on your disk for you (assuming you have enough unpartitioned space on the USB). Therefore there is no need to use a partition editor (such as gparted) to manually create a special writable partition on the USB.

Tip: Instead of having to press <kbd>ESC</kbd>, you may want to make sure the text Grub menu is always shown (so the user can make a selection). Otherwise, the ISO will automatically boot into the graphical user interface that only presents two options (try and install). I'll let you research how to always show the Grub menu.

**Comment by greenpython28** [comment]
Thank you so much, will the remaining free space be used for a persistent partition?

**Comment by PJ-Singh-001** [comment]
This is how I've seen it work.
You should see a new partition named `writable`.
You can view the partitions on your USB using the Disks app or Gparted, to verify.
(I guess, you could resize that partition after it is created, if you wanted/needed to).
Remember, it will only be created after your first boot using the Persistent option.

Let me know how this works for you, it's bee a while since I tested this.

**Comment by greenpython28** [comment]
![image](https://user-images.githubusercontent.com/60375263/198858687-fbe5e012-20cc-4091-9109-95fa4c5d50f8.png)
After running my persistent option, this comes back in disks after booting in qemu

**Comment by UselessNeanderthal** [comment]
I haven't seen if changes actually save in persistence yet, so I will try that.

**Comment by greenpython28** [comment]
^^^Scratch that I see writable when using ubuntu startup disk creator

**Comment by PJ-Singh-001** [comment]
This makes sense. It wouldn't show up in Qemu, because there is no disk (USB) in the emulator; it is running in memory on a read-only virtual disk (as shown in the Partition Type in Disks).

**Comment by greenpython28** [comment]
True, but I didn't really see it when writing to a USB using rufus on windows either.
