### ISSUE TITLE
The `dconf load` command does not work; what is the alternative?

### ISSUE THREAD

**Issue by celoluna666** [PJ-Singh-001/Cubic#132]
I cant do the "dconf load" command on Cubic

The error:
`Cannot spawn a message bus without a machine-id: Invalid machine ID in /var/lib/dbus/machine-id or /etc/machine-id`

**Comment by celoluna666** [comment]
![image](https://user-images.githubusercontent.com/119078073/204053157-51c5d681-63b4-4c1c-9c1c-23b0bad39fc7.png)

**Comment by PJ-Singh-001** [comment]
The `dconf load` command will load will load `gsettings` from the specified file.
These setting are loaded for the current user.

When you are in the [Cubic virtual environment](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), there are no users (except that you have `root` access to the Linux file system). Even if you were able to load these settings, they would only be loaded for the root user, which I suspect is not your goal.

First make sure your `dconf` file does not have a bunch of junk it in.
So, if you created this file using `dconf dump`, you will need to comb through the file and *only* select the important settings you need.

For example, the following settings are useless, since they specift the size and locaton of a window:

**Comment by PJ-Singh-001** [comment]
The `dconf load` command will load will load `gsettings` from the specified file.
These setting are loaded for the current user.

When you are in the [Cubic virtual environment](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), there are no users (except that you have `root` access to the Linux file system that you are customizing). Even if you were able to load these settings, they would only be loaded for the root user, which *I suspect* is not your goal.

Therefore, the approach is to store your settings in a "gschema override" file which will be loaded by the GNOME Desktop Environment for each user upon login. As a result, all (new) users will get the same baseline settings that you establish. Of course users can change these settings, but those changes will only impact their account.

First make sure your `dconf` file does not have a bunch of junk it in. If you created this file using `dconf dump`, you will need to comb through the file and *only* select the important settings you need.

For example, the following settings are useless, since they specify the size and location of a window:

    [org/gnome/clocks/state/window]
    panel-id='world'
    size=(870, 690)
    state=87168

However, some setting may be important to you, such as the default wallpaper.

    [org.gnome.desktop.background]
    picture-uri = 'file:///usr/share/backgrounds/ubuntu/ubuntu_by_arman1992.jpg'
    picture-uri-dark = 'file:///usr/share/backgrounds/ubuntu/ubuntu_by_arman1992.jpg'

Using this information, here are the steps you should follow:

 1. Edit your `dconf` file to only include these important settings, for example:

 2. Then rename this file to `90_ubuntu-settings.gschema.override`.

 3. Finally, follow the remaining instructions [here, under the section titled](https://github.com/PJ-Singh-001/Cubic/issues/22#issuecomment-1032011784), "Configure Defaults" (or "デフォルトの構成", if you happen to read Japanese).

**Comment by PJ-Singh-001** [comment]
The `dconf load` command will load `gsettings` from the specified file.
These setting are loaded for the *current user*.

When you are in the [Cubic virtual environment](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), *there are no users* (except that you have `root` access to the Linux file system that you are customizing). Even if you were able to load these settings, they would only be loaded for the root user, which *I suspect* is not your goal.

Therefore, the approach is to store your settings in a "gschema override" file which will be loaded by the GNOME Desktop Environment for each user upon login. As a result, all (new) users will get the same baseline settings that you establish. Of course users can change these settings, but those changes will only impact their account.

First make sure your `dconf` file does not have a bunch of junk it in. If you created this file using `dconf dump`, you will need to comb through the file and *only* select the important settings you need.

For example, the following settings are useless, since they specify the size and location of a window:

    [org/gnome/clocks/state/window]
    panel-id='world'
    size=(870, 690)
    state=87168

However, some setting may be important to you, such as the default wallpaper:

    [org.gnome.desktop.background]
    picture-uri = 'file:///usr/share/backgrounds/ubuntu/ubuntu_by_arman1992.jpg'
    picture-uri-dark = 'file:///usr/share/backgrounds/ubuntu/ubuntu_by_arman1992.jpg'

Using this information, here are the steps you should follow:

 1. Edit your `dconf` file to only include these important settings.

 2. Then rename this file to `90_ubuntu-settings.gschema.override`.

 3. Finally, follow the remaining instructions [here, under the section titled](https://github.com/PJ-Singh-001/Cubic/issues/22#issuecomment-1032011784), "**Configure Defaults**" (or "**デフォルトの構成**", if you happen to read Japanese).
