### ISSUE TITLE
Cannot boot custom ISO (you need to load the kernel first)

### ISSUE THREAD

**Issue by Panja0** [PJ-Singh-001/Cubic#134]
I'm having problems with v2022.12.74
Created a custom Kubuntu 22.04.1 (x64) ISO on Kubuntu 22.04.1 (x64) and with the latest Cubic version (as pointed above) and still having problems booting. I can get to the Grub (v2.04) screen but trying any option results in:
```
error: invalid magic number
error: you need to load the kernel first
```

**Comment by PJ-Singh-001** [comment]
Are you testing using a USB, or are you using the Test button in Cubic, or are you using a Virtual Machine like Virtual Box ?

**Comment by Panja0** [comment]
Testing using an USB stick.

Just tried to create a custom ISO but without doing any changes. Afterward I can boot.
So it must be something in the proces of changing custom settings. 

Let me tell you what custom changes I did:
- apt update && apt upgrade -y
- apt autoremove --purge
- apt remove --purge elisa* libreoffice* -y
- installed a few .deb files with apt install ./xxxx.deb

Press next, next, next finish

**Comment by Panja0** [comment]
Just created a new one and tested it within Cubic and it works. But I cannot get it to boot on USB.

**Comment by PJ-Singh-001** [comment]
I tested by customizing `kubuntu-22.04.1-2022.12.02-desktop-amd64.iso` running Cubic 2022.12.74 in Ubuntu 22.04. I made the following customizations, matching your steps above:

    apt update && apt upgrade -y
    apt autoremove --purge
    apt remove --purge elisa* libreoffice* -y

On the Kernel tab, I accepted the default kernel, 5.15.0-56, which was installed by the upgrade process. This will allow the ISO to boot up using this newer kernel, instead of the the original kernel, 5.15.0-43.
    ![image](https://user-images.githubusercontent.com/19394936/205343772-2d3912b6-9ed1-4038-a428-4db93ad697b8.png)

The resulting image booted up just fine.
    ![image](https://user-images.githubusercontent.com/19394936/205344388-23a39a28-4a6f-4684-9263-1d7acb1645e5.png)

I suspect you have an issue with your USB.

 1. You may have run out of space while writing the USB. Make sure your USB is larger than the ISO size you are trying to write to it. You can also save a little space by deleting the pool files  from your ISO (i.e. the off-line `*.deb` files, since most will be outdated versions after you've done an `apt upgrade`). (Note, this must be done *outside* of Cubic on your host machine).

        rm r -rf <cubic project directory>/custom-disk/pool/*

 2. Your USB may be corrupt or old, so writing to it may be a problem. You can try zeroing out the USB or doing a full format, which are both long processes, but may help restore it to a usable condition.

Another option is to select the original kernel to bootstrap your ISO on the [Kernel tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#kernel-tab). The drawback of this is that you will be using the older kernel version 5.15.0-43 in the Live Environment. However, if your goal is to install the OS to a machine, and only use the ISO for installation, this isn't a big deal. Once you've installed the customized OS, it will use the most recent kernel you installed in Cubic, kernel version 5.15.0-56 in this case. (However, if your USB simply has some corrupt bits, the act of creating a new USB may simply resolve the issue, so selecting a different kernel may be unnecessary).

What software did you use to create your USB?

**Comment by Panja0** [comment]
I have one USB 3.0 stick of 128GB with Ventoy. All iso files on that disk boot without problems (10 iso files: windows and Linux). Also I tried to flash the custom iso to a different (almost new) usb 3.0 stick of 32GB.

Copy to the Ventoy disk was done with Dolphin. 
Flashing to the other usb stick was done on Windows with Rufus. 

Also tried the older Kernel without luck.

**Comment by PJ-Singh-001** [comment]
Are you able to boot into the customized ISO using the <kbd>Test</kbd> button in Cubic?

Also, try booting into the customized ISO using Virtual Box, and let me know what happens?

Did any of the `*.deb` files you installed modify or update your kernel?

If I get some time, I will try creating a bootable USB, to see if I have the same issue, but it will take me some time to do that test.

**Comment by Panja0** [comment]
Thanks for all the help! Appreciated. 
Deb files are apps. Nothing kernel related. 

I’ll do some more testing myself as well and report back. Will be later this weekend.

**Comment by Panja0** [comment]
Just created a new custom iso, same settings, same things changed. It works now!
sorry for the troubles. I’ll close the issue. 

Thanks for testing and helping out!

**Comment by PJ-Singh-001** [comment]
Glad it's working now. The `invalid magic number` hinted there was something wrong with a file (probably `vmlinuz` or `initrd`). Writing to USB can be a little unreliable sometimes, even with a brand new USB key-- my guess is that is what it was.
