### ISSUE TITLE
Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details

### ISSUE THREAD

**Issue by pasman1** [PJ-Singh-001/Cubic#137]
New apt-key prefer keys in /etc/apt/trusted.gpg.d/ directory, not in /etc/apt/trusted.gpg file.

Install cubic-wizard. 
sudo apt update

**Comment by PJ-Singh-001** [comment]
Please provide additional information.
Which OS and version are you using?

**Comment by PJ-Singh-001** [comment]
@pasman1,

This isn't an issue with Cubic.
You need to fix your system.

Here are a couple of resources, but you can also do your own search on the Internet on how to remedy this issue:

- [Fixing “Key is stored in legacy trusted.gpg keyring” Issue in Ubuntu](https://itsfoss.com/key-is-stored-in-legacy-trusted-gpg/)

- [Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg)](https://askubuntu.com/questions/1407632/key-is-stored-in-legacy-trusted-gpg-keyring-etc-apt-trusted-gpg)

**Comment by richteas75** [comment]
Thank you for your work on cubic!
@pasman1 has a point here, imo. Since the links that you, @PJ-Singh-001, provided even mention that trusted.gpg keyring is deprecated, the installation instructions for Debian could be adapted. The second command
`apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 081525E2B4F1283B`
could be replaced by its up-to-date equivalent:
`sudo curl -S "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x081525e2b4f1283b" | sudo gpg --batch --yes --dearmor --output /etc/apt/trusted.gpg.d/cubic-wizard-ubuntu-release.gpg
`

**Comment by PJ-Singh-001** [comment]
Done.
Thank you @richteas75 !!
