### ISSUE TITLE
Please stop creating `filesystem.manifest-minimal-remove`

### ISSUE THREAD

**Issue by hasanmerkit** [PJ-Singh-001/Cubic#143]
Since I do not use this file in the .ISO files I create, I always have to delete it manually.

Please stop create this file if not exists...

![image](https://user-images.githubusercontent.com/18331715/209310382-469a7a9c-dfd8-4e4e-a190-1ce0ed6d8274.png)

**Comment by PJ-Singh-001** [comment]
Can you remind me what the behavior is when this file is not present ? (I think Ubiquity simply doesn’t show the “minimal install” option, if I recall correctly?).

Why do you not want this file present? 
The regular installer has this file,  but it is optional to use it during installation. Why don’t you want to present this as an option to people who use your custom ISO?

**Comment by hasanmerkit** [comment]
Answer#1: No. That's problem. Some old ubiquity versions and alternate installer shows "minimal install" option if this file exists.
Answer#2: My Ubuntu customization is already removed some packages for make minimal installation.

**Comment by PJ-Singh-001** [comment]
I'll mark this an an enhancement for a future release.

The solution may be as follows:

- Add a checkbox for the user to select whether or not to generate the minimal install file.
- Implement criteria/rules when to show the checkbox (ie. older versions of Ubiquity do not show a minimal install option, so it does not make sense to show the checkbox).
- Hide/deactivate or show/activate the the minimal install column (i.e. second column) based on the status of the checkbox.
- Store the user's selection in the project's configuration file.

At this time, I can not provide a timeline when I will be able to add this feature to Cubic.

**Comment by hasanmerkit** [comment]
Thank you <3

**Comment by PJ-Singh-001** [comment]
Let's keep this issue open until the enhancement is released.

**Comment by PJ-Singh-001** [comment]
On the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page)...
- Add a switch in the header bar for the user to select whether or not to generate the minimal install file ( `*.manifest-minimal-remove`).
- The switch will be shown for Ubiquity >= 18.04.
- For Ubiquity < 18.04, the switch will not be shown, and the minimal install column will not be shown.
- If Ubiquity is not installed, per existing functionality, the Packages page is not shown.
- The switch will be "on" if a `*.manifest-minimal-remove` file exists.
- The switch will be "off" if a `*.manifest-minimal-remove` file does not exists.
- Correspondingly, the minimal install column will be shown if the switch is visible and is "on".
- The minimal install column will not be shown if the switch is visible and is "off".
- A `*.manifest-minimal-remove` file will be created if the switch is shown and is "on", otherwise the file will be removed or not created.

On the [Prepare page](https://github.com/PJ-Singh-001/Cubic/wiki/Prepare-Page), always identify and count the packages required for a minimal install, to pre-populate the minimal install column, in case the user activates the headerbar switch, when available. (Previously, the minimal install packages were only identified if the `*.manifest-minimal-remove` file existed). In cases where `*.manifest-minimal-remove` file does not exist, the packages to remove will match the packages to remove for a typical install, as a starting point for the user to customize.

There is no need to store the user's selection in the `cubic.conf` project configuration file, since the existence of the `*.manifest-minimal-remove` file is enough to record the user's choice.

![Typical Install Only](https://user-images.githubusercontent.com/19394936/222918569-08719a00-a129-45b5-a2fb-020e64fa6f48.png)
![Typical Install and Minimal Install](https://user-images.githubusercontent.com/19394936/222918574-68178eba-0b2c-4728-b07a-0d2e7da4175b.png)

**Comment by PJ-Singh-001** [comment]
Update:

We will store the user's selection in the `cubic.conf` project configuration file.

With this approach, there is there is no need to delete the `*.manifest-minimal-remove` file. As a result, the user can always chose to include the `*.manifest-minimal-remove` file in the future (without losing its original contents).

Thus updated rules are as follows:

- If Ubiquity is not installed, per existing functionality, the Packages page is not shown.
- Add a switch in the header bar of the Packages page for the user to select whether or not to generate the minimal install file ( `*.manifest-minimal-remove`).
- The switch will be shown for Ubiquity >= 18.04.
- The switch will not be shown for Ubiquity < 18.04.
- The minimal install column will not be shown for Ubiquity < 18.04.
- For new projects, the switch will be "on" by default for Ubiquity >= 18.04.
- For existing projects, the switch will be "on" or "off" based on the user's previous selection.
- The user's selection, whether or not to include the minimal install file, will be stored in the project's `cubic.conf` file.
- The minimal install column will be shown if the switch is visible and is "on".
- The minimal install column will not be shown if the switch is visible and is "off".
- A `*.manifest-minimal-remove` file will always be created.
- If Ubiquity >= 18.04 and the switch is "on", the `*.manifest-minimal-remove` file will be copied to the generated ISO.
- If Ubiquity >= 18.04 and the switch is "off", the `*.manifest-minimal-remove` file will not be copied to the generated ISO.
- If Ubiquity < 18.04, the `*.manifest-minimal-remove` file will not be copied to the generated ISO.
- If Ubiquity is not installed, the minimal install file will not be copied to the generated ISO.

**Comment by PJ-Singh-001** [comment]
Fix released in version 2023.03.76.

**Comment by hasanmerkit** [comment]
Thanks for work :)
But,
I switched off and i deleted /casper/filesystem.manifest-minimal-remove file, but Cubic still auto generating this file...
(File exists in original .iso file.)

1:
![1](https://user-images.githubusercontent.com/18331715/227709363-6c6bed1e-aa19-4aa8-a99b-e779f4512deb.png)

2:
![2](https://user-images.githubusercontent.com/18331715/227709369-98aae6e2-73e7-4050-b801-174dbc9075c4.png)

**Comment by PJ-Singh-001** [comment]
This is correct.

Cubic will [still generate this file, per the comments above](https://github.com/PJ-Singh-001/Cubic/issues/143#issuecomment-1455348709):

- _**A *.manifest-minimal-remove file will always be created.**_
- If Ubiquity >= 18.04 and the switch is "on", the *.manifest-minimal-remove file will be copied to the generated ISO.
- If Ubiquity >= 18.04 and the switch is "off", the *.manifest-minimal-remove _**file will not be copied to the generated ISO.**_

This way, the user can "undo" their selection in the future, when they are re-customizing their project. The idea is to not "throw away" the file.

The switch controls whether or not the file gets _copied_ to the generated `*.iso`.

Check you generated `*.iso` file.
The `*.manifest-minimal-remove` should not be on it, if you had turned the switch off in Cubic.

**Comment by PJ-Singh-001** [comment]
Re-opening this issue.

This enhancement was released in version 2023.03.76. However, there was a bug in the subsequent release, version 2023.03.77. The bug caused the `filesystem.manifest-minimal-remove` file to _always_ be copied to the generated ISO, even if the "+Minimal" toggle was switched off.

I will fix this along with Issue #213, [Cubic removes filesystem.manifest-remove from the generated ISO [Elementary OS]](https://github.com/PJ-Singh-001/Cubic/issues/213).

**Comment by PJ-Singh-001** [comment]
Fix released in version 2023.05-83.

Cubic no longer checks for Ubiquity to determine if the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page) should be shown.

Here is the updated logic:

**Standard install (`filesystem.manifest-remove` file):**
- If the original ISO has the `filesystem.manifest-remove` file, the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page) will be shown. This no longer depends on Ubiquity being installed. Therefore, this will work for all installers (such as `ubiquity`, `pop-installer`, `io.elementary.installer`, etc.) that use the `filesystem.manifest-remove` file.
- The customized `filesystem.manifest-remove` file is always created.
- The Standard packages column is always shown.
- If the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page) is shown, the customized `filesystem.manifest-remove` file will be copied to the generated ISO.
- If the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page) is not shown, the customized `filesystem.manifest-remove` file will not be copied to the generated ISO.

**Minimal install (`filesystem.manifest-minimal-remove` file):**
- The "＋Minimal" switch is always shown on the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page). This no longer depends on the version of Ubiquity installed. Therefore, this will work for all installers (such as `ubiquity`, `pop-installer`, `io.elementary.installer`, etc.).
- The customized `filesystem.manifest-minimal-remove` file is always created.
- If the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page) is not shown, the customized `filesystem.manifest-minimal-remove` file will not be copied to the generated ISO.
- When the "＋Minimal" switch is "on", the Minimal packages column will be shown.
- When the "＋Minimal" switch is "off", the Minimal packages column will not be shown.
- The "＋Minimal" switch will be "on" by default, if the original ISO has the `filesystem.manifest-minimal-remove` file.
- The "＋Minimal" switch will be "off" by default, if the original ISO does not have the `filesystem.manifest-minimal-remove` file.
- The user can toggle "＋Minimal" switch, regardless of the installer version.
- If the "＋Minimal" switch is "on", the `filesystem.manifest-minimal-remove` file will be copied to the generated ISO.
- If the "＋Minimal" switch is "off", the `filesystem.manifest-minimal-remove` file will not be copied to the generated ISO.

_Note, if you are customizing an existing Cubic project created using a version of Cubic prior to version 2023.05-83, the "＋Minimal" switch will be "on" by default, and you should manually toggle it to the "off" position, if you do not want the `filesystem.manifest-minimal-remove` file to be copied to the generated ISO. You only have to do this once, because your selection will be saved for the next time you edit your project._
