### ISSUE TITLE
Add support for Kali?

### ISSUE THREAD

**Issue by arnon001** [PJ-Singh-001/Cubic#147]
can cubic support other distros than ubuntu and debian (like kali)?

**Comment by PJ-Singh-001** [comment]
Is Kali based on Ubuntu ?

**Comment by arnon001** [comment]
it based Debian

**Comment by PJ-Singh-001** [comment]
Ok. I’ll take a look to see if it is possible.

**Comment by PJ-Singh-001** [comment]
This will be lower priority than some of the other critical Issues posted here. I'll look into it when I am able. In the mean time, I'll keep this Issue open.

**Comment by PJ-Singh-001** [comment]
Cubic does work with Kali.
On the Kali website, there are [multiple versions you can download](https://www.kali.org/get-kali).
You must select a Live version (such as [kali-linux-2022.4-live-everything-amd64.iso](https://cdimage.kali.org/kali-2022.4/kali-linux-2022.4-live-everything-amd64.iso.torrent)), because Cubic customizes Live ISOs.

**Comment by arnon001** [comment]
I think you might got the question worng,
I meant if you can run Cubic on Kali linux,
sorry for the misunderstanding

**Comment by PJ-Singh-001** [comment]
I successfully installed and ran Cubic on Kali 2020.2.
Cubic should also run on newer versions of Kali.
