### ISSUE TITLE
not finding package

### ISSUE THREAD

**Issue by landoncr2012** [PJ-Singh-001/Cubic#150]
it keeps saying "E: Unable to locate package cubic"

**To Reproduce**
![Screenshot 2023-01-20 6 38 08 PM](https://user-images.githubusercontent.com/88589878/213824022-6a02acbf-d736-4ab4-8523-d3798e1724ba.png)

Steps to reproduce the behavior.

**Expected behavior**

**OS Information (please complete the following information):**
 - OS/Distro Name: [e.g. Ubuntu, Mint, Kubuntu]
 - OS Version [e.g. Ubuntu 21.10]

**Cubic Information (please complete the following information):**
 - Cubic Version: [e.g. 2021.12.67 from the About dialog, or 2021.12-67-release from `dpkg -l`]
 - ISO Customizing: [e.g. ubuntu-21.10-desktop-amd64.iso]
 - Download Link:  The download link for the ISO you are customizing

**Cubic Log:**

 Cut and paste the log after running `cubic --verbose` from the command line

**Screenshots**

**Comment by opensensesolutions** [comment]
See the first line of your output where it says "sudo: apt-add-repository: command not found" ?  That's the problem, which has nothing to do with cubic.

Instead of pasting in the entire block of installation instruction commands in at once do them one at a time and look for errors.  Your debian system doesn't have the tool required to add the cubic repository.  Based on one google search I think you might just need to do this first to add the apt-add-repository functionality:

sudo apt-get install software-properties-common

**Comment by PJ-Singh-001** [comment]
@landoncr2012,

@opensensesolutions is absolutely correct.
Cut and paste each line separately.
(Thanks @opensensesolutions!!)

Beyond that, Cubic *does* work on Debian, but installation is an issue.

I have [asked Debain to accept Cubic into their repos](https://github.com/PJ-Singh-001/Cubic/issues/141#issuecomment-1345443705), but I have not heard back from them.

I'll close this issue based on @opensensesolutions suggestion.

If you are still not able to install Cubic on your system, open a new issue, and I'll see if I can help you.

**Comment by landoncr2012** [comment]
Wrong email address
