### ISSUE TITLE
invalid file name 'boot=casper' you need to load the kernel first error in disk image with Xubuntu 22.04

### ISSUE THREAD

**Issue by hirusha-adi** [PJ-Singh-001/Cubic#155]
**Describe the bug**

![image](https://user-images.githubusercontent.com/36286877/216837421-be3714af-7d14-41cd-a20a-057f7b24f39b.png)

**To Reproduce**

Everything was untouched except:
1. i copied the xfce4 folder to .config in /etc/skel
2. i copied the autostart folder with plank.desktop file to autostart plank to /etc/skel
3. i copied the .themes and .icons folders to /etc/skel

thats all

**Expected behavior**

The final disk image to work properly

**OS Information:**
 - OS/Distro Name: Xubuntu
 - OS Version Xubuntu 22.04

**Cubic Information (please complete the following information):**
 - Cubic Version:
 ```
user@user-vm:~$ dpkg -l | grep "cubic"
ii  cubic                                 2022.11-73-release~202211192040~ubuntu22.04.1       all          Wizard to create a customized Ubuntu Live ISO image.
```
 - ISO Customizing: xubuntu-22.04.1-desktop-amd64.iso
 - Download Link:  The download link for the ISO you are customizing

**Cubic Log:**

-

**Screenshots**

![image](https://user-images.githubusercontent.com/36286877/216837417-e517c100-e68f-4946-b685-c8cb32930661.png)

**Comment by PJ-Singh-001** [comment]
On the grub screen, would you please press <kbd>e</kbd> and share what the boot command looks like?

**Comment by PJ-Singh-001** [comment]
I see that you are using an older version of Cubic, 2022.11-73.

The problem you have reported was fixed in Issue "[Error invalid file name 'boot=casper' when booting from an ISO created with Cubic version 2022.11.73](https://github.com/PJ-Singh-001/Cubic/issues/130)".

The current version of Cubic, version 2022.12.74, has the fix.

Use `sudo apt update && sudo apt install cubic` to update to the latest version.

As a side note, you can search for closed Issues [here](https://github.com/PJ-Singh-001/Cubic/issues?q=is%3Aissue+is%3Aclosed), to check if a solution to your problem has already been posted.

**Comment by hirusha-adi** [comment]
thank you
