### ISSUE TITLE
Why is the Packages page not shown (Linux Mint 21.1)?

### ISSUE THREAD

**Issue by c05772** [PJ-Singh-001/Cubic#160]
I want to access the Packages Page  (Cubic Packages Page.png in the screen shots).

I use Linux Mint 21.1 and version 2023.02.75. Everything works OK but I cannot really customize because after the Prepare Page I get directly to the Kernel tab page without the possibility to check or uncheck packages  as shown in the screen shots.

I installed Cubic from the Mint package Manager first, then uninstall it and tried the command line method  given on https://github.com/PJ-Singh-001/Cubic

In both cases I install the same version number and get the same result: I cannot access the Packages Page (). 

However everything else works fine and I get a workable ISO.

**OS Information (please complete the following information):**
 - OS/Distro Name: Linux Mint 21.1 Cinnamon
 - OS Version : Linux Mint 21.1 -  Cinnamon 5.6.7
 
**Cubic Information (please complete the following information):**
 - Cubic Version: 2023.02.75
 - ISO Customizing: linuxmint-21.1-cinnamon-64bit.iso
 - Download Link:  https://muug.ca/mirror/linuxmint/iso/stable/21.1/linuxmint-21.1-cinnamon-64bit.iso

**Screenshots**
 This page is not accessible:
https://github.com/PJ-Singh-001/Cubic/blob/release/screenshots/Cubic%20Packages%20Page.png

**Comment by PJ-Singh-001** [comment]
**What is the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page) used for?**

- It helps configure how the [Ubiquity installer](https://wiki.ubuntu.com/Ubiquity) operates.
- The Ubiquity installer will UNINSTALL selected packages AFTER the OS has been installed to your COMPUTER.
- The [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page) is NOT used to select packages that are installed on your COMPUTER.
- Instead, to install packages on your Live ISO and your computer, use `apt install` on the command line on the [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page).
- The [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page) is NOT used to remove packages installed on your COMPUTER.
- Instead, to not have packages on your Live ISO and your computer, use `apt autoremove` on the command line on the [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page).

**Why / when would I use the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page)?**

Use the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page) when you need certain software in the Live ISO Environment, but you do not need that software once the OS is installed to your computer.

A good example is [GParted](https://gparted.org). You might want to make GParted available for the person using the LiveISO, so she can manually partition her disk, before installing the OS to her computer. Once the OS is installed, there is no need for GParted. To achieve this, she would execute `apt install gparted` on the [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page) to install the software. Then, on the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page), she would check-mark GParted for automatic removal from the COMPUTER by Ubiquity, AFTER the customized OS is installed.

Another example of a package you want removed after your OS has been installed is the [Ubiquity installer](https://wiki.ubuntu.com/Ubiquity) itself. If you do not select Ubiquity for removal on the Packages page, the user will get an "Install Ubuntu" icon in their dock and decktop after they have installed their new customized OS. (That would be confusing, and running this software will probably overwrite or destroy their OS!)

**Why can I not see the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page) in Cubic?**

Since the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page) is used to configure the [Ubiquity installer](https://wiki.ubuntu.com/Ubiquity), it only appears in Cubic if you have Ubiquity installed.

If your OS uses as different installer, you will not see the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page). For example, Pop_OS! and Elementary both use the Elementary installer instead of [Ubiquity installer](https://wiki.ubuntu.com/Ubiquity).

If you have an older version of Ubiquity that does not support minimal installs, you will only see one column of check-boxes on the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page). Therefore, if you are customizing Ubuntu based distros prior to Ubuntu 18.04, you will only see a single column of check-marks on the  [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page). Newer versions of Ubiquity support both minimal and regular installs, so two columns of check-marks will be shown, corresponding to these two types of installs.

You can install Ubiquity using `apt install ubiquity`. Of course, you should uninstall the other installer that comes with your OS. Then, you may also have to configure Ubiquity to install your particular OS. This can be quite complicated, so I strongly suggest sticking with the installer that comes with your OS.

**What about Linux Mint?**

If Linux Mint does actually use the [Ubiquity installer](https://wiki.ubuntu.com/Ubiquity), let me know. In that case you should be able to see the  [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page).
