### ISSUE TITLE
How to update iptables?

### ISSUE THREAD

**Issue by vervaekejonathan** [PJ-Singh-001/Cubic#17]
Cubic-ing a ubuntu 18.04.6 live server iso.
When trying to configure the firewall, some error is popped up:

```
# /usr/sbin/ufw status verbose
ERROR: problem running iptables: iptables v1.6.1: can't initialize iptables table `filter': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
```

**Comment by PJ-Singh-001** [comment]
Services, such as `ufw` do no run in the Terminal environment in Cubic.

The terminal is not a "running" OS. Instead it is a list files to which you have root access. This allows you to modify any files you need to in order to customize your system. Therefore, you can not rely on services to do the configuration for you-- you have to make the changes manually.

The reason for this is, if services could run, they could modify your system without you knowing. They would also create lots of logs and other files that you do not know about. All of these unnecessary files would end up on your customized OS.

It may be possible for you to setup the `ufw` rules manually.

Look at these files:

    ./usr/share/ufw
    ./usr/share/lintian/overrides/ufw
    ./usr/share/doc/ufw
    ./usr/sbin/ufw
    ./usr/lib/ufw
    ./usr/lib/python3/dist-packages/ufw
    ./etc/ufw
    ./etc/logrotate.d/ufw
    ./etc/init.d/ufw
    ./etc/default/ufw

Keep in mind, the container (Cubic's Terminal environment) uses the Host's network.

In fact, the IP address is the same. You can see this if you execute...

    ip addr show

...on both the host machine and in Cubic.
