### ISSUE TITLE
Screenfetch recognizes OS as Ubuntu 18.04

### ISSUE THREAD

**Issue by xybytz** [PJ-Singh-001/Cubic#175]
**Describe the bug**

I was remastering Ubuntu 18.04 (Bionic Beaver). I renamed it to Rubuntu "Sussy Superman" (do not question the name). However, when I install screenfetch, and then run the command, it Recognizes it as Ubuntu 18.04 bionic. 

**To Reproduce**

1. Start with Ubuntu 18.04 iso
2. Install Wine Stable on the virtual environment
3. Use xz compression
4. Note: Everything else is default, such as the packages installed (other than Wine).

**Expected behavior**

I want Screenfetch to recognize it as Rubuntu Sussy Superman. I do not think this is a problem with screenfetch, rather a problem with the automatic configuration.

**OS Information (please complete the following information):**
 - OS/Distro Name: Ubuntu
 - OS Version Host: 22.04 ; Final Product: 18.04

**Cubic Information (please complete the following information):**
 - Cubic Version: 2023.02.75
 ubuntu 18.04 from official repo
 - Download Link:  n/a

**Cubic Log:**

 Cut and paste the log after running `cubic --verbose` from the command line
Cubic - Custom Ubuntu ISO Creator                                               

  • Set application directory.............. /usr/share/cubic                    
  • Set application user home.............. /home/pac                           
  • Execute synchronously.................. dpkg-query                          
                                            --admindir="/var/lib/dpkg" --show   
                                            --showformat="${Version} " "cubic"  
  • The process id is...................... 58643                               
  • Set application cubic version.......... 2023.02-75-                         
                                            release~202302190210~ubuntu22.04.1  
  • Set application kernel version......... 5.19.0-35-generic                   

  Setup pages                              

  • Setup.................................. boot copy page                      
  • Setup.................................. compression page                    
  • Setup.................................. delete page                         
  • Setup.................................. extract page                        
  • Setup.................................. finish page                         
  • Setup.................................. generate page                       
  • Setup.................................. migrate page                        
  • Setup.................................. options page                        
  • Setup.................................. packages page                       
  • Setup.................................. prepare page                        
  • Setup.................................. preseed copy page                   
  • Setup.................................. project page                        
  • Setup.................................. start page                          
  • Setup.................................. terminal copy page                  
  • Setup.................................. terminal page                       
  • Set terminal colors?................... Yes                                 
  • Setup.................................. test 1 page                         
  • Setup.................................. test 2 page                         

  Setup file choosers                      

  • Setup (ignore warnings)................ copy file chooser                   

(cubic:58638): Gtk-WARNING **: 12:11:56.078: Content added to the action area of a dialog using header bars

(cubic:58638): Gtk-WARNING **: 12:11:56.078: Content added to the action area of a dialog using header bars
  • Setup (ignore warnings)................ directory chooser                   

(cubic:58638): Gtk-WARNING **: 12:11:56.119: Content added to the action area of a dialog using header bars

(cubic:58638): Gtk-WARNING **: 12:11:56.120: Content added to the action area of a dialog using header bars
  • Setup (ignore warnings)................ iso image chooser                   

(cubic:58638): Gtk-WARNING **: 12:11:56.160: Content added to the action area of a dialog using header bars

(cubic:58638): Gtk-WARNING **: 12:11:56.160: Content added to the action area of a dialog using header bars

Handle navigation from no page on open action                                   

  • Interrupt previous thread.............. No thread                           

Get the new page                                                                

  • Current page........................... no page                             
  • Action................................. open                                
  • New page............................... start page                          

Navigate from no page to start page on open action                              

  • The thread id is....................... 140090290468416                     
  • Set application configuration.......... /home/pac/.config/cubic/cubic.conf  

  Load application configuration           

  • Load application configuration......... 2022 layout from                    
                                            /home/pac/.config/cubic/cubic.conf  
  • Set application visited sites.......... []                                  
  • Set application projects............... ['/home/pac/cubic2',                
                                            '/home/pac/os2',                    
                                            '/home/pac/Desktop/RoshanOS4']      
  • Set application iso file path.......... /home/pac/Downloads/ubuntu.iso      

  Transition pages                         

  • Show new page.......................... start page                          

**Screenshots**
![image](https://user-images.githubusercontent.com/95513381/226442369-b47ce510-608d-457f-9bdd-c90080bf7e16.png)

**Comment by PJ-Singh-001** [comment]
I had responded to this a few days ago, but it looks like my comment did not get recorded...

Check with Screenfetch and find out where they pull this information from, and then modify the corresponding file while you are customizing Ubuntu.

Check-marking on the "OS Release" check-box on the [Project page](https://github.com/PJ-Singh-001/Cubic/wiki/Project-Page) will update the release description you see as the "OS Name" in the "About" section of System Settings. This corresponds to the output of the `lsb_release --description` command. However, from your screenshot, it is clear that Screenfetch does not use this information in its display.

Screenfetch is getting its information some other way, and you will have to find out what that is, and change it manually while Customizing your ISO. (Remember, you can use `nano` to edit files while in [Cubic's Terminal Environment](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page)).

When you figure this out, please share the solution!

**Comment by xybytz** [comment]
Did some digging, found out one must manually change the /etc/os-release and/or the /etc/lsb-release file. Could you make it so that Cubic does this automatically?

**Comment by xybytz** [comment]
I will check which one is affected in the already running os and change it there, and see which one was already changed.

**Comment by PJ-Singh-001** [comment]
OK. This is good research.

In that case, I suggest updating `/etc/lsb-release`, `/etc/os-release`, and `/usr/lib/os-release`. Some distributions use one or the other of these files. Do you know which field(s) in these files Screenfetch pulls information from? You should update the correct field(s) in each file for consistency.

Cubic already updates `DISTRIB_DESCRIPTION` in `/etc/os-release` and `PRETTY_NAME` in `/etc/os-release` and `/usr/lib/os-release`. This is done when you check-mark "OS Release" on the [Project page](https://github.com/PJ-Singh-001/Cubic/wiki/Project-Page).

I do not have plans to update any of the other fields in these files, because Cubic's philosophy is to not customize the OS for the user; rather Cubic unpacks and repacks the ISO for the user, incorporating all of the user's changes. With this philosophy in mind, updating the above fields is the _only_ thing Cubic modifies inside the custom Linux file system on behalf of the user, and this is done _only when the user grants permission_ by selecting the "OS Release" check-box. This capability was added to accommodate user requests some years ago, because users wanted to be able to tell if and when their OS was customized by Cubic. All other changes, updates, and customizations in the Linux File system are left to the user.

There are a few caveats you should be aware of when changing these files:
1. `apt` uses values from these files to determine which version of Ubuntu you are running.
2. Changing some of the other fields (other than `DISTRIB_DESCRIPTION` and `PRETTY_NAME`) may interfere with `apt` and with updates or upgrades to your customized OS.
3.  When doing an `upgrade` or `dist upgrade`, `apt` _may_ overwrite your changes to these files.

Based on your experience, it seems that Screenfetch uses some of the other fields (other than `DISTRIB_DESCRIPTION` and `PRETTY_NAME`, that Cubic already can change) to display OS information. Proceed with caution when updating those.

**Comment by asakpke** [comment]
> '/home/pac/Desktop/RoshanOS4']

@xybytz What's the RoshanOS4 on the Desktop?
