### ISSUE TITLE
Linux Mint Install taking 30+ minutes

### ISSUE THREAD

**Issue by mopfel-winrux** [PJ-Singh-001/Cubic#176]
**Describe the question**

I'm installing a custom version of Linux Mint 21. The ISO installs and runs but it takes a long time; 30+ minutes. when looking at the logs I notice that its trying to access the internet. The boxes I'm installing it on don't have internet access. Is there a way to speed this up?

**What you have tried**

Tried messing with the preseed file but no luck.

**Expected behavior**

Install quickly from the ISO only

**OS Information (please complete the following information):**
 - OS/Distro Name:: Linux Mint
 - OS Version 21

**Cubic Information (please complete the following information):**
 - Cubic Version: 2022.12.74
 - ISO Customizing: linuxmint-21.1-mate-64bit.iso
 - Download Link: https://linuxmint.com/edition.php?id=303

**Screenshots**

N/A

**Comment by PJ-Singh-001** [comment]
I do not recall the Mint installation dialog, but is there a "Install Updates" checkbox? If so disable that.
Also, before starting the installation, try disabling the network interface.
You should be able to do this graphically, or you could do it from the command line:

    ifconfig <interface name> down

(I've had similar issues on Ubuntu, and I am usually able to disable networking from the System menu in the Live Environment before starting the installation).

Lastly, I wonder if you could remove networking packages while customizing the ISO in Cubic, if you will never need networking?

**Comment by PJ-Singh-001** [comment]
I did some informal tests with the [ISO you linked to above](https://linuxmint.com/edition.php?id=303).

I tested installing into a virtual machine in VirtualBox. I disabled networking in VirtualBox to simulate your scenario.

It took about 8 minutes from the time I launched the installer to the time it completed installation. This established a baseline. (This did include time for me to click through the installer and type requested information, so these test were not very scientific).

I noticed that installer does attempt to lookup information on the internet, such as network time.

For the second test, I attempted to change the  network time-out parameter to see if this helps.

    nano /usr/lib/systemd/system/networking.service

Change...

    TimeoutStartSec=5min

...to...
    TimeoutStartSec=0min

Unfortunately, this did not make a significant difference in installation time from the baseline.

For the third test, I noticed that the installer tried to fetch packages from the configured Mint repos. I disabled all of these repositories by commenting them out, as shown here.

    nano /etc/apt/sources.list.d/official-package-repositories.list

    # Do not edit this file manually, use Software Sources instead.

    # deb http://packages.linuxmint.com vera main upstream import backport #id:linuxmint_main

    # deb http://archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
    # deb http://archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
    # deb http://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse

    # deb http://security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse

Unfortunately, this did not make a significant difference in installation time from the baseline.

Thus, I could not significantly change the installation time, compared to my baseline.

The two major steps the installer takes are:
1. Copying files
2. Removing unnecessary files (packages)

In your case, the disk you are installing to may be slow, or your USB may be slow to read from. You can make sure you have removed all unnecessary packages while customizing Mint on Cubic's [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), especially things like language packs that you do not need. Packages that are removed by the installer after a successful installation are listed on Cubic's [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page). You can use the packages listed here as a guideline about what you can remove. Be careful to not remove stuff that the Live Environment absolutely needs like the Ubiquity installer itself. By taking this step, you may be able to reduce the amount of time the installer takes _removing_ files that have been copied to your disk. This will also have the benefit of reducing the amount of files that are copied to your disk in the first place.

I still suggest you try to reduce the network time out and comment out the package repositories as I did in my second and third tests, since this may benefit your system, even though it made no difference on my system.

Also, you may want to bypass installing your customized OS from an installation media (such as a USB or DVD). You can install directly from your hard disk/ssd. Take a look at [these instructions](https://github.com/PJ-Singh-001/Cubic/issues/154#issuecomment-1414524086); when following these instructions, make sure your ISO is placed on a partition that will _not_ be formatted during installation, and chose "Something else" in the installer to select which partitions the installer will install to and format.

**Comment by PJ-Singh-001** [comment]
Your issue may stem from the actual hardware you are using, since my test installs took less than 10 minutes. I suggest trying some of [my recommendations above](https://github.com/PJ-Singh-001/Cubic/issues/176#issuecomment-1501150567) to (possibly) help reduce your installation times.

I am going to close this issue, with the response provided above.

**Comment by mopfel-winrux** [comment]
Thank you for your help! I'll try this asap
