### ISSUE TITLE
unable to inform the kernel of the change -ubuntu-22.04.2-desktop-amd64

### ISSUE THREAD

**Issue by mohaddesehrezaee** [PJ-Singh-001/Cubic#180]
Hi, I have tried customization on ubuntu-22.04.2-desktop-amd64.iso and I used the below scripts for customizing: 
```
apt-get update && apt-get upgrade 
apt install python3 vlc make curl wget git dkms gcc 
dpkg -i google-chromexx.deb 
adduser <username>
```

I made no changes on grub.cfg and ubuntu.seed and made a bootable 32GB flash using the balenaEtcher app. there is just one kernel 5.19.0 identified. when I am installing the OS I face this page and the installation would not be successful. what would be the problem? I don't meet this error while installing the original iso image. 

cubic version: 2023.03.79

I really appreciate any help you can provide.

![20230326_155154](https://user-images.githubusercontent.com/96718772/227781812-de4b098b-fc18-4d16-ad25-b1e958b0a057.jpg)

![Uploading 20230326_155421.jpg…]()

![20230326_155233](https://user-images.githubusercontent.com/96718772/227781768-a9072148-c2b2-4848-b63b-4ff73c388aae.jpg)

**Comment by PJ-Singh-001** [comment]
Are you installing the OS from a `*.iso` file on the disk, or are you installing from a USB stick ?

**Comment by mohaddesehrezaee** [comment]
> Are you installing the OS from a `*.iso` file on the disk, or are you installing it from a USB stick?

I've put the generated iso on a USB using balenaEtcher and for generating customized iso in cubic I used  *.iso file.

![Uploading Screenshot from 2023-03-27 09-35-17.png…]()
and while using qemu to test the generated iso I see this 
![Screenshot from 2023-03-27 10-01-30](https://user-images.githubusercontent.com/96718772/227859105-34eb56a5-ac90-49a9-8abf-ee701db5362d.png)

**Comment by PJ-Singh-001** [comment]
You wouldn't be able to install the OS in QEMU. There is no physical disk there. You can use QEMU to test the live environment, make sure your customizations are working, and simply ensure your ISO boots.

**Comment by PJ-Singh-001** [comment]
The message is telling you that one of the disk partitions that the installer is trying to write to is currently in use.
It could be that you have:
- Accidentally mounted a disk partition before starting the installation process
- Or, booted into the `*.iso` file on your disk rather than from a USB
- Or, attempted to install some portion of your OS to the USB (perhaps the boot loader?)

![image](https://user-images.githubusercontent.com/19394936/228015155-4d5763a8-54d6-48c7-946c-aa56ae41eaca.png)

Make sure that any partition you are attempting to format or any partition you are attempting to install any portion of your OS to (such as boot loader, or `/` root folder, etc.) is not mounted.

You can see what's mounted using the "Disks" app.
![image](https://user-images.githubusercontent.com/19394936/228017306-8fa364ff-eacc-4897-9bca-99a8de6ce40b.png)

**Comment by mohaddesehrezaee** [comment]
Thanks for helping me. The problem solved via using rufus with MBR,FAT32 setting
