### ISSUE TITLE
How to customize Linux Mint Cinnamon wallpaper, icons, and theme?

### ISSUE THREAD

**Issue by ImGGAAVVIINN** [PJ-Singh-001/Cubic#184]
**Describe the question**

I want to change default theme in a Linux Mint desktop

**What you have tried**

I have tried to do
gsettings set org.cinnamon.theme name "My Theme Name"
And I have tried to just straght up replace Mint-Y-Aqua with my theme but the task did not have the theme applied

**Expected behaviour**

I want to know a way how I can set the default theme in Linux Mint in Cubic.

**Screenshots**
![Screenshot_20230329_082557](https://user-images.githubusercontent.com/68761233/228370547-d8175697-c13e-4632-b081-07282c08e0fd.png)

**Comment by PJ-Singh-001** [comment]
Gsettings are applied on a per-user basis. Executing `gsettings set org.cinnamon.theme name "My Theme Name"` in a running OS would change the theme for the currently logged in user, but other users' themes would not be affected.

However, in [Cubic's Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), there are no users because the OS has not been installed yet, but you do have read/write access to _all_ files in the Linux file system.

Therefore, the approach when customizing the OS is to change specific (configuration) files, so that once the OS is run in a Live ISO Environment or once the OS is installed, the OS can read those files and behave the way you want it to.

Take a look at Issue #22,  [How to customize the wallpaper, icon theme, desktop theme, and Plymouth boot splash theme (in English & Japanese)?](https://github.com/PJ-Singh-001/Cubic/issues/22#issuecomment-1032011784)

The instructions in Issue #22 are for Ubuntu, but you can easily adapt them to Cinnamon.

For example, in the "Configure Defaults" section of the instructions, instead of...

    # Default Desktop Theme
    [org.gnome.desktop.interface:ubuntu]
    gtk-theme = "Materia"

...you would use...

    # Default Desktop Theme
    [org.cinnamon.theme]
    name = "My Theme Name"

...which you can see is equivalent to the `gsettings set org.cinnamon.theme name "My Theme Name"` command you had mentioned above.

_Tip: To search through questions that have already been answered, click on "[Closed](https://github.com/PJ-Singh-001/Cubic/issues?q=is%3Aissue+is%3Aclosed)" (next to "Open" on the [Issues tab](https://github.com/PJ-Singh-001/Cubic/issues) of the [Cubic Github page](https://github.com/PJ-Singh-001/Cubic)), type your search text in the "Filters" text entry, and press <kbd>Enter</kbd>._

**Comment by ImGGAAVVIINN** [comment]
And for the file, should I use 90_ubuntu-settings.gschema.override? or should I use other file names?
For example I found a file called 10_cinnamon.gschema.override, should I use it?

**Comment by PJ-Singh-001** [comment]
You can use a different name. Make sure it starts with a higher number, because higher number `*.gschema.override` files override the settings in lower numbered files.

Leave `10_cinnamon.gschema.override` and do not change it.

I suggest creating a new file named `zz_cinnamon-settings.gschema.override` with your new settings.

**Comment by PJ-Singh-001** [comment]
@ImGGAAVVIINN,

I think I found the issue you are having.
I'll write up a solution in the next couple of days.

**Comment by PJ-Singh-001** [comment]
@ImGGAAVVIINN,

I think I found the issue you are having.
I'll write up a solution in the next couple of days.

**Comment by PJ-Singh-001** [comment]
## Install Wallpapers

 1. On Cubic's [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), create a directory (or directories) for your custom wallpapers.

        mkdir /usr/share/backgrounds/my-backgrounds

    (You can replace the `my-backgrounds` directory name with whatever name you like).

 2. Change directory to the new wallpapers directory.

        cd /usr/share/backgrounds/my-backgrounds

 3. On your host computer, open a File browser (such as Nautilus), and drag your wallpaper(s) onto on Cubic's [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page).

    Click the Copy button to copy the file(s) into the current directory (`/usr/share/backgrounds/my-backgrounds`).

 4. On your host computer, open a new text document using Gedit or other text editor, and add the following contents.

        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE wallpapers SYSTEM "gnome-wp-list.dtd">
        <wallpapers>
          <wallpaper>
            <name>My First Wallpaper</name>
            <filename>/usr/share/backgrounds/my-backgrounds/my_first_wallpaper.png</filename>
            <options>zoom</options>
            <pcolor>#ffffff</pcolor>
            <scolor>#000000</scolor>
            <shade_type>solid</shade_type>
          </wallpaper>
          <wallpaper>
            <name>My Second Wallpaper</name>
            <filename>/usr/share/backgrounds/my-backgrounds/my_second_wallpaper.png</filename>
            <options>zoom</options>
            <pcolor>#ffffff</pcolor>
            <scolor>#000000</scolor>
            <shade_type>solid</shade_type>
          </wallpaper>
        </wallpapers>

    - You can replace "My First Wallpaper" and "My Second Wallpaper" with whatever names you like.

    - Use the same file path from Step 1 above, for example `/usr/share/backgrounds/my-backgrounds`.

    - Ensure the wallpaper names ("my_first_wallpaper.png", "my_second_wallpaper.png"., etc.) match the actual file names of your wallpapers.

    - You can add other wallpapers by including additional `<wallpaper>...</wallpaper>` tags.

 5. Save this file. For example, you may name it `my-wallpapers.xml`.

 6. On Cubic's [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), change directory to the background properties directory.

        cd /usr/share/gnome-background-properties

 7. Open a File browser (such as Nautilus), and drag your background properties file (`my-wallpapers.xml`) onto on Cubic's [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page).

    Click the Copy button to copy the file into the current directory (`/usr/share/gnome-background-properties`).

## Install Icons

 1. On Cubic's [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), install your icon theme, such as [Elementary](https://github.com/elementary/icons).

        apt install elementary-icon-theme

 2. Verify that your icons were installed to the correct location.

        ls -1d /usr/share/icons/elementary*

        /usr/share/icons/elementary

## Install Theme

 1. On Cubic's [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), install your desktop theme, such as [Materia Theme](https://github.com/nana-4/materia-theme).

        apt install materia-gtk-theme

 2. Verify that your theme was installed to the correct location.

        ls -1d /usr/share/themes/Materia*

        /usr/share/themes/Materia
        /usr/share/themes/Materia-compact
        /usr/share/themes/Materia-dark
        /usr/share/themes/Materia-dark-compact
        /usr/share/themes/Materia-light
        /usr/share/themes/Materia-light-compact

## Configure Defaults

 1. On your host computer, open a new text document using Gedit or other text editor, and add the following contents.

        # Default Wallpaper
        [org.cinnamon.desktop.background]
        picture-uri='file:///usr/share/backgrounds/my-backgrounds/my_second_wallpaper.png'

        # Default Icon Theme
        [org.cinnamon.desktop.interface]
        icon-theme='elementary'

        # Default Desktop Theme
        [org.cinnamon.theme]
        name='Materia'

    Make sure you reference the correct wallpaper path, icon theme name, and desktop theme name from the previous steps.

 2. Save this file as `zz_cinnamon-settings.gschema.override`.

    **Important:** Gschema files are prioritized alphanumerically, so you must prefix your `*.override` file with `zz` to ensure your customizations have higher priority than the default customizations. In Linux Mint, `mint-artwork.gschema.override` already contains keys and values for `org.cinnamon.desktop.background`, `org.cinnamon.desktop.interface`, and `org.cinnamon.theme`. Therefore, you must prefix your `*.gschema.override` file with any character that comes after `m`; I chose `zz` to ensure nothing else takes a higher precedence, and this is easy to verify in a directory listing. Do not modify `mint-artwork.gschema.override` directly, because this file may be reverted by a future update or upgrade, and your customizations will be lost.

 3. On Cubic's [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), change directory to the schemas directory.

        cd /usr/share/glib-2.0/schemas

 4. Open a File browser (such as Nautilus), and drag your schema file (`zz_cinnamon-settings.gschema.override`) onto on Cubic's [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page).

    Click the Copy button to copy the file into the current directory (`/usr/share/glib-2.0/schemas`).

 5. On Cubic's [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), compile the schemas.

        glib-compile-schemas /usr/share/glib-2.0/schemas
