### ISSUE TITLE
Custom Plymouth theme works during shut down, but not during boot

### ISSUE THREAD

**Issue by ImGGAAVVIINN** [PJ-Singh-001/Cubic#185]
**Describe the question**

I have follow the instruction on 
https://github.com/PJ-Singh-001/Cubic/issues/5#issuecomment-1001224949
But the theme only shows when the os is shutting down, not during the startup

**What you have tried**

I have tried to run 
sudo update-initramfs -u
and
update-initramfs -uk all
I have tried to give the custom theme priority of 400 when running update-alternatives --install
I have also tried to just replace the default Plymouth theme with my custom splash screen

**Expected behavior**

The Plymouth theme is applied and it shows when the os is starting up and shutting down

**Screenshots**

Doesn't work on start up
![image](https://user-images.githubusercontent.com/68761233/228962992-46f66b61-f09f-4e72-85e1-4b862ed2e07a.png)
Works when shutting down
![image](https://user-images.githubusercontent.com/68761233/228964302-d0c8e71b-d822-4921-ac09-49c4ac1de458.png)

**Comment by PJ-Singh-001** [comment]
The ISO has its own Plymouth theme, which comes from the `initrd` file used to bootstrap the ISO.
You are most likely using the defailt `initrd` file that came with the ISO.
In order to select a different (customized) `initrd` file, you need to install a kernel. (You probably already did that, even though you did not mention it in your issue report).

You can select your new kernel as the bootstrap kernel on the [Options page, Kernel tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#kernel-tab).

Note that, by default, the Linux Mint ISO does not have kernel files installed in `\boot`. As you can see here, all `initrd.img` and `vmlinuz` are broken symlinks:

    You have entered the virtual environment.
    root@cubic:~# cd /boot
    root@cubic:/boot# ls -la
    total 6360
    drwxr-xr-x  3 root root     180 Dec 17 10:43 .
    drwxr-xr-x 17 root root     460 Dec 17 10:43 ..
    -rw-------  1 root root 6250186 Nov 22 10:08 System.map-5.15.0-56-generic
    -rw-r--r--  1 root root  261842 Nov 22 10:08 config-5.15.0-56-generic
    drwxr-xr-x  2 root root      80 Dec 17 10:41 grub
    lrwxrwxrwx  1 root root      28 Dec 17 10:40 initrd.img -> initrd.img-5.15.0-56-generic
    lrwxrwxrwx  1 root root      28 Dec 17 10:40 initrd.img.old -> initrd.img-5.15.0-56-generic
    lrwxrwxrwx  1 root root      25 Dec 17 10:40 vmlinuz -> vmlinuz-5.15.0-56-generic
    lrwxrwxrwx  1 root root      25 Dec 17 10:40 vmlinuz.old -> vmlinuz-5.15.0-56-generic
    root@cubic:/boot# 

If you are not able to use a different kernel, because the ISO will not boot, your installed kernel (and corresponding `initrd` file will still be used once you install the ISO to a computer. At that point you should see your Plymouth changes for both boot-up and shut-down.
