### ISSUE TITLE
How to change the user name in the live enviroment?

### ISSUE THREAD

**Issue by MacroHard-Winux** [PJ-Singh-001/Cubic#189]
In Linux Mint, when you are booting from a live environment, the user name is mint. And I want to change it into live user, but I can't find a way online to change it.

**Comment by PJ-Singh-001** [comment]
Are you looking to _only_ change the Live Environment user, or are you OK with creating users that will be available _both_ in the Live Environment _and_ after the OS is installed?

If it it is the later, this will work for you: #3, [How to create custom users on the login screen?](https://github.com/PJ-Singh-001/Cubic/issues/3#issuecomment-997134540).

**Comment by ImGGAAVVIINN** [comment]
I want to only change the user name in live environment and allow the user to set their name during installation in the ubiquity installer

**Comment by ImGGAAVVIINN** [comment]
Sorry I used the wrong account when postin this issue :P

**Comment by PJ-Singh-001** [comment]
The following solution works for Ubuntu versions that use the Ubiquity installer.
- All Ubuntu Desktop Live ISOs prior to and including 22.10.
- All Ubuntu Server Live ISOs prior to and including 21.04.

Ubuntu Desktop 23.04 and Ubuntu Server 21.10 started using the Subiquity snap instead of Ubiquity, so the installer can not (currently) be configured in Cubic.

Unfortunately this solution did not work for Linix Mint, when I tested using Linux Mint 19.1.

However, I suggest you try it yourself, since you may have better luck. You can use this solution as a guideline for your research-- the Linux Mint team may be customizing an additional file that I have missed; if you can figure out what that is, you should be able to change the Live user name.

 1. Make sure you have kernel files in the `/boot` directory.

    If `initrd` or `vmlinuz` files are missing or are symlinks to missing files, install a kernel. 

        apt update
        apt install linux-headers-5.4.0-99 linux-headers-5.4.0-99-generic linux-image-5.4.0-99-generic

    Remember which kernel you installed, so you can use it in step 6 below.

 2. Install `initeamfs-tools` and `casper`.

        apt install initramfs-tools
        apt install casper

 3. Make a backup of `casper.conf`.

    This file contains the Live user name.

        cp /etc/casper.conf ~/

 4. Edit `casper.conf`.

        nano /etc/casper.conf

    Update the Live user name (`USERNAME=`).
    You can also update the Live user's full name and the Live system's host name.

    You **must** uncomment `export FLAVOUR=` and ensure it is a non-empty string.

        # This file should go in /etc/casper.conf
        # Supported variables are:
        # USERNAME, USERFULLNAME, HOST, BUILD_SYSTEM, FLAVOUR

        export USERNAME="test"
        export USERFULLNAME="Live session user"
        export HOST="ubuntu"
        export BUILD_SYSTEM="Ubuntu"

        # USERNAME and HOSTNAME as specified above won't be honoured and will be set to
        # flavour string acquired at boot time, unless you set FLAVOUR to any
        # non-empty string.

        export FLAVOUR="Ubuntu"

 5. Update initramfs for all kernels in `/boot` to incorporate the above change.

        update-initramfs -uk all

 6. Select the updated kernel.

     Navigate to the [Options page](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page), and click on the [Kernel tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#kernel-tab).

     Select one of the kernels in `/boot`. This will include the kernel you installed in step 1.
     (Do not select the kernel used to bootstrap the original disk, because this kernel is simply copied from the original ISO and was not updated in step 5 with your changes).

 7. Generate your ISO and [test](https://github.com/PJ-Singh-001/Cubic/wiki/Finish-Test-Page).

**Comment by ImGGAAVVIINN** [comment]
It works ty :D
