### ISSUE TITLE
How to skip the disk check when booting up from the ISO?

### ISSUE THREAD

**Issue by ImGGAAVVIINN** [PJ-Singh-001/Cubic#190]
**Describe the question**

How to disable the disk check when the system is booting up? I am testing the OS and I don't want to smash repeatedly Ctrl+C everything I boot up the test VM

**Expected behaviour**

I want the system to boot up without the disk check because it takes too long, and I don't want to spam control c when it is booting up.

**Screenshots**

![Screenshot_20230408_193143](https://user-images.githubusercontent.com/68761233/230714339-c188d5dc-a57f-409d-adb8-7c50e2f61cc7.png)

**Comment by PJ-Singh-001** [comment]
In Cubic, when you get to the [Options page](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page), click on the [Boot tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#boot-tab) and edit the files shown.

For the `boot/grub/grub.cfg` and `boot/grub/loopback.cfg` files, create a new `menuentry` item, such as "Try Ubuntu (Custom)" with the parameter `fsck.mode=skip` added to the `linux` line. 

For the `isolinux/txt.cfg` file, create a new `label` item, such as "live-no-fsck" with the parameter `fsck.mode=skip` added to the `append` line.

(You could also modify the existing menu entries instead of creating new ones).

For example, in the file `boot/grub/grub.cfg`:

    menuentry "Try Ubuntu (Custom)" {
	    set gfxpayload=keep
	    linux	/casper/vmlinuz boot=casper fsck.mode=skip file=/cdrom/preseed/ubuntu.seed maybe-ubiquity quiet splash ---
	    initrd	/casper/initrd.lz
    }

For example, in the file `boot/grub/loopback.cfg`:

    menuentry "Try Ubuntu (Custom)" {
	    set gfxpayload=keep
	    linux	/casper/vmlinuz boot=casper fsck.mode=skip file=/cdrom/preseed/ubuntu.seed maybe-ubiquity iso-scan/filename=${iso_path} quiet splash ---
	    initrd	/casper/initrd.lz
    }

For example, in the file `isolinux/txt.cfg`:

    default live-no-fsck
    label live-no-fsck
      menu label ^Try Ubuntu (Custom)
      kernel /casper/vmlinuz
      append  boot=casper fsck.mode=skip file=/cdrom/preseed/ubuntu.seed initrd=/casper/initrd.lz quiet splash ---

Note that in the `boot/grub/grub.cfg` and `boot/grub/loopback.cfg` files, the first entry is default. In `isolinux/txt.cfg`, you specify the default entry using the directive `default <your default entry>`.

(Also, be aware that this only affects the ISO boot. If you want the same behavior for an installed system, you will need to modify grub in Cubic's [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), and you will need to take special steps in the preseed file to ensure your customized grub is not overwritten during installation.)

Here is a screenshot of Cubic's [Options page](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page), [Boot tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#boot-tab), showing a new menu entry that skips the file system check.

![Cubic Options Page Boot Tab](https://user-images.githubusercontent.com/19394936/230725545-52c17240-7313-4e54-a3c7-90351e8b9ec5.png)


  [1]: https://launchpad.net/cubic
  [2]: https://askubuntu.com/a/741770/100356
  [3]: https://i.stack.imgur.com/SRcLP.png

**Comment by ImGGAAVVIINN** [comment]
It works, but there is a "Check skipped text that appear on the screen for 2 seconds, is there a way to remove it?"

**Comment by PJ-Singh-001** [comment]
> It works, but there is a "Check skipped text that appear on the screen for 2 seconds, is there a way to remove it?"

My guess would be that you would have to find the code that calls `fsck` during boot, and change the code. If this is a binary, you will need to recompile it. You would also have to make sure your customized code is not overwritten on an update, which you could do by holding back the package containing the program or application that you chad changed.
