### ISSUE TITLE
Ubuntu 22.04 - Cannot change Plymouth theme, Kernel page list only original iso kernel

### ISSUE THREAD

**Issue by hasanmerkit** [PJ-Singh-001/Cubic#197]
![image](https://user-images.githubusercontent.com/18331715/233387144-83fe0183-e1e4-4817-a176-bade3306799f.png)

![image](https://user-images.githubusercontent.com/18331715/233386649-716f7466-266e-4a50-b2e0-c513be65feda.png)

What i missing ? :(

**Comment by PJ-Singh-001** [comment]
I recall there is an answered question on this in the closed issues section, so search there.

Let me know what you find, and if you have issues with the posted instructions.

**Comment by PJ-Singh-001** [comment]
I found it for you...
Just click on the [Closed Issues link](https://github.com/PJ-Singh-001/Cubic/issues?q=is%3Aissue+is%3Aclosed), and type "Plymouth" in the search box.
See [How to customize the Plymouth Splash Screen?](https://github.com/PJ-Singh-001/Cubic/issues/5#issuecomment-1001224949).

Since you are customizing Ubuntu 22.04, you will be able to customize the Plymouth theme for _both_ the Live ISO and for the installed system (i.e. after you have used the ISO to install the OS) using the [instructions above](https://github.com/PJ-Singh-001/Cubic/issues/5#issuecomment-1001224949).

However, starting with Ubuntu 23.04, you can only customize the Plymouth theme for the installed system using the [instructions above](https://github.com/PJ-Singh-001/Cubic/issues/5#issuecomment-1001224949). This is because you must use the kernel that came with the original ISO to _bootstrap your customized Live ISO_, otherwise your customized ISO will not boot. (Of course, if you have the skills to modify the `/boot/initrd.img` file, you can also change the Live ISO's bootsplash screen as well; I just don't know how to do it myself).

**Comment by hasanmerkit** [comment]
The problem is
```
apt update
apt --yes install --reinstall linux-headers-generic
apt --yes install --reinstall linux-image-generic
```
downloading older kernel and using internet connection.

So, downlaoding current kernel manually with `apt install reinstall`, working fine but needs internet connection.

Is there a way to do this without using internet connection? If possible, can you add a option to "Copy kernel from customized iso (including if same version)"

**Comment by PJ-Singh-001** [comment]
You really do need an Internet connection to customize an ISO, or you need all the required the `*.deb` files and _all_ required dependencies downloaded. (This of course, also requires an Internet connection).

If you want to avoid having to repeatedly download packages, you could [create a local apt mirror](https://manpages.ubuntu.com/manpages/bionic/man1/apt-mirror.1.html). Although this can help you to not need an Internet connection to get the same packages you had previously downloaded, you will need a lot of bandwidth to get the initial set of packages. 

Copying kernel files won't be feasible. Take a look at all of the dependencies for `linux-image-generic` and `linux-headers-generic`.

    apt depends linux-image-generic
    linux-image-generic
      Depends: linux-image-5.19.0-40-generic
      Depends: linux-modules-extra-5.19.0-40-generic
      Depends: linux-firmware
      Depends: intel-microcode
      Depends: amd64-microcode
      Recommends: thermald

    apt depends linux-headers-generic
    linux-headers-generic
      Depends: linux-headers-5.19.0-40-generic

Each of these dependencies will also have their own dependencies.

Thus, to make sure all required files are copied is out of the scope for Cubic.
However, you can [manually copy files into Cubic](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Copy-Page) yourself.
May be you could copy all kernel files from your host machine into Cubic? I think this is tricky, and is not something I would be able to help you with.
