### ISSUE TITLE
How to install a custom grub theme?

### ISSUE THREAD

**Issue by ImGGAAVVIINN** [PJ-Singh-001/Cubic#199]
**Describe the question**

I want to install a custom grub theme on my custom distro, but I don't know how to do it

**What you have tried**

I have tried to edit /etc/default/grub to change the grub theme but it didn't apply after I installed the distro

**Expected behaviour**

The custom grub theme should be applied when booting up after I installed the distro onto a pc

**Comment by PJ-Singh-001** [comment]
The Ubiquity installer overwrites your changes to `/etc/default/grub`.
This is why your changes are not reflected in the installed OS.

Therefore, you need to tell Ubiquity to replace the _Ubiquity-modified_ grub file with your custom grub file.

 1. Make your changes to the default grub file as you did before.

        /etc/default/grub

 2. Make the _same_ changes to this "backup" grub file, as well.

        /usr/share/grub/default/grub

 3. Instruct Ubiquity to apply the custom grub file (from `/usr/share/grub/default/grub`).

    On the [Options page](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page), [Preseed tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#preseed-tab), select the `ubuntu.seed` file, and add the following lines at the end:

    This preseed command will be executed by Ubiquity once it has finished installing your OS.

        # (a) Generate /boot/grub/grub.cfg using the customized version of /etc/default/grub.
        # (b) Revert the customized version of /etc/default/grub after it has been overwritten.
        ubiquity ubiquity/success_command string \
            in-target bash -c 'update-grub'; \
            in-target bash -c 'cp /usr/share/grub/default/grub /etc/default/grub';

(I assume the new Subiquity installer in Ubuntu 23.04 does the same thing as Ubiquity, but the above may not work for Subiquity, because Ubuntu 23.04 no longer uses preseed files).
