### ISSUE TITLE
Knoppix

### ISSUE THREAD

**Issue by NathanYinYang** [PJ-Singh-001/Cubic#203]
Can you add Knoppix support please?

**Comment by PJ-Singh-001** [comment]
What is the download link so I can look at the ISO structure?

**Comment by NathanYinYang** [comment]
knopper.net

**Comment by PJ-Singh-001** [comment]
Downloaded `KNOPPIX_V9.1DVD-2021-01-25-EN.iso` from http://mirrors.sonic.net/knoppix/knoppix-dvd/

**Comment by NathanYinYang** [comment]
Okay

**Comment by PJ-Singh-001** [comment]
I try to accommodate user requests to extend Cubic to work with other distributions.

Cubic unpacks the original ISO. It then locates and uncompresses the Squashfs file (which contains the Linux file system), and presents the user with a terminal environment where they can modify the files contained within the Squashfs file. ([See Wikipedia to learn more about Squashfs](https://en.wikipedia.org/wiki/SquashFS)).

Cubic expects the ISO's directory structure to be similar to Ubuntu/Debian. However, as long as the Squashfs file is present, I could modify Cubic to work with a different directory structure (although this in-itself would be a lot of work).

---

I checked the Knoppix ISO looking for the Squashfs file.

Here is the Knoppix ISO file structure with file sizes.

    .
    ├── [  54]  autorun.bat
    ├── [  45]  autorun.inf
    ├── [ 967]  autorun.pif
    ├── [2.0K]  boot
    │   ├── [4.0K]  isolinux
    │   └── [   8]  syslinux -> isolinux
    ├── [ 32K]  cdrom.ico
    ├── [2.0K]  efi
    │   └── [2.0K]  boot
    ├── [1.7K]  index.html
    └── [4.0K]  KNOPPIX
        ├── [577K]  background.jpg
        ├── [ 19M]  bootonly.iso
        ├── [  47]  bootonly.iso.md5
        ├── [7.7K]  index_de.html
        ├── [7.2K]  index_en.html
        ├── [8.9K]  index_es.html
        ├── [8.0K]  index_fr.html
        ├── [7.9K]  index_it.html
        ├── [643M]  KNOPPIX
        ├── [3.7G]  KNOPPIX1
        ├── [ 11K]  knoppix-cheatcodes.txt
        ├── [  25]  knoppix-data.inf
        ├── [ 31K]  knoppix-logo-medium.png
        ├── [ 15K]  knoppix-logo-small.png
        ├── [  15]  kversion
        ├── [ 18K]  LICENSE.txt
        ├── [2.0K]  modules
        ├── [ 161]  overlay-contents.txt
        ├── [3.2K]  README_Security.txt
        ├── [ 117]  sha1sums
        └── [1.2K]  SOURCES.txt

Because these are the largest files, they may be Squashfs files without the `squashfs` extension:
1. `./KNOPPIX/KNOPPIX`
2. `./KNOPPIX/KNOPPIX1`

Unfortunately, neither are Squashfs files (i.e. compressed Linux file system files).

    file ./KNOPPIX/KNOPPIX
    ./KNOPPIX/KNOPPIX: POSIX shell script executable (binary data)

    unsquashfs ./KNOPPIX/KNOPPIX
    FATAL ERROR: Can't find a valid SQUASHFS superblock on ./KNOPPIX/KNOPPIX

    file ./KNOPPIX/KNOPPIX1
    ./KNOPPIX/KNOPPIX1: POSIX shell script executable (binary data)

    unsquashfs ./KNOPPIX/KNOPPIX1
    FATAL ERROR: Can't find a valid SQUASHFS superblock on ./KNOPPIX/KNOPPIX1

In contrast, here is the output of the `file` command for a Squashfs file from the Ubuntu 22.04 Desktop ISO:

    file filesystem.squashfs
    filesystem.squashfs: Squashfs filesystem, little endian, version 4.0, zlib compressed, 2502324066 bytes, 220861 inodes, blocksize: 131072 bytes, created: Tue Apr 19 10:11:56 2022

---

Based on this research, I do not think Cubic can be adapted to work with Knoppix.

However, _I will keep this request in mind for future enhancements_. If you are aware of documentation on how the Knoppix ISO is put together and how the Linux files are compressed/stored on the ISO, please add links in this issue, and I will use the information in the future, should I be able to support Knoppix in Cubic.
