### ISSUE TITLE
Cubic removes `filesystem.manifest-remove` from the generated ISO [Elementary OS].

### ISSUE THREAD

**Issue by mirek190** [PJ-Singh-001/Cubic#213]
CUBIC is removing from iso/casper/filesystem.manifest-remove so during building image so I can not install system ...

Funny thing is older versions were not doing it .

Any idea ....

**Comment by PJ-Singh-001** [comment]
Have you accidentally turned off the off the "＋Minimal" switch in the header bar on the [Packages Page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page)?

Have you seen [Please stop creating "filesystem.manifest-minimal-remove"](https://github.com/PJ-Singh-001/Cubic/issues/143#issuecomment-1483839474)?

>   A *.manifest-minimal-remove file will always be created.
>  If Ubiquity >= 18.04 and the switch is "on", the *.manifest-minimal-remove file will be copied to the generated ISO.
>  If Ubiquity >= 18.04 and the switch is "off", the *.manifest-minimal-remove file will not be copied to the generated ISO.

Attach a screenshot of your [Packages Page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page) in Cubic, so I can see what it looks like.

I'm marking this as a Question, until we can determine this is indeed a bug in Cubic.

**Comment by mirek190** [comment]
I don't care about manifest-minimal-remove as this not present in the image .

Cubic is removing  filesystem.manifest-remove from the ready image.
Missing this file under elementary os giving error during installation ,( error logs shows missing filesystem.manifest-remove ... interrupt installation ) 

Tested older version ( 2022.06 ) which I installed manually  and that file is presented in the ready image and can easily install elementy os .


Another thing - why a new version prevent me to custom customised image from older Cubic versions?
Older version allow me to do that...for instance I have customised version where I want to add new kernel or some package but I can't now in new version as Cubic inform me I need (  "ORIGINAL" image not customised ).

Later I attach screenshots 

![Screenshot from 2023-05-17 09-04-49](https://github.com/PJ-Singh-001/Cubic/assets/6817266/17b631ac-b168-496c-875d-6131b3491d37)
![Screenshot from 2023-05-17 09-05-03](https://github.com/PJ-Singh-001/Cubic/assets/6817266/84c43ad7-d67e-45e9-bccf-bec657990625)
![Screenshot from 2023-05-17 09-06-20](https://github.com/PJ-Singh-001/Cubic/assets/6817266/443c00ce-3305-4a44-9099-3f987c65ca80)
![Screenshot from 2023-05-17 09-06-57](https://github.com/PJ-Singh-001/Cubic/assets/6817266/101becea-3344-44da-9f47-6aa91b1e55a2)
![Screenshot from 2023-05-17 09-07-20](https://github.com/PJ-Singh-001/Cubic/assets/6817266/6f18dc81-d05e-49a0-b5cf-50d01c5ac9af)
![Screenshot from 2023-05-17 09-10-28](https://github.com/PJ-Singh-001/Cubic/assets/6817266/9ad24c9a-f50f-43ba-840b-ef0590c66480)


Like you see on the pictures the "custom-disk" has filesystem.manifest-remove but built image NOT... so cannot install it as installation is broken  ...
Also I do not have "Packages Page" ..... I showed all screens what I have .... but no "Packages Page"

**Comment by PJ-Singh-001** [comment]
Why do all of your screenshots have the About dialog in front of them?
It makes it impossible to see the contents of the Cubic page.

On the  the [Prepare page](https://github.com/PJ-Singh-001/Cubic/wiki/Prepare-Page) (your second image), I would have liked to see the message under "Create the package manifest for a minimal install." Would it be possible for you to get a screenshot with the message?

**Comment by mirek190** [comment]
here you go ...
![Screenshot from 2023-05-17 20-50-03](https://github.com/PJ-Singh-001/Cubic/assets/6817266/981cb0b7-c85f-43a0-8657-6248d59938d4)

after this screen I have kernel select page.


But why a newer version of Cubic is removing filesystem.manifest-remove  ...

**Comment by PJ-Singh-001** [comment]
Ok, thanks.
I’ll look into this and get back to you.

**Comment by mirek190** [comment]
thank you

**Comment by PJ-Singh-001** [comment]
Cubic checks for the package `ubiquity` to determine if the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page) should be displayed.

The [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page) allows you to configure the contents of the following files, which are used by Ubiquity during installation:

- `filesystem.manifest-remove`
- `filesystem.manifest-minimal-remove`

However, Elementary OS began using a forked version of Ubiquity.
The forked installer package is `io.elementary.installer`.
(This change may have happened with Elementary OS 5.0 Juno, but I am not sure).

Because Cubic does not find the `ubiquity` package while customizing Elementary OS, it does not show the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page). Furthermore, the fix released for [Please stop creating "filesystem.manifest-minimal-remove"](https://github.com/PJ-Singh-001/Cubic/issues/143#issuecomment-1483839474) in version 2023.03.76 stopped copying the "manifest-remove" files to the new ISO whenever the `ubiquity` package was missing. This is why you experienced this issue with the newer versions of Cubic.

The solution will be to check the following in order to show the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page). Cubic should then generate the new ISO with the `filesystem.manifest-remove` file (and the `filesystem.manifest-minimal-remove` file, as needed).

- The existence of `filesystem.manifest-remove`, or
- The existence of `filesystem.manifest-minimal-remove`, or
- The existence of `ubiquity`, or
- The existence of `io.elementary.installer`

**Comment by PJ-Singh-001** [comment]
Fix released in version 2023.05-83.

Cubic no longer checks for Ubiquity to determine if the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page) should be shown.

Here is the updated logic:

**Standard install (`filesystem.manifest-remove` file):**
- If the original ISO has the `filesystem.manifest-remove` file, the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page) will be shown. This no longer depends on Ubiquity being installed. Therefore, this will work for all installers (such as `ubiquity`, `pop-installer`, `io.elementary.installer`, etc.) that use the `filesystem.manifest-remove` file.
- The customized `filesystem.manifest-remove` file is always created.
- The Standard packages column is always shown.
- If the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page) is shown, the customized `filesystem.manifest-remove` file will be copied to the generated ISO.
- If the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page) is not shown, the customized `filesystem.manifest-remove` file will not be copied to the generated ISO.

**Minimal install (`filesystem.manifest-minimal-remove` file):**
- The "＋Minimal" switch is always shown on the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page). This no longer depends on the version of Ubiquity installed. Therefore, this will work for all installers (such as `ubiquity`, `pop-installer`, `io.elementary.installer`, etc.).
- The customized `filesystem.manifest-minimal-remove` file is always created.
- If the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page) is not shown, the customized `filesystem.manifest-minimal-remove` file will not be copied to the generated ISO.
- When the "＋Minimal" switch is "on", the Minimal packages column will be shown.
- When the "＋Minimal" switch is "off", the Minimal packages column will not be shown.
- The "＋Minimal" switch will be "on" by default, if the original ISO has the `filesystem.manifest-minimal-remove` file.
- The "＋Minimal" switch will be "off" by default, if the original ISO does not have the `filesystem.manifest-minimal-remove` file.
- The user can toggle "＋Minimal" switch, regardless of the installer version.
- If the "＋Minimal" switch is "on", the `filesystem.manifest-minimal-remove` file will be copied to the generated ISO.
- If the "＋Minimal" switch is "off", the `filesystem.manifest-minimal-remove` file will not be copied to the generated ISO.

_Note, if you are customizing an existing Cubic project created using a version of Cubic prior to version 2023.05-83, the "＋Minimal" switch will be "on" by default, and you should manually toggle it to the "off" position, if you do not want the `filesystem.manifest-minimal-remove` file to be copied to the generated ISO. You only have to do this once, because your selection will be saved for the next time you edit your project._
