### ISSUE TITLE
How to add cron tasks on Ubuntu Server 21.04+ ?

### ISSUE THREAD

**Issue by Luke-Jaeger** [PJ-Singh-001/Cubic#216]
**I'm trying to auto-install an image with a working crontab that runs as root on reboot**

in other words, a workflow like this:
- auto-install custom Ubuntu image
- after install, boot from internal drive & run setup script

I can create a root crontab file in the virtual environment:
`echo "@reboot   /path/to/setup.sh" > /var/spool/cron/crontabs/root`
But after I burn the .iso, run the auto-install, etc, there's no root crontab file on the installed instance.

I want the cron task to already be there when the machine boots for the first time, without having to log in and do `crontab -e`

**OS Information (please complete the following information):**
 - OS/Distro Name: Ubuntu Desktop
 - OS Version 22.04

**Cubic Information (please complete the following information):**
 - Cubic Version: [2023.04.81]
 - ISO Customizing: [ubuntu server 22.04]
 - Download Link:  [Ubu server 22.04
](https://releases.ubuntu.com/22.04.2/ubuntu-22.04.2-live-server-amd64.iso)

**Comment by PJ-Singh-001** [comment]
Does the entire directory path exist in Cubic?

    /var/spool/cron/crontabs/

**Comment by Luke-Jaeger** [comment]
> Does the entire directory path exist in Cubic?
> 
> ```
> /var/spool/cron/crontabs/
> ```

Yes! I created that path in the virtual environment, and it's reproduced on the installed machine. But the actual root crontab file doesn't get installed, just the empty directory path.

**Comment by PJ-Singh-001** [comment]
Does Ubuntu Server have a Standard and Minimal install option?

If so, which did you use?

Currently, Cubic can only customize the Minimal "version".
If you selected the Standard install, it may have overridden your customizations to the Minimal "version" done in Cubic.

**Comment by Luke-Jaeger** [comment]
All the other customizations have been working, it's just this one I can't figure out!
I only see the Standard / Minimal options when trying to install the Desktop version.

**Comment by Luke-Jaeger** [comment]
adding the task to /etc/crontab didn't work either.

**Comment by PJ-Singh-001** [comment]
> adding the task to /etc/crontab didn't work either.

The file is simply missing after you install the customized OS?

Is the file present in the Live Environment?

(In Ubuntu Server, you can enter the Live Environment by selecting "Enter Shell" from the "Help" menu item at the top right).

**Comment by Luke-Jaeger** [comment]
/etc/crontab is present after the install but it's the default file. It must be getting overwritten somehow.
I tried running the postinstall script as a runcmd in the user-data file and that seemed to work! So maybe I don't need to worry about cron jobs.
In some future version of Cubic it would be amazing to have a tool for setting up post-boot tasks.
It would also be great if there were a way to use nano or other text editors in the Cubic terminal.

**Comment by PJ-Singh-001** [comment]
I think I see what is going on. I'm looking at it now, and I'll get back to you.

**Comment by PJ-Singh-001** [comment]
Here is a solution that I think will solve your immediate problem. The workaround is to place your crontab file in the `/etc/cron.d` directory.

Execute the following in Cubic...

I like to use `nano` to edit text files, but you can also drag-n-drop files onto the Cubic window.

    apt install nano

Create a script to execute. Place the script in the `opt` directory.

    nano /opt/test.sh

Add the following lines. This just creates test files with unique names. The files are also placed in the `/opt` directory for this test. We can verify that the script is being executed by cron by examining the contents of the `/opt` directory.

    #!/bin/bash
    # /opt/test.sh

    file_name=$(date)
    file_name="${file_name// /_}"
    file_name="${file_name//:/_}"
    echo "Creating file /opt/$file_name.txt"
    touch "/opt/$file_name.txt"
    echo "Done."
    echo

Make sure your script is executable.

    chmod +x /opt/test.sh
    ls -la /opt/test.sh

    -rwxr-xr-x 1 root root 194 May 23 15:06 /opt/test.sh

Create your crontab file. Place this file in the `/etc/cron.d` directory. This directory is available in the ISO's Live Environment. This directory is also available on an installed system.

    nano /etc/cron.d/test

Add the following to the crontab file.

    * * * * * root /opt/test.sh

Make sure your crontab file has the correct permissions.

    ls -la /etc/cron.d

    total 8
    drwxr-xr-x  2 root root   80 May 23 15:11 .
    drwxr-xr-x 74 root root 2740 May 23 14:54 ..
    -rw-r--r--  1 root root  201 Jan  8  2022 e2scrub_all
    -rw-r--r--  1 root root   23 May 23 15:11 test

During installation, on the "Type of Server" page, you have the choice of installing:
 1. "Ubuntu Server"
 2. "Ubuntu Server (minimized)"

If you chose the first option, the `cron` package will automatically be included. However, if you chose the second option, the `cron` package is not automatically included. Therefore, you should install the `cron` package.

    apt install cron

Here are the test results in the Live Environment. In Ubuntu Server, you can enter the Live Environment by selecting "Enter Shell" from the "Help" menu item at the top right.

![image](https://github.com/PJ-Singh-001/Cubic/assets/19394936/75d7fd14-8971-456e-93ac-5099bb3235a2)

---

Next steps:

1. I will install the customized OS in a virtual environment to ensure the solution also works on an installed system.
3. I will give you an explanation as to why you are experiencing this issue.
4. I will see if I can offer a solution to make your `/etc/crontab` file work.

**Comment by PJ-Singh-001** [comment]
Here is the explanation...

The Ubuntu Server ISO has two layers (conceptually):

- Ubuntu Standard Layer
- Ubuntu Minimal Layer

![Ubuntu Servr ISO Diagram 2023-05-23-01-PS](https://github.com/PJ-Singh-001/Cubic/assets/19394936/9e184625-d0e4-4e48-bb46-ac92ab33fc35)

The Ubuntu Standard Layer overrides your changes in Cubic, because Cubic allows you to customize the Minimal Layer, not the Standard Layer.

You will _not_ be able to see your customizations in the Live Environment (accessed by selecting "Enter Shell" from the "Help" menu item at the top right) because the Live Environment shows the Standard Layer.

However, you can ensure your customizations are reflected in the installed OS by selecting "Ubuntu Server (minimized)" during installation.

![Ubuntu Server Installer 2023-05-23-01-PS](https://github.com/PJ-Singh-001/Cubic/assets/19394936/1583e916-0db5-479a-bd7b-1182317f842a)

**Comment by Luke-Jaeger** [comment]
THANK YOU for this super detailed explanation!

Luke Jaeger | Technical Project Administrator
____________

Computer Science Department <https://www.mtholyoke.edu/directory/departments-offices-centers/computer-science> / Fimbel Maker & Innovation Lab <https://www.mtholyoke.edu/academics/centers-and-facilities/fimbel-maker-innovation-lab>
Mount Holyoke College
____________

Book me on Pathways <https://mountholyoke.starfishsolutions.com/starfish-ops/dl/instructor/serviceCatalog.html?bookmark=connection/297945/schedule>

**Comment by PJ-Singh-001** [comment]
Here is the solution using the `/etc/crontab` file.

 1. Install the `cron` package, because it is not available in the (Minimal) file system you are customizing in Cubic.

        apt install cron

 2. I like to use `nano` to edit text files, but you can also drag-n-drop files onto the Cubic window.

        apt install nano

 3. Create a script to execute. Place the script in the `opt` directory.

        nano /opt/test.sh

 4. Add the following lines. This just creates test files with unique names. The files are also placed in the `/opt` directory for this test. We can verify that the script is being executed by cron by examining the contents of the `/opt` directory.

        #!/bin/bash
        # /opt/test.sh

        file_name=$(date)
        file_name="${file_name// /_}"
        file_name="${file_name//:/_}"
        echo "Creating file /opt/$file_name.txt"
        touch "/opt/$file_name.txt"
        echo "Done."
        echo

 5. Make sure your script is executable.

        chmod +x /opt/test.sh
        ls -la /opt/test.sh

        -rwxr-xr-x 1 root root 194 May 23 15:06 /opt/test.sh

 6. Edit `/etc/crontab`.

        nano /etc/crontab

 7. Add your cron task to `/etc/crontab`.

    This will execute the test script every minute.

        * * * * * root /opt/test.sh

    The file will look like this:

        # /etc/crontab: system-wide crontab
        # Unlike any other crontab you don't have to run the `crontab'
        # command to install the new version when you edit this file
        # and files in /etc/cron.d. These files also have username fields,
        # that none of the other crontabs do.

        SHELL=/bin/sh
        # You can also override PATH, but by default, newer versions inherit it from the environment
        #PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

        # Example of job definition:
        # .---------------- minute (0 - 59)
        # |  .------------- hour (0 - 23)
        # |  |  .---------- day of month (1 - 31)
        # |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
        # |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
        # |  |  |  |  |
        # *  *  *  *  * user-name command to be executed
        17 *    * * *   root    cd / && run-parts --report /etc/cron.hourly
        25 6    * * *   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
        47 6    * * 7   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.weekly )
        52 6    1 * *   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.monthly )
        #
        * * * * * root /opt/test.sh

 9. Finally, generate the ISO in Cubic and install the customized OS.

10. During installation, on the "Type of Server" page, you have the choice of installing:

     1. "Ubuntu Server"
     2. "Ubuntu Server (minimized)"

    You **must** chose the second option "**Ubuntu Server (minimized)**" during installation.

12. Here are the test results in an installed system.

![Screenshot from 2023-05-23 21-50-48](https://github.com/PJ-Singh-001/Cubic/assets/19394936/1cbc1820-3001-436f-a6d9-ceec379d697b)

**Comment by PJ-Singh-001** [comment]
Note:

Instead of only installing the `cron` package in [step 1 above](https://github.com/PJ-Singh-001/Cubic/issues/216#issuecomment-1560358762), you can execute `unminimize` inside Cubic.

This will install missing packages like `cron` for you.

    You have entered the virtual environment.
    root@cubic:~# unminimize
    This system has been minimized by removing packages and content that are
    not required on a system that users do not log into.

    This script restores content and packages that are found on a default
    Ubuntu server system in order to make this system more suitable for
    interactive use.

    Reinstallation of packages may fail due to changes to the system
    configuration, the presence of third-party packages, or for other
    reasons.

    This operation may take some time.

    Would you like to continue? [y/N]

**Comment by Luke-Jaeger** [comment]
thank you again!
I tried again using your **unminimize** method, but the installer crashed during **subiquity postinstall run_unattended_upgrades.**
I can force a reboot and log in, but /etc/crontab is back to its default state.
Also, the installer never asked me whether I wanted **server** or **server minimized**.

![2023-05-24 15 28 17](https://github.com/PJ-Singh-001/Cubic/assets/59834553/80a3f743-ad5b-45a5-be57-9e3fb5cb73d8)

**Comment by PJ-Singh-001** [comment]
Are you using autoinstall, per [your previous question](https://github.com/PJ-Singh-001/Cubic/issues/210)?

If so, the problem is you do not have an opportunity to select "Ubuntu Server (minimized)". Autoinstall always picks the "Standard" install, and the "Standard" install always overrides `/etc/crontab`.

You can try to install manually, using the [2nd solution (with `/etc/crontab/`)](https://github.com/PJ-Singh-001/Cubic/issues/216#issuecomment-1560358762), and make sure you pick "Ubuntu Server (minimized)", just to validate that the solution works.

If you have to use autoinstall, I think [the 1st solution (using `/etc/cron.d` instead of `/etc/crontab`)](https://github.com/PJ-Singh-001/Cubic/issues/216#issuecomment-1560031580) should work for you. I have noticed that the contents of `/etc/cron.d` does not get overridden with the "Standard" install. If you use the [the 1st solution (using `/etc/cron.d` instead of `/etc/crontab`)](https://github.com/PJ-Singh-001/Cubic/issues/216#issuecomment-1560031580), you do not need to [run `unminimize`](https://github.com/PJ-Singh-001/Cubic/issues/216#issuecomment-1560370854), because the "Standard version is _already_ unminimized.

**Comment by Luke-Jaeger** [comment]
you were right, the file in /etc/cron.d survived the installation!
this is great!
the point here is to create a completely hands-free system to install & customize Ubuntu Desktop on several dozen laptops later in the summer (when I won't have time to experiment).
thanks for this excellent software & support!

**Comment by PJ-Singh-001** [comment]
Great!

In summary, there are conceptually two "Layers" on the Ubuntu Server ISO:
1. Ubuntu Standard Layer
2. Ubuntu Minimal Layer

**Cubic modifies the "Minimal Layer".**
**During installation the user should select the "Minimal" install.**
Otherwise the "Standard Layer" will override the files from the "Minimal Layer", and some customization will be lost.
If you must do a "Standard" install, then it is important to figure out which files are and are-not overridden and make customizations accordingly.
