### ISSUE TITLE
Debian 12: cubic unable to locate the compressed linux file system

### ISSUE THREAD

**Issue by alexiarstein** [PJ-Singh-001/Cubic#218]
**cubic unable to locate the compressed linux file system**

This is the error message experienced when trying to use the debian 12 iso (AMD64)

**To Reproduce**

Launch the program, try to load Debian 12 bookworm iso

**Expected behavior**

This error won't let you proceed

**OS Information (please complete the following information):**
- Host OS: Debian 12 bookworm, vmware player, dual xeon gold, 16gb ram, 4 cores

**Cubic Information (please complete the following information):**
 - Cubic Version: latest 
 - ISO Customizing: firmware-bookworm-DI-alpha1-amd64-DVD-1.iso
 - Download Link:  [The download link for the ISO you are customizing](https://cdimage.debian.org/cdimage/bookworm_di_alpha2/amd64/iso-dvd/debian-bookworm-DI-alpha2-amd64-DVD-1.iso)

**Cubic Log:**

 Cut and paste the log after running `cubic --verbose` from the command line

**Screenshots**

**Comment by PJ-Singh-001** [comment]
@alexiarstein,

The ISO you are trying to customize does not have a Live Environment.
I guess that because Debian 12 is still in alpha, they haven't created an ISO with a Live Environment yet.

Here is what the Debian 12 ISO looks like when you boot it up...
![Debian 12 ISO 2023-05-30](https://github.com/PJ-Singh-001/Cubic/assets/19394936/eea88e52-e6d5-4366-8318-7b53f365c297)

In contrast, here is what an ISO with a Live Environment looks like (from Debian 11)...
![Debian 11 ISO 2023-05-30](https://github.com/PJ-Singh-001/Cubic/assets/19394936/1160f1a1-2eff-493f-ae2a-c6f90abd93f2)
