### ISSUE TITLE
How to customize which icons are shown in the Dock?

### ISSUE THREAD

**Issue by tcboeira** [PJ-Singh-001/Cubic#23]
I would like when generating my custom ISO through Cubic, that I could change icons/shortcuts that are in the Dock.
Both for Live mode and standard post installation.

For example:
I would like to remove Firefox and leave Chrome.
I would like to remove Thunderbird and add Terminal.

Tried - via Terminal Cubic - to use gsetting and dconf to no avail.
As an alternative, I set up a script to run when a user is logged in, putting it in /etc/skel/user/.config/autostart and with no success

Using Ubuntu 20.04

**Comment by PJ-Singh-001** [comment]
You can not directly set the values using `gsettings` because the user you are changing the settings for does not exist yet. 

Instead, use a gschema override file.

 1. On Cubic's [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), change directory to the `schemas` directory.

        cd /usr/share/glib-2.0/schemas

 2. Create a new gschema file named `90_ubuntu-settings.gschema.override`.

        nano 90_ubuntu-settings.gschema.override

 3. Enter the following information (for example) for the `gsettings` path, key, and value.

        [org.gnome.shell]

        favorite-apps = ['ubiquity.desktop', 'google-chrome.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.gedit.desktop', 'org.gnome.Terminal.desktop', 'org.gnome.Calculator.desktop', 'org.gnome.Screenshot.desktop', 'gnome-system-monitor.desktop']
 
    - You can use the right-click context menu or keyboard shortcuts (<kbd>Shift</kbd>+<kbd>Ctrl</kbd>+<kbd>C</kbd> or <kbd>Shift</kbd>+<kbd>Ctrl</kbd>+<kbd>V</kbd>) to cut and paste text in the terminal.

    - Modify the `favorite-apps` list to contain the applications you want in your dock, in the order you want them displayed.

    - Be sue to use the correct launcher filename for your applications. The launchers are found in `/usr/share/applications`.
    - You can leave `'ubiquity.desktop'` in the list, if you want Ubiquity to be listed in the dock in the Live environment.

 4. To exit nano, type <kbd>Ctrl</kbd>+<kbd>X</kbd> and you will be prompted to save the file.

    Type <kbd>Y</kbd> to save the file (or <kbd>N</kbd> to cancel saving the file). Press <kbd>Enter</kbd> to accept the default file name.

 5. Compile the gschemas.

        glib-compile-schemas /usr/share/glib-2.0/schemas

**Comment by tcboeira** [comment]
It's perfect!!! Thank you very, very much!!!

I apologize for any mistakes... I don't understand much - nothing honestly - about another language, and I always end up using an online translator...

But thank you very, very much!!!

Now I'm going to find out how to close...
;-)
