### ISSUE TITLE
how to update subiquity in cubic virtual terminal for installation ubuntu 22.04 server ?

### ISSUE THREAD

**Issue by gitgonewithwind** [PJ-Singh-001/Cubic#232]
Hi @PJ-Singh-001 
can I update  subiquity in cubic virtual terminal?
I posted a question here:
https://github.com/PJ-Singh-001/Cubic/issues/229
it seems not work for below user-data
storage:
layout:
name: lvm
password: test

I find here: https://github.com/canonical/subiquity/pull/1579
it seems I need to use
https://github.com/canonical/subiquity/pull/1588

  storage:
    layout:
      name: lvm_use_all_space
      password: TEMPORARY

but I think my ubuntu 22.04 server subiquity is older. can not support it
how can I do ?
Can I update subiquity in cubic virtual terminal? if possible , how to do?

**Comment by PJ-Singh-001** [comment]
Unfortunately, you will not be able to update Subiquity using Cubic.

In the past, when Canonical used Ubiquity, the OS was in a "single layer." During installation, Ubiquity copied everything from this "single layer" onto the computer's disk. After installation, Ubiquity would automatically remove software not needed on an installed system. To make this more clear, the Ubuntu installer would _actually copy Ubiquity onto your disk_, and _then remove itself_ just before completing the installation.

The newer ISOs from Canonical that use Subiquity have multiple layers. During installation, the installer only installs certain layers (either the Minimal layer, or the Minimal layer + the Standard layer). The Subiquity installer is on a completely different layer, which _never_ gets copied onto your disk. Therefore, there is no longer a need to remove the Subiquity installer, after installation is complete. This is obviously more efficient, but it gives us less control when customizing an ISO.

Cubic does not allow you to customize the "Standard" layer or the "Installer" layer. Even if you could edit the "Installer" layer (that contains the Subiquity installer) you would be disappointed to learn that it is a Snap package. There is currently no way (that I am aware of) to update Snap packages in a container environment, like the one Cubic uses.

Note that you can download a "Legacy" installer ISO for the Ubuntu 23.04 _Desktop_ that uses the Ubiquity `*.deb` package. This gives you a lot of control when customizing the ISO, but I am not aware of a similar ISO for Ubuntu Server. (See Issue #208, [Tips for customizing the Ubuntu 23.04 Lunar Lobster Desktop ISO](https://github.com/PJ-Singh-001/Cubic/issues/208)).

I have not come up with a workable approach (yet) for these two issues:
 1. Multiple "layers" on the ISO
 2. Updating Snap packages

Here is a conceptual view of the layers from Issue #216 ([How to add cron tasks on Ubuntu Server 21.04+ ?](https://github.com/PJ-Singh-001/Cubic/issues/216#issuecomment-1560288812)) and Issue #225 ([Installed packages via Cubic are not registered in final installed OS - Ubuntu 22.04](https://github.com/PJ-Singh-001/Cubic/issues/225#issuecomment-1573939832)).

(Note there are more layers on the ISO than are depicted in this conceptual diagram, such as the "Installer Layer" that contains Subiquity, which I mentioned above but is not shown below).

<img src="https://user-images.githubusercontent.com/19394936/240445460-9e184625-d0e4-4e48-bb46-ac92ab33fc35.png"/>

**Comment by PJ-Singh-001** [comment]
@gitgonewithwind,

Here is something you could try. I have not tested it myself, so I have no idea if it will work...

Since you are customizing Ubuntu Server 22.04, and you want (I assume) the newer Subiquity from Ununtu Server 23.04, you could try the following:

 1. Download the Ubuntu 23.04 Server ISO (`ubuntu-23.04-live-server-amd64.iso`) and keep it handy for step 4, below. 
 2. Create a Cubic project to customize Ubuntu Server 22.04 ISO.
 3. Once you get to the [Options page](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page) in Cubic, do the following **outside** Cubic.
 4. Mount the `ubuntu-23.04-live-server-amd64.iso` ISO from step 1.
 5. Copy `<mount point>/Ubuntu-Server 23.04 LTS amd64/casper/ubuntu-server-minimal.ubuntu-server.installer.squashfs` to `<your Cubic project>/custom-disk/casper`. (This will contain the Subiquity installer from Ubuntu Server 23.04).
 6. Unmount the `ubuntu-23.04-live-server-amd64.iso` ISO from step 4.
 7. Finish customizing your ISO.
 8. Test the updated Subiquity installer.
 
If this does not work, you can undo this change by copying the original `ubuntu-server-minimal.ubuntu-server.installer.squashfs` file from the `ubuntu-22.04.2-live-server-amd64.iso` file.

**Comment by gitgonewithwind** [comment]
@PJ-Singh-001 
Thank you so much. I will try your solution first.
or
another harder option ,I can directly update to my project to Ubuntu Server 23.04 (or test before your solution). if that, Maybe I need to ask my colleagues' to update their code.

**Comment by gitgonewithwind** [comment]
Hi
@PJ-Singh-001 
NOT work.
I tired:
1. I directly used Cubic  for ubuntu sever 23.04  and completely use your guide here: https://github.com/PJ-Singh-001/Cubic/issues/101#issuecomment-1336728758 . NOT work at all. error:failed to start service for snap application lxd.activate. .... waiting untill snapd is fully seeded . or used my simple user-data that worked well in 22.04 , same Not work. see error picture 
![IMG_20230614_122909](https://github.com/PJ-Singh-001/Cubic/assets/53866161/4a975c78-866c-4058-9492-bc0dcfefc1fa)

2. use your solution posted this page to replace ubuntu-server-minimal.ubuntu-server.installer.squashfs in ubntu 22.04.
Not work either. see error picture:
![IMG_20230614_111148](https://github.com/PJ-Singh-001/Cubic/assets/53866161/3611fd19-5100-414b-8f87-a139ac9ce956)
