### ISSUE TITLE
Cubic Live ISO's and Modifications - Tutorials of Use (wiki reviewed already) - Fit for purpose?

### ISSUE THREAD

**Issue by cblknittights** [PJ-Singh-001/Cubic#249]
**Describe the question**

Looking to get 
1) Tutorials on the use of Cubic - I reviewed the "wiki" here, but its just screen shots, with out much detail on use.

2) Determine if Cubic can do what I want:

Modify Live ISO's to create NEW LIVE ISO's with the changes I make that can be tested and reviewed like a normal LIVE ISO and then installed via the install icon on the LIVE ISO or via the INSTALL OPTION of the live ISO ie: the Try xbuntu or Install xbuntu that would come up when booting the live iso

**What you have tried**

Reviewed wiki, just screen shots and not tutorials on use. Appears a very large prior knowledge base is required to use Cubic 
.
Reviewed many issues here (Don't see the "discussion" tab to use or a ML or a forum? to discuss use, operations etc.. 

Reviewed several sites at : 
https://itsfoss.com/create-custom-linux-mint-iso/
https://www.makeuseof.com/create-custom-ubuntu-iso-cubic/

These seem to point to what I am after to do, modify the LIVE ISO to my purpose... but then I see: 

this image

![](https://user-images.githubusercontent.com/19394936/240445460-9e184625-d0e4-4e48-bb46-ac92ab33fc35.png)

This appears to state that Cubic does NOT MODIFY THE LIVE ENVIRONMENT and CAN NOT MODIFY IT to achieve my goals and purpose. Correct??????? 

**Expected behavior**

Looking to AVOID the MESS OF THIS:
https://help.ubuntu.com/community/LiveCDCustomization

Which is a recipe for disaster, and there is no way that Canocial etc. are doing all that to create ISO's. So Cubic is the tool to replace the unreleased ISO creation tools that Canocial has???? 

Modify the Ubuntu and Debian ISO to have the software packages I want removed,  and add the software I want added to be setup for the user from the LIVE mode or the Installer mode. 

Simple for IDIOTS aka no ISO Gurus aka me! :) to use to remaster of *buntu/Debian ISO's to remove their garbage ie: snapd, and install software needed from basic net-tools package to other stuff which must be compiled, etc.. 

Examples:

REMOVE snapd and all snap based software

INSTALL NON snap based items ie: firefox

CHANGE the apt config to BLOCK snapd from being installable

setup the Mozilla Repo to provide firefox

install a program(s)  I want included

UPDATE ALL THE PACKAGES Of the ISO to the current versions from the repos at the time of creation of the new ISO. 

COMPILE???? PROGRAMS to be available in the LIVE ISO and installed from the Live ISO

**OS Information (please complete the following information):**
Looking to use:
Kubuntu 22.04 and 23.10 DAILY BUILDS
Debian 12 Bookworm
Ubuntu Server 22.04 and 23.10 DAILY BUILDS

**Cubic Information (please complete the following information):**

Use the latest from the Cubic Repo.

Comments ? Thank you in advance.

**Comment by PJ-Singh-001** [comment]
If you want to customize Ubuntu Server 20.10 (and lower) or Ubuntu Desktop 22.10 (and lower) you will have no issues using Cubic and seeing your customizations in the Live Environment.

---

The diagram above applies to:
- Ubuntu Server 21.04 (and above)
- Ubuntu Desktop 23.04 (and above)

For these ISOs, the key take-aways for these versions are:
1. Select Minimal install during installation
2. Unfortunately, you will not be able to see your customizations in a the Live Environment

Note, even if you try to manually customize any of these newer  ISOs (by following https://help.ubuntu.com/community/LiveCDCustomization, for example), you will run into the same issues as Cubic faces, because Canonical changed how the ISO works.

---

However, I do have good news for you regarding Kubuntu 23.04. Kubuntu 23.04 uses the old ISO structure, so you will be able to customize it using Cubic (and see your customizations in the Live Environment).

Also, there is good news regarding Debian Bookwom. You will be able to customize it using Cubic (and see your customizations in the Live Environment). See: https://github.com/PJ-Singh-001/Cubic/issues/ and https://github.com/PJ-Singh-001/Cubic/issues/187.

---

Regarding instructions, look for closed issues that start with "How to...". Those may help you. Since there are an infinite amount of customizations users may do, it would be impossible to create detailed instructions, especially for all of the distributions Cubic supports.

**Comment by PJ-Singh-001** [comment]
**Here are instructions to customize Ubuntu:**

Issue #22, [How to customize the wallpaper, icon theme, desktop theme, and Plymouth boot splash theme (in English & Japanese)?](https://github.com/PJ-Singh-001/Cubic/issues/22#issuecomment-1032011784)

**Here are instructions to customize Linux Mint:**

Issue #252 [How to customize Linux Mint Cinnamon wallpaper, icons, and theme?](https://github.com/PJ-Singh-001/Cubic/issues/252).
