### ISSUE TITLE
screen blank when booting customized os

### ISSUE THREAD

**Issue by Daggermaster** [PJ-Singh-001/Cubic#250]
I'm just finished generating the customized os but when I'm trying to boot it on the VM, the screen turns into a blank screen after the splash screen showed up. I could see the mouse pointer. before generating the customized os im doing update the kernel 

**OS Information (please complete the following information):**
 - OS: ubuntu 22.04
 - I'm using the latest version of cubic
 - kernel 6.2.0.26
 - VirtualBox 6.1

**Comment by PJ-Singh-001** [comment]
On the [Options Page](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page), on the [Kernel Tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#Kernel-Tab), select the original bootstrap kernel (not the new kernel you installed).

Selecting the original bootstrap kernel will allow your ISO to boot, but you will *not* see your new kernel while running the ISO's Live Environment.

However, once you have installed your customized OS to a computer or virtual machine, your new kernel will be installed/used.

(Note: Because Cubic always defaults to the new kernel for bootstrapping the ISO, you will need to make sure you select the original bootstrap kernel on the [Kernel Tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#Kernel-Tab) each time you regenerate your ISO).

**Comment by Daggermaster** [comment]
im already fix that problem, thanks.
