### ISSUE TITLE
cubic won't install with systemd 249.11-0ubuntu3.11 , asks for 249.11-0ubuntu3.7

### ISSUE THREAD

**Issue by alanlupsha** [PJ-Singh-001/Cubic#287]
**Describe the bug**

Can't install the latest cubic due to systemd error, see the reproduce step below.

**To Reproduce**

My systemd version is 249.11-0ubuntu**3.11**

```
./systemd --version
systemd 249 (249.11-0ubuntu3.11)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
```

Installing cubic says it needs 249.11-0ubuntu**3.7**

```
apt-add-repository universe
sudo apt-add-repository ppa:cubic-wizard/release
sudo apt update
sudo apt install --no-install-recommends cubic
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 **systemd-container : Depends: systemd (= 249.11-0ubuntu3.7) but 249.11-0ubuntu3.11 is to be installed**
E: Unable to correct problems, you have held broken packages.
```

**Expected behavior**

Cubic should probably install without this error.

```
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```

**Cubic Information (please complete the following information):**
None yet because it doesn't install.

**Cubic Log:**

N/A

**Screenshots**

![image](https://github.com/PJ-Singh-001/Cubic/assets/41340720/5c7da49a-1559-422c-b4a0-f57bc4c2bbdf)

![image](https://github.com/PJ-Singh-001/Cubic/assets/41340720/cded9a4c-1b29-49d1-98d8-2e667801ecce)

**Comment by PJ-Singh-001** [comment]
You did not share which version of Ubuntu you are using. I will guess it is Jammy 22.04 LTS, based on your version of `systemd`.

Cubic can be installed in Ubuntu 18.04.5 Bionic Beaver and above.
Cubic depends on `systemd-container` version 237 or higher.
However, the package `systemd-container` depends on `systemd`.
(Note that on a working system, the version number for `systemd-container` and `systemd` are usually the same).

On your system, `systemd-container`  requires `systemd` version 249.11-0ubuntu**3.7**, because it will not work with any other version of `systemd`. This implies that you have `systemd-container`  version 249.11-0ubuntu**3.7** installed.

According to your error message, `systemd` version 249.11-0ubuntu**3.11** will be installed, not version 249.11-0ubuntu**3.7** (which is the version `systemd-container`  requires):

    The following packages have unmet dependencies:
     **systemd-container : Depends: systemd (= 249.11-0ubuntu3.7) but 249.11-0ubuntu3.11 is to be installed**
    E: Unable to correct problems, you have held broken packages.

So the issue you have is an incompatibility between `systemd-container` and `systemd`.

Instead of attempting to install Cubic, try to fix this issue 1st.

    sudo apt update
    sudo apt install systemd-container

You will note that you get the same error as you have posted above.

Do you have any held-back packages?

    apt-mark showhold

See if you have any other package dependencies that may prevent `systemd-container` and `systemd` from updating.

**Comment by alanlupsha** [comment]
Thank you for the suggestions.

no luck with ```apt-install systemd-container```:

![image](https://github.com/PJ-Singh-001/Cubic/assets/41340720/7c39ee48-c50b-4833-9137-24dd9e0b0429)

Also, there is nothing being held back:

![image](https://github.com/PJ-Singh-001/Cubic/assets/41340720/5d48e735-cfc3-49ea-aabf-c361691c14b3)

It looks like I have systemd, but I do NOT have systemd-container:

![image](https://github.com/PJ-Singh-001/Cubic/assets/41340720/ef813b53-ae0f-4058-9d80-7acc128065fd)

systemd is version 249.11-0ubuntu**3.11**

and trying to install systemd-container is no go, due to this error:

![image](https://github.com/PJ-Singh-001/Cubic/assets/41340720/b3b815cb-e147-4cdd-9b21-d61cd95f46c7)

Also: nothing weird going on with this system, it's a pretty new install. Thanks!

**Comment by alanlupsha** [comment]
I gave up, and installed
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
```
which is a more stable release than Ubuntu 22.04.3 LTS, and there are no issues.

Keep in mind that newer versions can cause issues.

Thanks for all the help, take care, please close this, lgtm.

**Comment by alanlupsha** [comment]
Closing.
