### ISSUE TITLE
Can not boot the LMDE 6 modified iso

### ISSUE THREAD

**Issue by Plasmoid77** [PJ-Singh-001/Cubic#290]
![image](https://github.com/PJ-Singh-001/Cubic/assets/114841879/3eafd75e-8d78-4a4c-83d9-5c99ccd1468e)
I tried to use Cubic to modify LMDE 6, iso was made succesfully. But I'm not able to boot, it gets stuck at this moment

**Comment by Plasmoid77** [comment]
Green background of Mint's logo should be spinning, but it does not, so there must be something wrong. Btw, Cubic also doesn't snow the menu with the list of packages, that could be deleted, after virtual terminal. Like here: https://github.com/PJ-Singh-001/Cubic/issues/274#issuecomment-1841896244

**Comment by PJ-Singh-001** [comment]
What installer does your Mint ISO use?

Per the [Cubic Wiki](https://github.com/PJ-Singh-001/Cubic/wiki), the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page)...
> is only shown if [Ubiquity](https://packages.ubuntu.com/bionic/ubiquity) is installed.

**Comment by Plasmoid77** [comment]
I don't know, it is default LMDE installer. I tried to find it's name, but can't find any

**Comment by Plasmoid77** [comment]
I also tried to use older (default) kernel, but everything is the same. It can not boot

**Comment by PJ-Singh-001** [comment]
What is the download link for the ISO you are trying to customize?

**Comment by Plasmoid77** [comment]
Standard LMDE's one: https://linuxmint.com/edition.php?id=308

**Comment by PJ-Singh-001** [comment]
OK. I'll download and try on my end...

**Comment by PJ-Singh-001** [comment]
I am able to reproduce this problem.

I will see if I can find a solution.

**Comment by PJ-Singh-001** [comment]
The solution is straightforward...

On the [Options page](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page), [Boot tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#boot-tab), replace `boot=casper` with `boot=live` in the following files:
- `/boot/grub/grub.cfg`
- `/isolinus/live.cfg`

Please note, you will have to make this change each time you customize your ISO in Cubic. (This is because Cubic always automatically overwrites the `boot=` value to support other Operating Systems, but LMDE seems to specifically require `boot=live` instead of `boot=casper`).

Here is a screenshot of `/boot/grub/grub.cfg` showing the required change:

![/boot/grub/grub.cfg](https://github.com/PJ-Singh-001/Cubic/assets/19394936/dae667f0-4821-4ae6-8cb0-11d3c1dd1db1)

Here is a screenshot of `/isolinus/live.cfg` showing the required change:

![/isolinus/live.cfg](https://github.com/PJ-Singh-001/Cubic/assets/19394936/38fa65f9-ec52-457f-9bbe-1219e1e33d05)
