### ISSUE TITLE
Minimal & Fast Install from Cubic-generated ISO

### ISSUE THREAD

**Issue by methanoid** [PJ-Singh-001/Cubic#294]
**Describe the question**
Is there any way to make the Cubic-generated ISO not install and then uninstall packages. I'm basically trying to make a minimal Kubuntu (or other flavours) installer that installs what I want and nothing extra. Cubic gives me the desired end results but the install from the ISO is slow as it installs and then uninstalls apps (this is I believe the fault of Ubuntu who don't offer any true minimal installer options)

**What you have tried**
None, no ideas

**Expected behavior**
Behaviour is as designed, my question is whether it can be different

**OS Information (please complete the following information):**
Kubuntu 21.10 last tried

**Cubic Information (please complete the following information):**
Cubic Version: sorry, havent tried recently

**Screenshots**
n/a

**Comment by PJ-Singh-001** [comment]
Yes.

Before I provide the solution, let me explain why Ubuntu "installs, then uninstalls packages".

**Explanation**

As you know, Ubuntu has a Live Environment where you can try out the OS using a USB before you install. The Live Environment showcases a "full experience," which includes all of the software that a standard install would contain, to allow users to try out all of the features and software. To achieve this, the OS on the Live ISO contains all of this software preinstalled. When you install the OS to your disk, all of the preinstalled packages and software are simply copied to your disk.

In order to offer a minimal install option, the (Ubiquity) installer then removes packages that should not be included in a minimal installation of Ubuntu. This allows the ISO to be smaller, by not having to keep two separate versions of the OS in the same ISO file.

Cubic allows you to select which packages are _removed_ for a _minimal_ install on the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page). (Note, some packages are also removed for a full install; these packages are things that _may_ be needed in a Live Environment, but are _not_ needed on an installed system. Examples of such packages include the Ubiquity installer itself and language packs for foreign languages you have not selected during installation).

**Solution**

Cubic allows you to customize your Live Environment. This is done in the console on the [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page). Packages you install in this console will appear in the Live Environment. Packages you _remove_ in this console will obviously _not_ appear in the Live Environment. As I mentioned earlier, all of the packages on the ISO are copied to the installed system.

Therefore, your solution is simple. If you do not want packages to appear on your installed system (_and_ the Live Environment), simply _remove_ them on the [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page). (Naturally, the removed packages will also no longer be listed on the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page), because the installer can not remove a package that was never included on the ISO).

Using this technique, you can create a truly "minimal" install ISO, with _only_ the packages you want.

**Note about Ubiquity vs. Subiquity**

The [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page) is only available if your ISO uses the Ubiquity installer. Newer versions of Ubuntu use the Subiquity installer, and the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page) will not be displayed for these versions of Ubuntu.

- Ubiquity
  - Ubuntu Server 21.04, and prior versions
  - Ubuntu Desktop 22.10, and prior versions

- Subiquity
  - Ubuntu Server 21.10, and newer versions
  - Ubuntu Desktop 23.04, and newer versions

Regardless of the version of Ubuntu you are customizing, the above solution will help you create a "minimal" install ISO using Cubic.

For the versions of Ubuntu that use **Ubiquity**, Cubic customizes the **typical** install on the [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page).

In contrast, for versions of Ubuntu that use **Subiquity**, Cubic _only_ customizes the **minimal** install on the [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page).  This is due to the changes Canonical made to the installer, and is not due to Cubic.

Therefore, for Ubuntu Server 21.10+ and Desktop 23.04+, be aware that the Live Environment may _not_ reflect your changes, so you may not be able to test your customizations using the Live ISO. However, your changes will be still installed to your computer, but you **must** select the **mininal install** option in Subiquity.
