### ISSUE TITLE
Ubuntu Server 22.04 Disable Subiquity Installer

### ISSUE THREAD

**Issue by J4CY** [PJ-Singh-001/Cubic#299]
**Describe the question**

I'm trying to use Cubic to create a custom live Ubuntu Server ISO, which is served as a testing ISO for our lab. The ultimate goal is to serve this ISO via PXE to a server to run on RAM, and have it run through our auto-commissioning scripts & hardware tests, with a simple PASS/FAIL on the screen after it's complete.

Currently, I have customized the Ubuntu server ISO to run a systemd service, which will run our commissioning & stress scripts. However, I want to further customize the ISO by removing the installer and displaying the progress of our scripts. (is this possible on ubuntu server 22.04?) 

- We also plan on changing the systemd service to running our scripts from a user, and having that user auto-login to the tty on boot (instead of displaying the subiquity installer), so the output of the script / monitoring program can be viewed on the monitor.

**OS Information (please complete the following information):**
 - OS/Distro Name: Ubuntu Server
 - OS Version Ubuntu Server 22.04 

**Cubic Information (please complete the following information):**
 - Cubic Version: 2024.02.86
 - ISO Customizing: ubuntu-22.04.4-live-server-amd64.iso
 - Download Link:  https://releases.ubuntu.com/22.04.4/ubuntu-22.04.4-live-server-amd64.iso

ps: thanks in advance!

**Comment by PJ-Singh-001** [comment]
Canonical changed the way the Live ISO works, with Ubuntu Server 21.10 and Ubuntu Desktop 23.04.
They have introduced a layered file system on the Live ISO.

The Subiquity installer is a snap package that is on a layer that Cubic can not customize because it does not contain a complete Linux filesystem. (Additionally, there was never a way of modifying snaps from a container environment, like Cubic's Terminal page. I checked and Canonical has no plans to allow snaps to be managed from a container).

Unfortunately, because the Subiquity installer is on a layer that Cubic can not access, there is no way to do what you want.

You could attempt to modify an older version of Ubuntu Server that does not have Subiquity, but that may introduce even more challenges bringing packages and kernels up to current releases.

Alternatively, you could try to customize a Debian *Live* ISO, because Debian still uses the original ISO layout.

I am exploring ways for Cubic to handle the new layout, but the effort would be high, requiring significant re-coding of the application.

Ubiquity
- Ubuntu Server 21.04, and prior versions
- Ubuntu Desktop 22.10, and prior versions

Subiquity
- Ubuntu Server 21.10, and newer versions
- Ubuntu Desktop 23.04, and newer versions

I am going to close this issue because there is no work-around I can suggest for you.
Nevertheless, I will continue to explore if/how Cubic could handle the new ISO layout.

**Comment by J4CY** [comment]
Sounds like Debian Live OS is the way to go for now. Your insight and knowledge is much appreciated.

**Comment by PJ-Singh-001** [comment]
UPDATE:

Cubic version 2026-07-107 (and newer) introduced the ability to remove Snap packages.

You can now remove the Subiquity installer...

On the new [Snaps page](https://github.com/PJ-Singh-001/Cubic/wiki/Snaps-Page), remove the Ubuntu Desktop Bootstrap snap package.
