### ISSUE TITLE
Why can't I access the Typical and Minimal packages page?

### ISSUE THREAD

**Issue by AlezZ743** [PJ-Singh-001/Cubic#309]
**Describe the question**

After the terminal screen, the packages selector for the different types of installations should appear but it doesn't anymore

**What you have tried**

I already created a custum Ubuntu 22.04 ISO using Cubic in an Ubuntu 22.04 without issue. Went to create some more custom ISOs of both Ubuntu 23.10 and 24.04 and the packages selector is gone.

**Expected behavior**

After terminal, the packages selector screen should have popped up as it had done before.

**OS Information**
 - OS/Distro Name: Ubuntu
 - OS Version: Ubuntu 22.04

**Cubic Information**
 - Cubic Version: 2024.02.86
 - ISO Customizing: ubuntu-23.10.1-desktop-amd64.iso AND/OR ubuntu-24.04-desktop-amd64.iso
 - Download Link:  None

**Comment by XA-Hydra** [comment]
My assumption (please correct me if wrong here anyone) is that this is due to 23.10 and 24.04 using the new installer and not Ubiquity.

**Comment by AlezZ743** [comment]
Based on my findings, I have to agree with you. It has to be the launcher changing because I went and tried to use an Ubuntu 22.04 base again and it worked perfectly. It's just that Cubic is not designed with these new launchers in mind.

Anyway, thanks for your response!

**Comment by PJ-Singh-001** [comment]
Please note the following statement on the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page) Wiki:

> This page is only shown if Ubiquity is installed.

Canonical started using the Subiquity installer in Ubuntu Server 21.10 and Ubuntu Desktop 23.04.
Prior to Subiquity, Ubuntu ISOs used the Ubiquity installer.

The Ubiquity installer would copy all "Standard" files to the target computer.
Then it would _remove_ packages not needed for a Standard install, such as the Ubiquity package itself.
If the user had opted for a "Minimal" install, Ubiquity would remove additional packages _not required_ for a Minimal install.
In other words, Ubiquity would actually install the full OS, and then _remove_ packages from the installation to make it "Minimal".
Because of this, for Ubuntu Server 21.04 and earlier, and for Ubuntu Desktop 22.10 and earlier, Cubic displays the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page) to allow users to select packages to remove for a "Standard" or a "Minimal" install.

Subiquity works differently. It will install a "Minimal" system. If the user has selected a "Standard" install, it "layers" additional files on top of the minimal install. The layered files are sets o files, not packages, that are added. Therefore Subiquity has no need to manage package lists, so Cubic will not show the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page) for ISOs that use Subiquity.

For clarity, I've added the following statement on the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page) Wiki:
> For Ubuntu Server 21.10 (or newer) and Ubuntu Desktop 23.04 (or newer), this page will not be shown.
