### ISSUE TITLE
Virtual environment state save

### ISSUE THREAD

**Issue by aniruddha-a** [PJ-Singh-001/Cubic#312]
**Describe the question**

I am trying to customize a Ubuntu Jammy (22.04.4 server) live ISO, and I want to know if I can do customizations in phases
i.e., I make some changes (via dpkg/snap commands) in the virtual env shell, create ISO, test and if its not working then
I can come back and start where I left off

**What you have tried**

I tried this, and once I was able to get to a certain stage, I tried to open Cubic again, I saw that my earlier customizations
were not saved! :( Am I missing something ? I have a project directory for Cubic and it seems to be saving some config

Its tedious to start all the customizations from scratch each time, as I am working with some snapd snaps
(and they are painful to set-up/copy! :-/ )

* what I expected *
That the state would be saved and I can come back to the same state each time

**OS Information (please complete the following information):**
 - OS/Distro: Ubuntu Jammy 22.04.4
- OS Version:
```
ani@ani-e14:~/jammy-cust$ lsb_release  -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
```

**Cubic Information (please complete the following information):**
 - Cubic Version:  
``` 
ani@ani-e14:~/jammy-cust$ cubic --version 
Cubic version... 2024.02.86
Copyright....... © 2015, 2020 PJ Singh
Website......... https://github.com/PJ-Singh-001/Cubic

ani@ani-e14:~/jammy-cust$ dpkg -l | grep cubic 
ii  cubic          2024.02-86-release~202402210133~ubuntu22.04.1 all
```
 - ISO Customizing: [ubuntu-22.04.4-live-server-amd64.iso]
 - Download Link:  https://releases.ubuntu.com/jammy/ubuntu-22.04.4-live-server-amd64.iso

**Comment by PJ-Singh-001** [comment]
_Yes_, your customizations are saved, and _yes_ you can continue customizing your project where you left off.

Please note, you can not manage snap packages in [Cubic's virtual environment](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page). Currently there is no solution for this, because of the way snaps were implemented by Canoical. To work around this, I do the following:
1. Delete the `snapd` package using `apt purge snapd`; this has the side effect of removing all snaps
2. Reinstall the `snapd` package using `apt install snapd` (so snaps can be installed once the OS has been installed to disk)
3. Install the deb versions of the software I want to add to the custom OS, using `apt` or `dpkg -i` or `gdbi`

Do not try to use the `snap` command in  in [Cubic's virtual environment](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page).

Since you are customizing the Server version, you **must** select _Minimal Install_ when installing your customized OS.

You may not be able to test all of your changes in the [emulator in Cubic](https://github.com/PJ-Singh-001/Cubic/wiki/Finish-Test-Page). (This issue is due to the new Subiquity installer and the new layout Canonical introduced for the ISOs; I am still trying to figure out a solution to allow Cubic to handle the new structure). You will have to actually install the customized OS to see your changes. To work around this, I usually install onto a virtual disk in Virtual Box to test.
