### ISSUE TITLE
i have error while mount Ubuntu 18.04 on cubic

### ISSUE THREAD

**Issue by Fathir34** [PJ-Singh-001/Cubic#318]
**Question**

it can't mounting Ubuntu 18.04 when Ubuntu 18.04 **"NOT"** Mounted on nautilus

**Expected behavior**

**OS Information (please complete the following information):**
 - OS/Distro Name: Ubuntu
 - OS Version Ubuntu 18.04

**Cubic Information:**
 - Cubic Version: 2024.02.86
 - ISO Customizing: Ubuntu_Fusion.iso (i changed the name)
 - Download Link:  https://drive.usercontent.google.com/download?id=1xEq0Srx6BSyQvqZofnyGeJXQ_Pf30xlk&export=download&authuser=0

**Screenshots**

![Screenshot 2024-05-24 8 18 01 PM](https://github.com/PJ-Singh-001/Cubic/assets/166030852/7a544ec6-6bba-4213-98a9-ac0134937c0f)

**Comment by PJ-Singh-001** [comment]
Cubic needs exclusive use of the ISO so it can mount it.

One reason for this is that you've accidentally clicked on your downloaded *.iso file, causing it to be mounted by the file browser (Nautilus). You may refer [this comment](https://github.com/PJ-Singh-001/Cubic/issues/11#issuecomment-1009080208) for more information.

Since you have indicated that the *.iso is not mounted by Nautilus, it may be mounted by another process. Use the `mount` command to find where it is mounted.
