### ISSUE TITLE
No root device specified, after try update kernel in iso.

### ISSUE THREAD

**Issue by Tibou-17** [PJ-Singh-001/Cubic#329]
**Describe the question**

I want update the kernel version inside the ubuntu-22.04.4-live-server-amd64.iso to linux-image-6.5.0-41-generic.
I need a recent kernel version for a recent hardware, old kernel version do not detect the NVMe disk.
Btw I can't for now use Ubuntu 24.04, I exec post script installation that depend of the target system and 24.04 is not yet supported.

**What you have tried**

1. Run cubic
$ cubic ~/projet/cubic/ ~/téléchargements/ubuntu-22.04.4-live-server-amd64.iso

2. Cubic GUI click on next

3. Cubic GUI click on next (I leave default parameters for disk).

4. Inside cubic shell of virtual environment
root@cubic:\~# apt update
root@cubic:~# apt install linux-image-6.5.0-41-generic

5. During installation I see a error and I can reproduce it
update-initramfs: Generating /boot/initrd.img-6.5.0-41-generic
cryptsetup: ERROR: Couldn't resolve device /dev/mapper/vgubuntu-root
cryptsetup: WARNING: Couldn't determine root device
cryptsetup: ERROR: Couldn't resolve device /dev/dm-2
I: The initramfs will attempt to resume from /dev/dm-2
I: Set the RESUME variable to override this.

6. Reproduce error
root@cubic:~# update-initramfs -u
update-initramfs: Generating /boot/initrd.img-6.5.0-41-generic
cryptsetup: ERROR: Couldn't resolve device /dev/mapper/vgubuntu-root
cryptsetup: WARNING: Couldn't determine root device
cryptsetup: ERROR: Couldn't resolve device /dev/dm-2
I: The initramfs will attempt to resume from /dev/dm-2
I: Set the RESUME variable to override this.

7. Cubic GUI click on next

8. I select the new installed kernel 6.5.0-41 and click on next

9. I click on generate

10. I click on test

**Expected behavior**

Linux kernel boot correctly and Ubuntu set up program start.

**OS Information :**
 - OS/Distro Name, Version: Ubuntu 22.04.4 LTS

**Cubic Information :**
 - Cubic Version: 2024.02-86-release\~202402210133~ubuntu22.04.1
 - ISO Customizing: ubuntu-22.04.4-live-server-amd64
 - Download Link: https://releases.ubuntu.com/22.04.4/ubuntu-22.04.4-live-server-amd64.iso

**Screenshots**

![image](https://github.com/user-attachments/assets/ae4e90e2-216f-461c-9ed7-152ba365de06)

**Comment by PJ-Singh-001** [comment]
The kernel you had selected on the [Kernel tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#kernel-tab) in Cubic is used to bootstrap the ISO / Live Environment.

Bootstrapping is the process used to "load" the OS from the disk, and it can be different from the kernel used by your OS.

The kernel you installed (6.5.0-41) does not allow ISO bootstrapping.

Nevertheless, you can still use kernel 6.5.0-41-generic on your installed system.

1. Install your desired kernel. _Remember to execute `update-initramfs -u`._

        apt update
        apt install linux-image-6.5.0-41-generic linux-headers-6.5.0-41-generic
        update-initramfs -u

 2. On the [Kernel tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#kernel-tab) in Cubic, do _not_ select the new kernel you installed. Instead, accept the default kernel. Please note the instructions...

    > Select this kernel if you are unable to boot the disk using other kernel versions. Use this kernel to bootstrap Ubuntu Server 21.10+ or Desktop 23.04+.

    ![Screenshot from 2024-07-12 15-29-43](https://github.com/user-attachments/assets/3af3a24a-63d3-40c4-b646-adf9bd19dfb3)

 3. When you [test your customized ISO](https://github.com/PJ-Singh-001/Cubic/wiki/Finish-Test-Page) in Cubic, it will still use the original kernel (5.15) that came with the ISO, because this is what you just selected on the [Kernel tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#kernel-tab) and, consequently, was used to boot the ISO.

    However, you will note that the new kernel was indeed installed in the `/boot` directory of the custom OS.

    ![Screenshot from 2024-07-12 14-58-06](https://github.com/user-attachments/assets/dfaa5e5f-0730-4609-9137-6e621c86ebc1)

    ![Screenshot from 2024-07-12 15-58-20](https://github.com/user-attachments/assets/5295bd09-e546-4894-a081-4a05ee889b00)

 4. Finally install your customized ISO to your computer (Please see _Important Notes_ below).

    It will use the updated kernel (6.5.0-41).

---

**Important notes:**

- During installation, be sure to select the minimal install (not the standard install), because the changes you made in Cubic's virtual environment apply to the minimal install only.
- Not all of your changes may be visible when you test your customizations. This is because the Ubuntu Live Environment "overlays" the _standard_ install on top of your _customized minimal_ install. (The upcoming release of Cubic will remedy this issue).

**Comment by Tibou-17** [comment]
For my installation I need update the bootstrap kernel for the ISO, cause the default kernel do not detect the NVMe disk, so I can not install anything in fact, no disk detected.

But true I also need install a recent kernel for my install system boot and it also detect NVMe disk.

In fact I need both.

I check what kernel is used for ubuntu-24.04-live-server-amd64.iso :
casper/vmlinuz: Linux kernel x86 boot executable bzImage, version 6.8.0-31-generic (buildd@lcy02-amd64-080) #31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024, RO-rootFS, swap_dev 0XE, Normal VGA

So is it possible to insert in my custom install a more recent kernel compatible with iso bootstrapping ?
Like 6.8.0-31-generic for example.

I search with apt and this version with repo of Ubuntu 22 version is not.

Where I can find other bootstrapping kernel version ? And how install it in my custom iso ?

Thanks for your answer and your time, I will continue investigate it and wait your answer.

Have a nice day.

**Comment by PJ-Singh-001** [comment]
You mentioned you wanted to install Linux Kernel 6.5.0-41 because it supports NVMe devices. I assume newer kernels can also support the NVMe devices. Each Ubuntu ISO comes with a kernel that can bootstrap the ISO. Cubic allows you to use the kernel from a newer version of Ubuntu for bootstrapping, while customizing an older version of the Linux file system.

Ubuntu 24.04 comes with kernel 6.8.0-31. Here is how you can use this kernel to boot the Ubuntu Live Server 22.04.4 ISO. You will need `ubuntu-24.04-live-server-amd64.iso`, so download this first.

 1. On Cubic's [Project page](https://github.com/PJ-Singh-001/Cubic/wiki/Project-Page), choose to customize "ubuntu-22.04.4-live-server-amd64.iso".
 2. Click <kbd>Next</kbd> until you arrive a the [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page).
 3. Click the <kbd>Back</kbd> until you arrive a the [Project page](https://github.com/PJ-Singh-001/Cubic/wiki/Project-Page) again.
 4. Under the "Original Disk" section on the left, click the folder icon to select a new ISO.

    Select `ubuntu-24.04-live-server-amd64.iso`, which you downloaded earlier.

 5. Click <kbd>Next</kbd>. You will be take to the [Extract page](), but only the "_Analyze the original disk_" and the "_Copy important files from the original disk_" processes will be repeated. Your previously extracted Linux file system (that you are customizing) will be retained, so you will not see an "_Extract the compressed Linux file system_" process.

 6. On the [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), continue to customize 22.04.4. You can type the following command to confirm this is still the version of Ubuntu you wanted to customize.

        lsb_release --release
        Release:    22.04.4

 7. Finish making your changes.

 8. Although it is not necessary, you could install a different kernel into your customized ISO. (Note: This will only be used _after_ you install your OS onto a computer. Kernel 6.8.0-31 will be used to boostrap your ISO into the Live Environment. If you are OK with using kernel 6.8.0-31 in your installed OS, you can skip this step.

        apt update
        apt install linux-image-6.X.X-XX-generic linux-headers-6.X.X-XX-generic
        update-initramfs -u

 9. Click <kbd>Next</kbd>.

10. On the [Options page](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page), [Kernel tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#kernel-tab), you will notice that the bootstrap kernel is 6.8.0-31. This kernel was copied in step 5 from the 24.04 ISO you had selected on the [Project page](https://github.com/PJ-Singh-001/Cubic/wiki/Project-Page).

11. Continue clicking through the remaining pages to generate your customized ISO.

12. On the [Finish page](https://github.com/PJ-Singh-001/Cubic/wiki/Finish-Page), [test your customized ISO](https://github.com/PJ-Singh-001/Cubic/wiki/Finish-Test-Page). Note that kernel 6.8.0-31 is being used.

        uname -r
        6.8.0-31-generic

**Comment by Tibou-17** [comment]
Ok so.

With the process you gave me, I can update the live kernel ISO. 
The problem is that version 6.8 is too recent; the glibc is outdated, which causes around 10 services to fail, and most commands don't work (like the 'man' command, for example).

So I tried with the latest Ubuntu Desktop 22.04 image that contains kernel 6.5, but it produced strange results. 
The built ISO doesn't install anything, and after starting, it only goes to the login screen.

But I don't understand why version 6.8 is not working. Why is a new version of glibc required?

Hmm, yeah, I also tried to compile my own glibc version inside the virtual terminal environment, but it seems that it does not affect the live system.

I don't know what source files the live system uses for booting or how to update those source files.

![image](https://github.com/user-attachments/assets/22f2046a-2f24-4d53-902b-9e1782e1e345)

**Comment by PJ-Singh-001** [comment]
For the newer ISOs, Canonical has "layered" multiple Linux file systems, one on top of the other.
1. minimal
2. standard
3. installer
4. (others)

The "minimal" file system is complete, and this is the one you can customize in Cubic.
The other file systems are incomplete and depend on the lower system for libraries, files, etc.

It is likely that the "installer" or "standard" file systems require the older version of `glibc` or the older kernel, so the combined filesystem (minimal + standard + installer) does not work in the live environment.

The new release of Cubic will combine minimal and standard file systems into one, and this _may_ help. The release should be ready within a few weeks.

If you share the explicit steps and commands to compile `glibc` and I will try them with the development code base of Cubic to see if it works.

**Comment by Tibou-17** [comment]
Hum yeah ok, I understand.

Well I'm not a expert of C compilation and glibc compilation, I follow some tutorial.
- https://github.com/jueve/build-glibc
- http://www.yl.is.s.u-tokyo.ac.jp/~tosh/kml/how_to_build_and_use_glibc.html
- https://www.gnu.org/software/libc/manual/html_node/Configuring-and-compiling.html

From what I understand there is four main step:
1. Download
2. Prepare / configure (Using configure script)
3. Compile / Install (Using make)
4. Deploy and test (The hardest one I think).

Well, thanks you for your time, and your investment in this project.
Maybe this issue should be renamed as something like "How to update live kernel in Ubuntu server iso" ?

Wanna wait your next release and test it in future :).

Have a nice day.

**Comment by PJ-Singh-001** [comment]
I do have a “How to” for updating kernels posted in the “Resolved Issues” section, but it relies on pre-compiled kernels. Nevertheless, this usually doesn’t work with the newer ISOs.

I’ll look at the links you shared. But please be patient, since there is a big backlog of work right now.

**Comment by AdityaGarg8** [comment]
Unfortunately I myself am affected by this issue. Has there been a fix yet? I would like to make ISOs with custom kernels.

**Comment by Tibou-17** [comment]
I don't think so, and I think it's quite complex.

**Comment by AdityaGarg8** [comment]
I've noticed that the kernel that has to bootstrap the iso lives in another squashfs file. Also in the chroot in cubic, that kernel is not visible in `ls /boot`. I wonder how is that handled.
