### ISSUE TITLE
how to load an existing project folder

### ISSUE THREAD

**Issue by H3xKatana** [PJ-Singh-001/Cubic#332]
i m building a custom iso and do most of the work and before building the final iso i accendtily killed cubic process i got the folder with all i need all ineed is to build it be there is no opetion to load existing project in Cubic

**Comment by PJ-Singh-001** [comment]
I suspect Cubic never got to save the project’s configuration file, because you killed the process.
It’s always best to click the window close button to allow the application shutdown properly.

Please share the contents of…

    cd <your project folder>
    ls -la

If your `cubic.conf` file is missing, I may be able to help your manually create one from scratch, so you don’t lose all of your work. But first I need to see the situation.

**Comment by H3xKatana** [comment]
So before reading your response i've  rebuilt  the iso now  it worked now , also after reading the cubic config file i understand that this file could be done manually anyway thanks for the help
