### ISSUE TITLE
Error. Unable to extract the compressed Linux file system.

### ISSUE THREAD

**Issue by Tian-HP** [PJ-Singh-001/Cubic#336]
**Describe the question**

Error. Unable to extract the compressed Linux file system.

**What you have tried**

Reinstalled Cubic Version 2024.02.86

**OS Information (please complete the following information):**
 - OS/Distro Name: Ubuntu
 - OS Version: Ubuntu 2024.04

**Cubic Information (please complete the following information):**
 - Cubic Version: 2024.02.86 from apt-get 
 - ISO Customizing: [Ubuntu MATE 24.04 (Noble Numbat) Daily Build]
 - Download Link: 
 
https://cdimage.ubuntu.com/ubuntu-mate/noble/daily-live/current/noble-desktop-amd64.iso

**Comment by PJ-Singh-001** [comment]
I have a download of Noble from March 27th, and that extracts without issue in Cubic.
In my experience, the daily builds for an upcoming release are often not ready, and therefore typically can not be extracted in Cubic (until they release the Beta versions).
I'll try to download the ISO you linked to above and see if I get the same error.

**Comment by PJ-Singh-001** [comment]
I downloaded MATE 24.04 Noble Numbat on August 4th, 2024 using the link you had shared.
It extracts without issue in Cubic.

If you are still having problems, try downloading the `*.iso` file again. It may be corrupt, or the developers may have uploaded fixes since you had downloaded it.

I also suggest you try the upcoming release of Cubic.

    # Remove release version 2024.02.86 of Cubic.
    sudo add autoremove cubic

    # Make sure there are no old files left by apt.
    sudo rm -rf /usr/share/cubic

    # Remove the Cubic "Release" repository.
    sudo add-apt-repository --remove ppa:cubic-wizard/release

    # Add the Cubic "Experimental" repository.
    sudo apt-add-repository universe
    sudo apt-add-repository ppa:cubic-wizard/experimental
    sudo apt update

    # Install an EXPERIMENTAL version of Cubic.
    sudo apt install --no-install-recommends cubic

If you try the experimental version, you should create a new Cubic project to use the fixes / enhancements.
