### ISSUE TITLE
Debian GNU/Linux 12 (bookworm) x86_64: Cubic freezes on the analysis process.

### ISSUE THREAD

**Issue by codydafoxie** [PJ-Singh-001/Cubic#343]
**Describe the bug**

I'm on Debian GNU/Linux 12 (bookworm) x86_64 and I want to modify the ISO of the same version as my host. Bur when I enter the "Extracting the original disk..." screen, the whole process freezes on the analysis, as seen on the screenshot.

However, the analysis works when using a Ubuntu 24.04 ISO

**To Reproduce**
- Open Cubic
- Select a directory
- On the next screen choose the debian ISO
- press next

**Expected behavior**

The analysis should finish but after ≈10 minutes nothing happens.

**OS Information:**
 - OS/Distro Name: Debian GNU/Linux
 - OS Version Debian GNU/Linux 12 (bookworm) x86_64
 - Kernel version: 6.1.0-25-amd64 

**Cubic Information:**
 - Cubic Version: 2024.09.88
 - ISO Customizing: debian-12.7.0-amd64-DVD-1
 - Download Link:  *Downloaded using Bittorrent but a HTTPS mirror exists too ->* https://cdimage.debian.org/debian-cd/current/amd64/iso-dvd/debian-12.7.0-amd64-DVD-1.iso

**Cubic Log:**

[cubic.20240906203705.log](https://github.com/user-attachments/files/16912039/cubic.20240906203705.log) 

**Screenshots**

![image](https://github.com/user-attachments/assets/12340fda-d699-4268-9ab5-b6ff7339a234)

**Comment by PJ-Singh-001** [comment]
Thank you for the information and log file. I'll look into this.

**Comment by codydafoxie** [comment]
Thank you.

**Comment by PJ-Singh-001** [comment]
Cubic only customizes _Live_ ISOs.

From the [top-level directory](https://cdimage.debian.org/debian-cd/), click on [current-live](https://cdimage.debian.org/debian-cd/current-live/).
There are [multiple ISOs available](https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/) with different desktop environments.
They also have a ["standard" ISO](https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/debian-live-12.7.0-amd64-standard.iso) you can download.

![image](https://github.com/user-attachments/assets/6cc081f6-ad44-4f15-abc0-f0de954531fb)

I'll look into possibly showing an error like, "Unable to analyze the original disk image", but I will not be able to specifically tell the user that the ISO is not a _Live_ ISO, because this would be difficult to identify.

Once you get past this step, be on the look out for Issue #342, [Error: Unable to update the vmlinuz boot file - During generation ISO in Debian 11](https://github.com/PJ-Singh-001/Cubic/issues/342). This issue was reported for Debian 11, but please comment on that bug report it also affects Debian 12.

**Comment by yonacwy** [comment]
I had same problem testing on a non live iso, tested on a live and it worked.
