### ISSUE TITLE
The `setxkbmap` command does not work to update the user keyboard.

### ISSUE THREAD

**Issue by sudo-joe** [PJ-Singh-001/Cubic#36]
Hello forum

tried to change the keyboard-layout on the cli(terminal) to swiss-german with 'setxkbmap ch'. The following message is shown:

    root@cubic:~# setxkbmap ch
    Cannot open display "default display"
    root@cubic:~# 

Thank's for your help!

Joe

PS:
 I am on Cubic 22.01.70

**Comment by PJ-Singh-001** [comment]
"sudo-joe", from your user name, I can see you _really_, _really_ want to use `sudo`, but as I mentioned in [your other question](https://github.com/PJ-Singh-001/Cubic/issues/37), don't use `sudo`, because in the [Cubic Terminal environment](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page) you already have root (read/write) access to the files you are attempting to modify.

**Comment by PJ-Singh-001** [comment]
Your above command is not working because it expects the X11 (service) to be running.
As I mentioned in [the answer to your other question](https://github.com/PJ-Singh-001/Cubic/issues/37), services do not run in the [Cubic Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page) because it is not a "running" OS.

In order to change the keyboard-layout, you have two options:
 1. Modify the files that `setxkbmap` would update. (You can use the `nano` editor to modify files).
    I do not know which files these are, off the top of my head, but you can research that.
 3. Use preseeding to select your keyboard.
    This question already has an answer.
    Please see [How to automate installation using Preseed for keyboard, time zone, locale, and user?](https://github.com/PJ-Singh-001/Cubic/issues/24).
