### ISSUE TITLE
How to reboot Cubic's "virtual environment" using the CLE on the Terminal page?

### ISSUE THREAD

**Issue by sudo-joe** [PJ-Singh-001/Cubic#37]
Hello

after upgrading my Ubuntu 18.04 with 'dist-upgrade', i would like to reboot it with 'shutdown -r now'.
The following message is shown:

    root@cubic:~# sudo shutdown -r now
    System has not been booted with systemd as init system (PID 1). Can't operate.
    Failed to talk to init daemon.
    root@cubic:~# 

Is there an other approach to reboot a cubic environment?

Thank's a lot

Joe

**Comment by PJ-Singh-001** [comment]
The Cubic [Terminal](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page) environment is not a "running" OS.
It is just a secure, isolated file system that you have root access to, in order to edit, add, or delete files.
Any changes you make to the file system are applied immediately.

There are **no** active services, as you would find in an actual running OS.
Therefore, do not expect `systemd` to be running.
Likewise, other services such as `snapd` do not run in this environment.

_With this in mind, the concept of "rebooting" does not apply._

By executing `dist-upgrade`, you simply ran a program (*not a service!*) that downloaded a bunch of files (i.e. packages) and copied them into this secure file system. Thus, you do not need to "reboot".

---

However, if you really want to exit and re-enter the Cubic [Terminal](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page) environment, you have four choices:

 1. Simply type `exit` in the [Terminal](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page) and press <kbd>Enter</kbd>.
     You will exit the [Terminal](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page) environment, and Cubic will automatically reenter the environment within a few miliseconds.
 2. Alternatively, you can click the <kbd>Back</kbd> button in Cubic's header bar, and then click the <kbd>Customize</kbd> button in the header bar to return to the Cubic [Terminal](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page) page.
 3. Another option is to click the <kbd>Next</kbd> button in Cubic's header bar, and then click the <kbd>Back</kbd> button in the header bar to return to the Cubic [Terminal](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page) page.
 4. The last option is to just quit Cubic, restart Cubic, and chose your existing project to continue customizing it.
 
_All of these options are the same. They have no effect on the file system you are updating. No new services will run and the changes applied to your customized OS will not be any different than if you had stayed in the [Terminal](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page) environment._

**Comment by PJ-Singh-001** [comment]
(By the way, don't use `sudo`, you are already root!)
