### ISSUE TITLE
How to use a custom compiled kernel in Cubic (Ubuntu 20.04 arm64)?

### ISSUE THREAD

**Issue by Mistuke** [PJ-Singh-001/Cubic#39]
**Describe the question**

I am trying to install a custom kernel on the Ubuntu 20.04 Arm64 ISO.
I get a new ISO at the end but when I try booting from it the kernel panics with
```
/init: .: 159: Can't open /scripts/casper
[      34.851480] Kernel panic - not syncing: Attempted to kill init!
```
I would imagine the x86_64 and Arm64 ISOs are laid out the same?

**What you have tried**

Tried to search around for a solution.

**Expected behavior**

Expect installation to start.

**OS Information (please complete the following information):**
 - OS/Distro Name: Ubuntu
 - OS Version : Ubuntu 20.04 Arm64

**Cubic Information (please complete the following information):**
 - Cubic Version: 2022.01-70-release~202201240317~~ubuntu20.04.1
 - ISO Customizing: ubuntu-20.04.4-live-server-arm64.iso
 - Download Link:  http://cdimage.ubuntu.com/releases/20.04/release/ubuntu-20.04.4-live-server-arm64.iso

**Comment by PJ-Singh-001** [comment]
Did you install your kernel from the official Ubuntu repositories, did you download the kernel from somewhere else, or did you compile your own kernel?

**Comment by Mistuke** [comment]
> Did you install your kernel from the official Ubuntu repositories, did you download the kernel from somewhere else, or did you compile your own kernel?

I compiled my own kernel, but it looks like it's the content of the `initrd` that cubic creates, it does indeed actually miss the entire `/scripts/casper` folder.

manually unpacking and repacking the `initrd` using `unmkinitramfs` and `cpio` gave me a working image, which was also significantly larger than the one cubic made.

**Comment by PJ-Singh-001** [comment]
You must have a `initrd` that matches your `vmlinuz` file.
You can try executing `update-initramfs -u` or `update-initramfs -k all` to generate the `initrd` file.

Also, it may be hard for Cubic to identify which `initrd` corresponds to which `vmlinuz` (this usually happens when you create your own kernel files, as in your case). To overcome this, give your `initrd` and your `vmlinuz` files the same unique version name. (This is the portion of the file name following the `-`). For example, you could name your files:

    initrd.img-5.4.0-60-generic
    vmlinuz-5.4.0-60-generic
