### ISSUE TITLE
Is `/var/cache/apt/archives` of Cubic shared with the host OS?

### ISSUE THREAD

**Issue by sudo-joe** [PJ-Singh-001/Cubic#43]
Hello

would like to backup(tar) my cubic folder. It should become as small as possible :) In the cubic filesystem I was unable to find /var/cache/apt/archives..

- does 'apt-get dist-upgrade' cache the *.deb's as well in /var/cache/apt/archives of the host?
- is it advisable to delete the cached files before backing up the cubic project folder?

Thank's a lot!

Joe

**Comment by PJ-Singh-001** [comment]
Cubic does not use the `/var/cache/apt` folder from your host machine. The [Terminal environment](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page) is completely isolated from your host machine, except for the network configuration (which is used as read-only from your host machine). Therefore, the cached `apt` files are unique to your Cubic project.

Please be very cautious about deleting `/var/lib/apt` due to bug #30.

Instead of deleting files under `/var/cache/apt` or `/var/lib/apt`, always do the following just before clicking the <kbd>Next</kbd> button on the [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page). This will safely clear out your cache.

    apt -f install
    apt --yes autoremove
    apt --yes autoclean
    apt --yes clean
