### ISSUE TITLE
How to upgrade Linux Mint in Cubic?

### ISSUE THREAD

**Issue by eband** [PJ-Singh-001/Cubic#44]
There has been some concerns as of late on where the Cubic project is heading.

Lately, Mint developers seem to have gone to a GUI approach when it comes to upgrade to a milestone release.

P.J. Singh, if you have a chance to read this, please tell me what you think: https://blog.linuxmint.com/?p=4293

The new update sounds intriguing, but my concern is if Cubic can adapt the new updates.

So, again, if you can get back to me, or us, please tell us of current plans for the project.

Thank you.

**Comment by PJ-Singh-001** [comment]
The tool you linked to looks nice. This would obviously be useful to a user who has installed Mint, made changes by installing PPAs and packages, and then wishes to upgrade to a new release.

Of course, everything this tool does can be done from the command line. Specifically, take a look at `apt dist-upgrade`, which is what I think this tool is doing.

---

Using Cubic you can chose to customize the _latest_ release, so there should be no need to upgrade to a new release within Cubic itself.

In this case, the procedure should be:

 1. Download the _latest_ ISO for the release you want to upgrade to.
 2. Launch Cubic, create a new project, and select this ISO to customize.
 3. Execute `apt-add-repository <official Mint repository>` for _each_ official repository (just to ensue that each official repository is enabled).
 4. Execute `apt upgrade` or `apt dist-upgrade` or `apt full-upgrade`. (If you've started with the most recent ISO in step 1, you should only need `apt upgrade`. Also, there will be no package conflicts if you start with an official ISO).
 5. Then, add your custom PPAs using `apt-add-repository <non-official repository>` for each non-official repository. (If the PPA is no longer available for your upgraded release, you will be notified, and you will not be able to add the PPA).
 6. Then install the packages from those PPAs using `apt install <non-official package name>`.
 7. Lastly, apply your other customizations (such as configuring themes, or configuring software).

This approach will ensure there are no package conflicts while creating the new ISO.

---
However if you have an old Cubic project and you want to upgrade that to a newer release, you should:

 1. Launch Cubic and open your existing project.
 2. Remove each non-official package (i.e. packages from non-official PPAs) using `apt remove <non-official package>` for each non-official package.
 3. Remove each each non-official repository using `apt-add-repository --remove <non-official repository>` for each non-official repository.
 4. Execute `apt-add-repository <official Mint repository>` for _each_ official repository (just to ensue that each official repository is enabled).
 5. Execute `apt upgrade` or `apt dist-upgrade` or `apt full-upgrade`. (You probably want to use `dist-upgrade` since this has a has a "smart" conflict resolution system).
 6. Then, re-add your custom PPAs using `apt-add-repository <non-official repository>` for each non-official repository. (If the PPA is no longer available for your upgraded release, you will be notified, and you will not be able to add the PPA).
 7. Then install the packages from those PPAs using `apt install <non-official package name>`.
 8. Lastly, apply your other customizations as necessary (such as configuring themes, or configuring software).

This approach will ensure there are no package conflicts while upgrading an existing Cubic project.

**Comment by eband** [comment]
Thank you, P.J.

EDIT: OK, sorry if I sound like a baby that wants to be spoon-fed, but does `apt dist-upgrade` do the actual upgrade, or what?

EDIT: And another thing: what is the point of re-adding the official repositories (second set of instructions, step four if you're not going to touch it to begin with?

**Comment by eband** [comment]
About the first edit... of course it was. I just made an ass out of myself. Please overlook my behaviour.

**Comment by PJ-Singh-001** [comment]
To answer your last "Edit" question, the reason you may want to re-add the official repositories is because the official repositories may not be enabled when you are customizing the ISO, and the official repositories may also not be enabled in the Live Environment. (This may not be the case for Linux Mint (?), but it is the case for other Ubuntu based distros).

The installer actually sets all of the official repositories _after_ installation, so some of them are not enabled when you are in Cubic's Terminal environment or the Live ISO environment. (For example the `universe` repository is not enabled in Ubuntu until _after_ your installation has completed).

I think this is done so software is added from the "cdrom" instead of via the Internet; this obviously helps avoid errors if the user doesn't have Internet access during installation, and it saves time and bandwidth during installation.

Therefore, as a precaution, re-adding the official repositories avoids potential issues. If the repositories are already enabled, no changes are made, but if they are not enabled, they will be added. In other words, it can't hurt, but it may help.

**Comment by eband** [comment]
About upgrading, I didn't use mintupgrade to upgrade from 20.2 to 20.3; I used dist-upgrade to upgrade so my bad.

This time around, would I just use the mintupgrade2 command from Cubic or are you not sure yet?

Any answer would suffice.

And thank you for helping me so far.

EDIT: Anyhow, whatever you answer, when the times to upgrade to Mint 21, I will avail myself to your help.

I set that time because there is a logic in that if you witness the new update software, you can get more questions answered at that time.

Thank you very much.

**Comment by eband** [comment]
Now, I said that I will ask you again when it's time to upgrade and I will, but first, I just need to answer one question before i do.

The steps you listed in the thread are general steps to upgrade to a later version of any Ubuntu-based OS, right?

EDIT: What I meant was these steps outlined in that link were steps to upgrade one edition of an Ubuntu-based OS to the later version of that Ubuntu-based OS, right?

EDIT: The reason I'm asking for steps on doing a full-blown milestone upgrade is that I have two programs that I am holding due to the versions breaking down.

OK, I'm done talking for now. I'll back off.

**Comment by eband** [comment]
OK, one more and I swear I will stop!

Why do I have to delete non-official packages prior to upgrading?

NOW, I'll back off!

**Comment by PJ-Singh-001** [comment]
If a package is installed on your system, and the package is no longer available for the newer OS release, you will have package dependency problems.

This doesn't happen for official packages because the developers and package maintainers take care of it.

But the developer or package maintainer of an unofficial package does not have an obligation to make sure their package works on your specific distro or your specific version of your distro.

Therefore, in my opinion, it is a good practice to remove an unoffical package, update your distro, and then simply reinstall the unofficial package. At that point, you'll be notified if the package can not be (re)installed, but this will not have impacted your distro upgrade.

**Comment by eband** [comment]
A follow-up question (I guess I can't resist, can I?): if the package is held back, does it still risk dependency problems?

I ask because I have two sorts of packages held back at the moment: Samba (official to Mint) and Wine (which is pointing to WineHQ's repository). These are held back because the later versions have bugs that I don't like.

If I upgraded the OS holding those back, will they interfere?
