### ISSUE TITLE
How to fix ISO Grub menu countdown loop (for Zorin OS)?

### ISSUE THREAD

**Issue by piotrbadelek** [PJ-Singh-001/Cubic#49]
**Describe the bug**

All Zorin OS 16 ISOs customized using Cubic don't boot past the GRUB screen. When adding `nomodeset debug nosplash` to the "Install or try Zorin OS" GRUB option, it outputs `Loading /casper/vmlinuz` before going back to GRUB. Safe graphics and modern NVIDIA drivers also don't work.

**To Reproduce**

1. Generate a Zorin OS ISO using Cubic, without any customizations
2. Either create a virtual machine and boot with the ISO, or use the built-in test option.
3. Try to launch the OS - it won't work.

**Expected behavior**

I expected the ISO to actually boot into an operating system.

**Host OS Information:**
 - OS/Distro Name: Ubuntu
 - OS Version: Ubuntu 20.04.4 LTS

**Cubic Information:**
 - Cubic Version: 2022.01.70 
 - ISO Customizing: Zorin-OS-16.1-Education-64-bit.iso
 - Download Link:  https://zorin.com/os/download/16/education/

**Cubic Log:**
```
Gtk-Message: 11:03:01.123: Failed to load module "appmenu-gtk-module"

(cubic:23073): Gtk-WARNING **: 11:03:01.947: Content added to the action area of a dialog using header bars

(cubic:23073): Gtk-WARNING **: 11:03:01.947: Content added to the action area of a dialog using header bars

(cubic:23073): Gtk-WARNING **: 11:03:01.977: Content added to the action area of a dialog using header bars

(cubic:23073): Gtk-WARNING **: 11:03:01.977: Content added to the action area of a dialog using header bars

(cubic:23073): Gtk-WARNING **: 11:03:02.008: Content added to the action area of a dialog using header bars

(cubic:23073): Gtk-WARNING **: 11:03:02.008: Content added to the action area of a dialog using header bars
```
**Screenshots**

![Screenshot from 2022-04-16 11-20-31](https://user-images.githubusercontent.com/37271169/163669585-1d2e2dab-4757-4786-80d4-70133088d287.png)
![Screenshot from 2022-04-16 11-21-35](https://user-images.githubusercontent.com/37271169/163669598-cc70129e-d08c-4387-9738-1ba4d2b8f4ad.png)

**Comment by PJ-Singh-001** [comment]
When you navigate to the [Options page](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page) in Cubic, you will see three tabs at the top:
- [Kernel](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#kernel-tab)
- [Preseed](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#preseed-tab)
- [Boot](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#boot-tab)

 1. Click on the [Boot tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#boot-tab).
    
    ![image](https://user-images.githubusercontent.com/19394936/163699677-6c27b66e-139f-4ae6-b575-2d9eadcf6e16.png)

    Notice that two files are visible in the left pane.
    - `/boot/grub/grub.cfg`
    - `/boot/grub/loopback.cfg`

 2. Click on the "Show all files" toggle button at the top left of the header bar. (It is the 1st button to the right of the <kbd>❬Back</kbd> button).
 
    ![image](https://user-images.githubusercontent.com/19394936/163699263-4289be76-c29d-4756-b545-155c452c9d1f.png)

 3. This will expand all of the files in the `/boot/grub` and the `/isolinux` folders.

 4. In the left pane, scroll all the way down and select `/isolinux/menuentries.cfg`.

    ![image](https://user-images.githubusercontent.com/19394936/163699329-6497777d-dcfd-4fc3-96e4-f63cb022c8d9.png)

 5. In the right pane, at the end of the first line, `# Define menu entries`, type some text, and then delete the text you typed.

    By editing this file you will let Cubic know that `/isolinux/menuentries.cfg` is an important file.

 6. Once again, click on the "Show all files" toggle button in the header bar.

    ![image](https://user-images.githubusercontent.com/19394936/163699410-52620abd-05fa-4d5d-a9c2-f2fabe5579ca.png)

 7. This will hide most of the files in the left pane. However, the three files will remain visible.
     - `/boot/grub/grub.cfg`
     - `/boot/grub/loopback.cfg`
     - `/isolinux/menuentries.cfg`

    ![image](https://user-images.githubusercontent.com/19394936/163699849-4e60e895-0bcb-4b44-a83f-66864fd5e7fd.png)

 8. Now click the <kbd>❬Back</kbd> button in the header bar to return to the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page).

 9. From the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page), click the <kbd>Next❭</kbd> button in the header bar to show the [Options page](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page) again.

      This will cause Cubic to automatically update all three files (`/boot/grub/grub.cfg`, `/boot/grub/loopback.cfg`, and `/isolinux/menuentries.cfg`).

10. Finally, click the <kbd>Next❭</kbd> button and generate your customized ISO.

     ![image](https://user-images.githubusercontent.com/19394936/163699499-f1d1ffb6-8562-45c7-ae66-112586d456d4.png)

The next time you open this project in Cubic (if you want to make additional customizations), _you will not  need to repeat these steps_, since Cubic will remember that `/isolinux/menuentries.cfg` is an important file for your OS / ISO.
