### ISSUE TITLE
How to customize the Plymouth Splash Screen?

### ISSUE THREAD

**Issue by real-nickel** [PJ-Singh-001/Cubic#5]
Hi, 
The solutions on ticket #699669 on the other site did not work.
Can you help me out?

**Comment by PJ-Singh-001** [comment]
You're customizing Xubuntu 20.04 ?

**Comment by PJ-Singh-001** [comment]
One more question...

Your question says "Ubiquity" and "Splash Screen".

Are you asking about:
(a) The *slideshow* in the ubiquity installer
(b) The Plymouth *splash screen* you see when the system boots up
?

**Comment by real-nickel** [comment]
Yes, I'm using xUbuntu 20.04, how id you know?
I am also talking about the slideshow in ubiquity and the Plymouth splash screen.

**Comment by PJ-Singh-001** [comment]
Deduction:
- In comment # 5 of the [question you referenced](https://answers.launchpad.net/cubic/+question/699669), you mentioned you were using Xubunu.
- In comment # 1 of the [same question](https://answers.launchpad.net/cubic/+question/699669), I used Ubuntu 20.04 as an example, and you did not refute that.

**Comment by PJ-Singh-001** [comment]
### How to customize the Boot Splash Screen (Plymouth)

I used xubuntu-20.04.1-desktop-amd64.iso for this test.

I chose ["Colorful Plymouth Theme"](https://www.gnome-look.org/p/1586875) for this test.

 1. On Cubic's [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), notice that you do not have any kernels installed.

        ls -la /boot

    The output will look like this (the following sim links are broken):

        initrd.img -> initrd.img-5.4.0-42-generic
        initrd.img.old -> initrd.img-5.4.0-42-generic

        vmlinuz -> vmlinuz-5.4.0-42-generic
        vmlinuz.old -> vmlinuz-5.4.0-42-generic


 2. Install the latest available kernel.

        apt update
        apt --yes install --reinstall linux-headers-generic
        apt --yes install --reinstall linux-image-generic

 3. Notice that you now have a kernel installed.

        ls -la /boot

    The output will look like this:

        initrd.img -> initrd.img-5.4.0-91-generic
        initrd.img-5.4.0-91-generic
        initrd.img.old -> initrd.img-5.4.0-91-generic

        vmlinuz -> vmlinuz-5.4.0-91-generic
        vmlinuz-5.4.0-91-generic
        vmlinuz.old -> vmlinuz-5.4.0-91-generic

 4. Notice that the current Plymouth theme being used is `xubuntu-logo.plymouth`.

        update-alternatives --display default.plymouth

    The output will look like this:

        default.plymouth - auto mode
          link best version is /usr/share/plymouth/themes/xubuntu-logo/xubuntu-logo.plymouth
          link currently points to /usr/share/plymouth/themes/xubuntu-logo/xubuntu-logo.plymouth
          link default.plymouth is /usr/share/plymouth/themes/default.plymouth
        /usr/share/plymouth/themes/xubuntu-logo/xubuntu-logo.plymouth - priority 150

 5. On your host machine, download your Plymouth theme and extract it.

 6. On Cubic's [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), `cd` to the Plymouth themes folder, and create a theme folder.

        cd /usr/share/plymouth/themes
        mkdir colorful
        cd colorful

 7. Using a file manager, select all of the files in the extracted folder on your host machine, and [drag and drop the files onto Cubic's Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Copy-Page) to copy the files to the current directory (`/usr/share/plymouth/themes/colorful`).

 8. Set your new Plymouth theme as the default theme using a higher priority. This command is separated into five lines for readability. The fourth line should specify your new Plymouth theme directory and the `*.plymouth` file inside of it, and the last line is the theme's priority.

        update-alternatives --install \
        "/usr/share/plymouth/themes/default.plymouth" \
        "default.plymouth" \
        "/usr/share/plymouth/themes/colorful/colorful.plymouth" \
        160

    The output will look like this:

        update-alternatives: using /usr/share/plymouth/themes/colorful/colorful.plymouth to provide /usr/share/plymouth/themes/default.plymouth (default.plymouth) in auto mode

 9. Notice that the default Plymouth theme has been changed. In this example, it is now `colorful/colorful.plymouth`.

        update-alternatives --display default.plymouth

    The output will look like this (the new theme will be listed as ""best version):

        default.plymouth - auto mode
          link best version is /usr/share/plymouth/themes/colorful/colorful.plymouth
          link currently points to /usr/share/plymouth/themes/colorful/colorful.plymouth
          link default.plymouth is /usr/share/plymouth/themes/default.plymouth
        /usr/share/plymouth/themes/colorful/colorful.plymouth - priority 160
        /usr/share/plymouth/themes/xubuntu-logo/xubuntu-logo.plymouth - priority 150

10. Finally, update the `initramfs` image for all installed kernels to use the new Plymouth theme.

        update-initramfs -uk all

    The output will look like this (the error and warning are normal):

        update-initramfs: Generating /boot/initrd.img-5.4.0-91-generic
        cryptsetup: ERROR: Couldn't resolve device tmpfs
        cryptsetup: WARNING: Couldn't determine root device

11. In Cubic, navigate to the [Options page](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page). Click on the [Kernel tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#kernel-tab), and make sure one of the kernels you had installed on the Terminal page is selected. Do not select the original disk's bootstrap kernel, because it will not have been updated.

    ![Screenshot from 2021-12-26 13-21-34](https://user-images.githubusercontent.com/19394936/147416803-2d8138f0-ebc9-4f32-9766-1bc82ceb3694.png)


12. Click the [Generate button](https://github.com/PJ-Singh-001/Cubic/wiki/Generate-Page), and test your customized ISO on the [Finish page](https://github.com/PJ-Singh-001/Cubic/wiki/Finish-Page).

    ![Screenshot from 2021-12-26 13-01-48](https://user-images.githubusercontent.com/19394936/147416649-a8505386-389f-45b7-8f2a-ebc6633e3129.png)

**Comment by PJ-Singh-001** [comment]
Regarding the Ubiquity Slide Show, please ask a separate question, since that is unrelated to the Plymouth Splash Screen.

**Comment by real-nickel** [comment]
Thanks for the help but I'm not home with my Linux computers so I can't try until a few days later

**Comment by real-nickel** [comment]
Ok so far it works but I haven't managed to install it on a VM yet (Cubic only really lets you test it live as not much disk space)
So thanks for the help.

P.S I may have fixed the Ubiquity issue myself but haven't tried it

**Comment by real-nickel** [comment]
Ok the splash screen worked but not ubiquity so I will make a new issue.

**Comment by ImGGAAVVIINN** [comment]
I have a problem which is my Plymouth theme does not work on start os but it applies when the os is shutting down

**Comment by TK1987** [comment]
With Ubuntu 23.10 this does not seem to work anymore.

`update-initramfs` seems to do nothing at all with the parameters `-uk all`. Only if you specify the kernel version with `-uk 6.5.0-9-generic`, the expected output is generated.
However, the Plymouth theme is still the old one when booting the ISO.
