### ISSUE TITLE
Adding default Bookmark and some addons,extensions inside firefox/chrome

### ISSUE THREAD

**Issue by vaisakhrr** [PJ-Singh-001/Cubic#55]
I wish to  customize ubuntu 22.04 using cubic .I created a default user "test-user".After that How can I do
1)add some bookmarks inside the bookmarks toolbar of firefox
2)add some Extensions inside chrome
3)add/import some certificates inside firefox/chrome
the above added bookmarks,extensions,cerificates must be preinstalled inside my default user "test-user"

**Comment by PJ-Singh-001** [comment]
- I can answer question # 1.
- For question # 2, I do not use Chrome, and I have not been able to successfully add an extension in Firefox. However, I'm sure there must be a way to do this.
- For question # 3, I have not done this, so I do not know how to do it. Again, I'm sure there must be a way to do this.
- May be the information below will help you with # 2 and # 3. If so, please share your solution(s).

**Question # 1**

If you want configurations and files available to all new users, you can place them inside the `/etc/skel` folder.
This folder acts as a template or "skeleton" for the home directory of new users.

If you actually created "test-user" while customizing your ISO on [Cubic's Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), then you can place your configuration files in the appropriate sub-directory (or directories) under `/home/test-user`.

Unfortunately, I have not had success configuring Firefox using the "individual" configuration files. This is because firefox creates a random key or code for each instance of Firefox on a per user basis.

See the output of the following command; notice the directory `<??????>.default-release` has a random name.

    ls -la .mozilla/firefox/*.default-release/prefs.js

(If you figure out how to configure Firefox by using the user's home directory or the `/etc/skel` directory, please let me know).

However, configuring Firefox globally worked for me...

If you want to configure Firefox globally (for all users), you could place your files under `/etc/firefox`. I believe the configuration file should be named `syspref.js`. In this file, be sure to use `"pref(<key>", "<value>")` `instead of user_pref()`. In my experience, `user_pref()` is for "individual" Firefox users and does not work when placed inside `/etc/firefox/syspref.js`. As an example, you may want to include the preference:

    pref("browser.toolbars.bookmarks.visibility", "always");

(Allowed values for this example preference are "newtab", "always", or "never").

You can always look inside the Firefox configuration on your host machine to find out what the keys and values should be:

    cat ~/.mozilla/firefox/*.default-release/prefs.js

Lastly, keep in mind these configurations work for the `*.deb` version of Firefox, and probably won't work for the snap version. Unfortunately, there is no way to install or (individually) uninstall snaps in Cubic.

**Comment by vaisakhrr** [comment]
At first thanks for your guidance...

I tried the following and its working, but I don't know it's the proper way or not. If there is any issue kindly correct me.

1.  **Adding Bookmarks in Firefox in Ubuntu 22.04 (Using the Firefox Snap Version)**

      1. Make a directory structure as given below in Cubic.

              mkdir -p /etc/skel/snap/firefox/common/.mozilla/firefox/

      2. Now copy the `profiles.ini` file from the host machine's Firefox folder. (Note that the host machine must be running Ubuntu 22.04. Also we must set needed bookmarks inside the host machine's Firefox). The  host machine's `profiles.ini` file location is in `/home/user name/snap/firefox/common/.mozilla/firefox/`.

      5. Open `profiles.ini` file and check the value `path=some_value.default`.

      6. Create a folder with the same name as the above path value (i.e. `some_value.default` inside `/etc/skel/snap/firefox/common/.mozilla /firefox/`).

      7. Go inside the newly created folder (i.e. `some_value.default`).

      8. Now copy `places.sqlite` file and `bookmarkbackups` folder from inside `some_value.default` folder.

 2. **Adding/Importing Digital Certificate Inside Firefox**

      1. First import the digital certificate into Firefox on the host machine using the graphical method (i.e. Firefox > Settings > Privacy & Security > Certificates > View Certificate > Import).

      2. Now copy the `cert9.db` and `key.db` files into `/etc/skel/snap/firefox/common/.mozilla/firefox/some_value.default/`.

After all these steps, create the ISO using Cubic.

After installation of the customized OS, the new user will automatically get the Firefox bookmarks and digital certificates.

**Comment by PJ-Singh-001** [comment]
Thank you for sharing and for posting these very detailed instructions! (I have edited and formatted your post, so it will be easier for others for follow).
