### ISSUE TITLE
(cubic:31): dconf-WARNING **: 15:34:52.160: failed to commit changes to dconf: Cannot autolaunch D-Bus without X11 $DISPLAY

### ISSUE THREAD

**Issue by karawitan** [PJ-Singh-001/Cubic#69]
Hello,

   while running cubic via docker, when I open the dialog box to "Select a project directory",
I get the following message on the console:

(cubic:31): dconf-WARNING **: 15:34:52.160: failed to commit changes to dconf: Cannot autolaunch D-Bus without X11 $DISPLAY

Is this message important ? what does it mean ?

**Comment by PJ-Singh-001** [comment]
Are you able to progress past the 1st page in Cubic, despite this message?

It seems that running Cubic in Docker is not easy.

[Here is another question on this topic](https://github.com/PJ-Singh-001/Cubic/issues/66), but there was no resolution.

Cubic is a GUI application so it obviously needs as display server (Wayland, or X).

Also, you must have services running. Specifically, dbus and systemd are needed.

Please note, the Virtual environment in Cubic is itself a container. This is designed to isolate your host system from changes you make in the virtual environment. By running Cubic in Docker, you are effectively trying to run a container within a container.

Is there a reason you are running Cubic in Docker, rather than directly on your host machine?

**Comment by karawitan** [comment]
Hi !
  I choose Docker so that I won't hit package dependencies issues.
I did not manage to install cubic on focal. Is there a way to recompile for focal ?

I had hit the following when installing on focal

```
 systemd-container : Depends: systemd (= 245.4-4ubuntu3.17) but 246.6-1ubuntu1.7 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by PJ-Singh-001** [comment]
Cubic installs and runs fine on all versions of Ubuntu from 18.04.5 Bionic Beaver and above.

Therefore Cubic will install on Ubuntu 20.04 Focal Fossa.

If you install Cubic using `sudo apt install --no-install-recommends cubic`, [as shown here](https://github.com/PJ-Singh-001/Cubic/wiki/Install-Cubic), you will only install the minimum required dependencies, so you will not be installing any unnecessary packages.

Cubic only uses official Ubuntu packages from the *main*, *universe*, and *security* repositories. Any version of required packages greater than or equal to the ones supplied with Ubuntu 18.04.5 will work with Cubic.

Unless you've installed third party repositories that provide unofficial versions of the standard Ubuntu packages, you will be fine.

On a fresh install of Ubuntu 20.04.4, 36 packages are installed, including Cubic itself, and this is less then 77 MB of files:

    binwalk
    cubic
    ipxe-qemu
    ipxe-qemu-256k-compat-efi-roms
    isolinux
    libburn4
    libcacard0
    libdaxctl1
    libdecor-0-0
    libfdt1
    libibverbs1
    libisoburn1
    libisofs6
    libjte2
    libndctl6
    libpmem1
    librdmacm1
    libsdl2-2.0-0
    libslirp0
    libspice-server1
    liburing2
    libusbredirparser1
    libvirglrenderer1
    python3-binwalk
    python3-magic
    python3-packaging
    python3-psutil
    python3-pydbus
    python3-pyinotify
    qemu-system-common
    qemu-system-data
    qemu-system-gui
    qemu-system-x86
    seabios
    systemd-container
    xorriso

A benefit of installing Cubic on your host machine is that you will be able to use the Emulator to test you customized ISO directly from Cubic. You can not use the Emulator if you are running in a virtual machine or container (even if you could get it to work).

**Comment by karawitan** [comment]
ok thanks for this feedback :)
