### ISSUE TITLE
Cubic fails to install on Ubuntu 22.04 due to dependency issue with systemd-container

### ISSUE THREAD

**Issue by matta10x** [PJ-Singh-001/Cubic#70]
**Describe the bug**

apt-get install cubic results in the following error:

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 cubic : Depends: systemd-container (>= 237)
E: Unable to correct problems, you have held broken packages.

**To Reproduce**

sudo apt install cubic

**Expected behavior**

Cubic installs.

**OS Information (please complete the following information):**
 - OS/Distro Name: Ubuntu
 - OS Version 22.04

**Comment by PJ-Singh-001** [comment]
Cubic requires any version of `systemd-container` greater than or equal to 237.

As you can [see here](https://packages.ubuntu.com/jammy/systemd-container), Ubuntu 22.04 ships with `systemd-container` version 249.1. Therefore Cubic will install on Ubuntu 22.04 Jammy Jellyfish.

Most likely, your system has an older version of `systemd-container` which may have been installed by a third-party (non-official) repository you are using.

Remove the unofficial repository that is delivering the incorrect version of `systemd-container` to your system. Then install the correct version of `systemd-container` and related dependencies. Warning, lots of packages in Ubuntu require `systemd-container`, so you may render your system ubootable as you try to fix your system.

[Here](https://github.com/PJ-Singh-001/Cubic/issues/53) is a similar problem someone else had; this user had accidentally enabled the “proposed” repository.

Finding the issue and fixing your Ubuntu installation may require a lot of work. Make sure you make a backup of your important data, because you could render your system unbootable.

A simpler approach might be to reinstall Ubuntu. (Of course, make sure you have a backup of your data before reinstalling).

**Comment by matta10x** [comment]
Thanks for the response, but systemd-container itself wouldn't install, despite having all its correct dependencies already installed.  From reviewing the similar issue you linked, I didn't have the proposed repo enabled either, so that wasn't the issue.  I also didn't have any other PPAs or 3rd party repos that looked to be providing their own systemd-container.  After several hours of investigating with no progress, I just reinstalled and was able to install systemd-container without issue.  This computer had gone through many upgrades from Ubuntu release to Ubuntu release, however, so maybe there was something from that historical upgrade process that was causing the problem.
