### ISSUE TITLE
Can't encrypt during install on 20.04

### ISSUE THREAD

**Issue by hoodstained** [PJ-Singh-001/Cubic#79]
First thing first, thanks for making Cubic it's really great

**Describe the bug**

Whenever I try to encrypt the disk during the Ubuntu install I get some weird graphical bugs ( window borders vanish ) and despite being able to reach the last step, I can't type anything to create an account and all that jazz. 
This bug also happens when installing Ubuntu vanilla while being connected to the internet and opting to install upgrades during the installation.
I've tried it with and without any internet connection, with and without having upgraded ubuntu in Cubic

**To Reproduce**

Try to encrypt during installation of a custom iso

**Expected behavior**

Being able to create an account at the end of the ubuntu installation.

**OS Information (please complete the following information):**
 - OS/Distro Name: Ubuntu amd64
 - OS Version Ubuntu 20.04

**Cubic Information (please complete the following information):**
 - Cubic Version: Cubic version 2022.06.72
 - ISO Customizing: [e.g. ubuntu-20.04-desktop-amd64.iso]
 - Download Link:  from canonical's website

**Cubic Log:**

 Cut and paste the log after running `cubic` from the command line

**Screenshots**

![IMG_20220706_093819](https://user-images.githubusercontent.com/104659134/177496873-c7383bb7-5e39-448c-b140-308d585b1c5b.jpg)

![IMG_20220706_093835](https://user-images.githubusercontent.com/104659134/177496905-aa3c15cc-bb9b-4658-bfbd-8771be4d8c06.jpg)
![IMG_20220706_093848](https://user-images.githubusercontent.com/104659134/177496937-b65eaefb-9241-4aac-a994-46c9072642e8.jpg)
![IMG_20220706_093906](https://user-images.githubusercontent.com/104659134/177496968-607994be-d335-4a3f-ad98-cf08e35d80e4.jpg)
![IMG_20220706_093931](https://user-images.githubusercontent.com/104659134/177497204-cd84351d-cf73-43c3-b5b4-c63f761afffb.jpg)

**Comment by PJ-Singh-001** [comment]
I'll try this out on a virtual machine, and see if I get similar behavior.
Please be patient, since there are other issues posted here, that also require a lot of investigation, like your issue.

**Comment by hoodstained** [comment]
> I'll try this out on a virtual machine, and see if I get similar behavior. Please be patient, since there are other issues posted here, that also require a lot of investigation, like your issue.

yeah, I figure you're already busy enough as it is.
I've figured another way out to a similar result. Just thought you might want this kind of issues to pointed out to you, so that you can work on it some day.

Good luck with the project, and thanks again for making it.

**Comment by Augusto7743** [comment]
What is the type of compression used in customized ISO ?
What is the filesystem ? ext ? btrfs ?

**Comment by hoodstained** [comment]
> What is the type of compression used in customized ISO ? What is the filesystem ? ext ? btrfs ?

gzip compression, the installation is done with LVM so I believe it is ext4 by default.

**Comment by Augusto7743** [comment]
Try test using VirtualBox.
You have tested using another filesystems ? BTRFS ?

**Comment by PJ-Singh-001** [comment]
I tested a customized 20.04 ISO in Virtual Box.

I did not experience this issue during installation.
I also had no issues decrypting the disk and using the installed OS.

Virtual Machine Specs:
- Base Memory 5120 MB
- Processor 1 CPU
- Enable PAE/NX
- Enable Nested VT-x/AMD-V
- Enable Nested Paging
- 16MB Video Memory
- Graphics Controller VMSVGA
- Enable 2D Acceleration
- 30 GB Virtual Disk

Host Computer Specs:
- 16 GB Memory
- Intel i7 with 8 cores
- NVIDIA GeForce MX150 Graphics
- SSD

<img src="https://user-images.githubusercontent.com/19394936/178169213-2f4104c3-70dc-4722-b0c2-323bdd2be73c.png" width="400"/>

Were you installing to hardware or a Virtual Machine?
What are the specs of your host computer?
What are the specs of your Virtual Machine (if installing to a VM)?

It's obvious your window manager has crashed.
This could be caused by some packages or customizatons you've done.
It could be caused by insufficient resources (Memory, CPU, Graphics).
Do you have a hard-disk or SSD?
Are you using X11 or Wayland?

I can see you have chosen the "Install Ubuntu" option.
Try selecting the "Try Ubuntu" option.
Then open System Monitor to watch your resources during installation.
Keep an eye on the memory and swap space usage.

If you encounter this issue, you may be able to restart the window manager, using this key combination:

<kbd>Alt</kbd>-<kbd>F2</kbd>, Type <kbd>r</kbd>, Press <kbd>Enter</kbd>

<img src="https://user-images.githubusercontent.com/19394936/178171127-a2615bd7-a9ce-4659-acd0-d293444c8f76.png" width="400"/>

**Comment by PJ-Singh-001** [comment]
I haven't heard back from you, so I'll assume the above work-around solved your problem, or you figured out another solution (perhaps a hardware related fix).
