### ISSUE TITLE
How to create a custom live only Ubuntu ISO to be used on a USB stick and with support for data persistence?

### ISSUE THREAD

**Issue by sguazt** [PJ-Singh-001/Cubic#8]
**Describe the question**

Hello, 
Firstly, thanks a lot for sharing your Cubic project!

I would like to create a live Xubuntu ISO with the following features:
- The live OS must not show the Welcome screen (that is, the one with the "Try Xubuntu" and "Install Xubuntu" buttons).
- The live OS must not have the "xubuntu" user (i.e., the user created in a traditional Xubuntu Live OS) or, if not possible, that user must log into the system only with a password (no auto-login).
- The live OS will have at least two predefined users, say "powuser" and "stduser" (both protected by predefined passwords), but only one of them ("powuser") will have administration capabilities (that is, can use "sudo").
- The live OS will have preinstalled extra packages (for instance, gcc and make) and preconfigured settings (including locale "en_US" and optionally "it_IT", keyboard layout "it" and timezone "Europe/Rome").
- The ISO image will be written to and run only from a USB stick, and any changes done while using the live image should persist across reboots (I am still not sure whether to use a persistent overlay or a separate area).

I was wondering if it is possible to use Cubic to create an ISO image like the above.
Thank you for your help and time.

**What you have tried**

I tried to customize the system from the Cubic Terminal page, but something not worked and something else I didn't know how to do it:
- Disable Welcome screen: don't know how to do it
- Remove (or disable) the "xubuntu" user: failed.
I didn't know how to remove the "xubuntu" user, so I tried to set a password for such user.
Similarly to the steps suggested in a [previously asked question](https://answers.launchpad.net/cubic/+question/692073), I removed the `15autologin` and `25adduser` files, than I executed `adduser xubuntu` (and specified a password for that user) and finally I run `update-initramfs -u`.
However, the live OS logged in with the "xubuntu" user without asking for any password.
If I log out from the system, I can see the login screen; but there is no password  textfield for the "xubuntu" user.
- Add predefined users: partially failed.
In the Cubic Terminal page, I added the "xubuntu" user (see above) and the "powuser" user.
Also, I added "powuser" (but not "xubuntu") to the "sudo" group.
However, in the Live OS, both "xubuntu" and "powuser" were able to run a command through "sudo" (only "powuser" can do it).
- Installation of extra packages: succeeded.
Installed extra packages from the Cubic Terminal page with `apt-get install ...`.
- Configuration of the system (locale, keyboard, timezone, ...): don't know how to do it.
I found similar questions in launchpad and the answer was to use preseeds.
However, if I understand correctly, preseeds cab be used only for the installed system.
- Data persistence: not yet done.
I think this is a bit unrelated to Cubic. Anyway, any suggestion is welcome ;-)
I am considering to use tools like [mkusb](https://help.ubuntu.com/community/mkusb) or [livecd-iso-to-disk](https://docs.fedoraproject.org/en-US/quick-docs/creating-and-using-a-live-installation-image/index.html]. I would like that data written by a user cannot be accessed by other users.

**Expected behavior**

n/a

**OS Information (please complete the following information):**
 - OS/Distro Name: Xubuntu
 - OS Version Xubuntu 21.10

**Cubic Information (please complete the following information):**
 - Cubic Version: 2021.12.68
 - ISO Customizing: xubuntu-21.10-desktop-amd64.iso
 - Download Link:  https://cdimage.ubuntu.com/xubuntu/releases/21.10/release/xubuntu-21.10-desktop-amd64.iso

**Screenshots**

n/a

**Comment by PJ-Singh-001** [comment]
sguazt,

Since you don't want the Welcome screen (with the "Try Xubuntu" and "Install Xubuntu" buttons), do you still want the installer available, in order to allow a user to install the OS, or do you intend to never use this ISO to install the OS?

**Comment by sguazt** [comment]
Hi,
I will never use the ISO to install the OS.

**Comment by PJ-Singh-001** [comment]
- _The live OS must not show the Welcome screen (that is, the one with the "Try Xubuntu" and "Install Xubuntu" buttons)._

    Simply remove Ubiquity, since you will not be using the customized OS to install Xubuntu.

       apt autoremove ubiquity ubiquity-frontend-gtk

- _The live OS must not have the "xubuntu" user (i.e., the user created in a traditional Xubuntu Live OS) or, if not possible, that user must log into the system only with a password (no auto-login)._

- _The live OS will have at least two predefined users, say "powuser" and "stduser" (both protected by predefined passwords), but only one of them ("powuser") will have administration capabilities (that is, can use "sudo")._

    Create the standard user.

      adduser stduser

      Adding user `stduser' ...
      Adding new group `stduser' (1000) ...
      Adding new user `stduser' (1000) with group `stduser' ...
      Creating home directory `/home/stduser' ...
      Copying files from `/etc/skel' ...
      New password:
      Retype new password:
      passwd: password updated successfully
      Changing the user information for stduser
      Enter the new value, or press ENTER for the default
              Full Name []: Standard User
              Room Number []:
              Work Phone []:
              Home Phone []:
              Other []:
      Is the information correct? [Y/n] Y

    Create the power user.

      adduser powuser

      Adding user `powuser' ...
      Adding new group `powuser' (1001) ...
      Adding new user `powuser' (1001) with group `powuser' ...
      Creating home directory `/home/powuser' ...
      Copying files from `/etc/skel' ...
      New password:
      Retype new password:
      passwd: password updated successfully
      Changing the user information for powuser
      Enter the new value, or press ENTER for the default
              Full Name []: Power User
              Room Number []:
              Work Phone []:
              Home Phone []:
              Other []:
      Is the information correct? [Y/n] Y

    Add the power user to the `sudo` group.

      usermod -a -G sudo powuser

- _The live OS will have preinstalled extra packages (for instance, `gcc` and `make`)._

    Install the `apt-add-repository` command.

      apt update
      apt install software-properties-common

    Add the repositories or PPAs for your packages, as needed.

      apt-add-repository universe

    Install the packages you want.

      apt install gcc make

- _The live OS will have preconfigured settings (including locale "en_US" and optionally "it_IT", keyboard layout "it" and timezone "Europe/Rome")._

    Install English language packs.

      apt install language-pack-en language-pack-en-base

    Install Italian language packs.

      apt install language-pack-it language-pack-it-base

    Select your locale(s).

      dpkg-reconfigure locales

    In the text based dialog, use the following to navigate.
    - Use <kbd>Tab</kbd> and <kbd>Shift</kbd>+<kbd>Tab</kbd> to navigate to different sections.
    - Use <kbd>Space</kbd> bar to select items.
    - Use the <kbd>↑</kbd> and <kbd>↓</kbd> keys to scroll through the list.
    - Use <kbd>Enter</kbd> to select the `<Ok>` or `<Cancel>`options, after they have been highlighted.

    Press <kbd>Space</kbd> bar to select `en_GB.UTF-8 UTF-8` for English / Great Britain.

      [ ] en_GB ISO-8859-1
      [ ] en_GB.ISO-8859-15 ISO-8859-15
      [*] en_GB.UTF-8 UTF-8

    Also, press <kbd>Space</kbd> bar to select `it_IT.UTF-8 UTF-8` for Italian / Italy.

      [ ] it_IT ISO-8859-1
      [*] it_IT.UTF-8 UTF-8
      [ ] it_IT@euro ISO-8859-15

    Use <kbd>Tab</kbd> to highlight `<Ok>`, and then press <kbd>Enter</kbd>.

    On the next page, scroll through the list and highlight `it_IT.UTF-8`.
    Use <kbd>Tab</kbd> to highlight `<Ok>`, and then press <kbd>Enter</kbd>.

    The locales will be generated.

      .
      .
      en_GB.UTF-8... done
      .
      .
      it_IT.UTF-8... done
      .
      .

    The `LANG` variable will be set to `it_IT.UTF-8`.

      cat /etc/default/locale

    Set the time zone.

      ls -l /etc/localtime
      ln -frs /usr/share/zoneinfo/Europe/Rome /etc/localtime
      ls -l /etc/localtime

Finally, generate your custom ISO and test.

![Screenshot from 2022-01-11 19-44-23](https://user-images.githubusercontent.com/19394936/149044212-9961e774-f804-4352-8c65-7c498d3b361e.png)

**Comment by PJ-Singh-001** [comment]
I still owe you a solution to your last question:

- _The ISO image will be written to and run only from a USB stick, and any changes done while using the live image should persist across reboots (I am still not sure whether to use a persistent overlay or a separate area)._

In the mean time, see if the above steps work for you.

**Comment by sguazt** [comment]
Many many thanks! It worked like a charm.

After the locale (re)configuration, I also ran:
```
dpkg-reconfigure keyboard-configuration
```
to change the default keyboard layout from English to Italian.

Specifically:
1. In the first screen, I selected `Generic 105-key PC (intl.)` as the model of the keyboard
2. In the second screen, I selected `Italian` as the layout
3. In the third screen, I selected `Italian` again as the specific layout
4. In the fourth screen, I select `The default for the keyboard layout` as the key to function as AltGr
5. In the fifth screen, I selected `No compose key` as the compose key
6. Finally, in the sixth screen, I selected `No` as the answer to the question *Use Control+Alt+Backspace to terminate the X server?*

Thank you.

**Comment by PJ-Singh-001** [comment]
- _The ISO image will be written to and run only from a USB stick, and any changes done while using the live image should persist across reboots (I am still not sure whether to use a persistent overlay or a separate area)._

### Edit boot parameters

 1. In Cubic, navigate to the [Options page](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page).
 2. Click on the [Boot tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#boot-tab) in the header bar.

### UEFI boot

 3. Click in the file `boot/grub/grub.cfg` † in the left pane.
 4. In the right pane, in the `"Try Xubuntu without installing"` section, add `persistent` just before `quiet splash`. (You may want to make similar changes to the other boot entries).
 5. Optionally, remove `file=/cdrom/preseed/xubuntu.seed` since you are not using Ubiquity. (You may want to make similar changes to the other boot entries).
 6. You might also want to change the name of the menu entry from `"Try Xubuntu without installing"` to something like `"Xubuntu (Persistent)"`. (You may want to make similar changes to the other boot entries).

### Legacy BIOS boot

 7. Click in the file `isolinux/txt.cfg` † in the left pane.
 8. In the right pane, in the `^Try Xubuntu without installing` section, add `persistent` just before `quiet splash`. (You may want to make similar changes to the other boot entries).
 9. Optionally, remove `file=/cdrom/preseed/xubuntu.seed` since you are not using Ubiquity. (You may want to make similar changes to the other boot entries).
10. You might also want to change the name of the menu entry from `^Try Xubuntu without installing` to something like `^Xubuntu (Persistent)`. (You may want to make similar changes to the other boot entries).

† Note: `boot/grub/grub.cfg` is used for UEFI boot in Ubuntu 20.04. `isolinux/txt.cfg` is used for legacy BIOS boot in Ubuntu 20.04. I'm not sure what `boot/grub/loopback.cfg` is used for, so if you know or figure it out, please let me know.

![Screenshot from 2022-01-16 19-29-34](https://user-images.githubusercontent.com/19394936/149684686-fb503af9-858c-4975-8571-1590b0e6390d.png)

### Burn and use the ISO

11. Create a bootable USB using a program like [Startup Disk Creator](https://packages.ubuntu.com/hirsute/usb-creator-gtk).
12. The first time you boot into the USB, the system will automatically create a new writable partition on the disk named `writable`. This will store your changes while you use the Live ISO.

![Screenshot from 2022-01-16 19-26-23](https://user-images.githubusercontent.com/19394936/149685567-4cacdcf2-7480-47d6-a499-b89d0022dc47.png)


### Caution

Be **very** cautious about doing system updates/upgrades and making big changes to the Live USB. Eventually, the USB will become unusable (speaking from experience). It is best to install all of the updates and software you need in Cubic, and avoid doing too many updates or installing too many new packages to the persistent Live USB.

**Comment by PJ-Singh-001** [comment]
### Alternative approach to remove "Try Xubuntu" / "Install Xubuntu" welcome dialog

In [the previous comment](https://github.com/PJ-Singh-001/Cubic/issues/8#issuecomment-1010516801), I suggested removing the Ubiquity package in order to get rid of the "Try Xubuntu" / "Install Xubuntu" welcome dialog.

Alternatively, if you do not want to remove Ubiquity, you can disable the Ubiquity service.

On [Cubic's Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), execute the following:

    rm /etc/systemd/system/graphical.target.wants/ubiquity.service

This will log you directly into the Live environment. The "Install Xubuntu" icon will remain on the desktop and the application menu. You will still be able to install Xubuntu from this Live environment by clicking on one of these icons.

**Comment by PJ-Singh-001** [comment]
I am closing this issue with the comments above.

If the approach I suggested for creating a persistent Live USB does not work, feel free to reopen this issue.

**Comment by sguazt** [comment]
Thank you so much!  :1st_place_medal: :+1: 

Concerning the GRUB's `/boot/grub/loopback.cfg` file, it is used by GRUB2 to boot from an ISO image file stored on some storage medium accessible at boot time. However, I never used it.
Here are some interesting references:
- https://www.gnu.org/software/grub/manual/grub/html_node/Loopback-booting.html
- https://help.ubuntu.com/community/Grub2/ISOBoot/Examples
- https://wiki.archlinux.org/title/Multiboot_USB_drive#Workstation_live_medium
