### ISSUE TITLE
Additional storage space for live system?

### ISSUE THREAD

**Issue by phillips321** [PJ-Singh-001/Cubic#82]
Hi there,

First off many thanks for Cubic, it's a great bit of work.

I use it to create a custom ISO, however how can i configure the running live image to have more temporary storage? I assume this is in RAM? Here i only have 2.2Gb of storage but our requirements sometimes need the running live image to use more for a short period of time.
```
└─# df -h
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           443M  1.1M  442M   1% /run
/dev/sda1       3.2G  3.2G     0 100% /cdrom
/cow            2.2G  1.3G  962M  57% /
tmpfs           2.2G     0  2.2G   0% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           2.2G     0  2.2G   0% /tmp
tmpfs           443M   76K  443M   1% /run/user/1000
```

What factors contribute to the size of /cow ?

Many thanks

**Comment by PJ-Singh-001** [comment]
Let's see how much available memory Cubic thinks you have...

Run Cubic using the command...

    cubic --verbose

Then generate a custom ISO.

When you get to the [Finish page](https://github.com/PJ-Singh-001/Cubic/wiki/Finish-Page), copy the log output from the terminal, and paste it here.

Only copy the portion of the log that starts with the heading (in yellow)...

    Navigate from generate page to finish page on finish action

**Comment by phillips321** [comment]
This comment can now be closed. Ive figured out that the cubic test virtual machine only has 4Gb of RAM (thus ~2Gb is used for /cow). However I can boot this ISO in VMware/virtual box and allocate more memory. If cubic offered an option to configure the allocated memory to the test VM it would save me having to test the ISO in a different virtualisation platform. Many thanks

**Comment by PJ-Singh-001** [comment]
Cubic requires at least 1.5GB available memory in order to run the emulator.

Available memory is memory that is _not currently being used_. What this means is that even if memory has been allocated ("earmarked") for other processes, as long as that memory is not being used by the other processes, Cubic will let you run the emulator.

In your situation, if you have 4GB of RAM, and 2 GB is being used, there must at least an additional 0.5 GB that is being used by other process or by the OS. If greater than 2.5 GB are being used, this will leave you with less than the required 1.5 GB.

1.5 GB is a low threshold to run the emulator **and** still maintain a responsive OS. You might be able to get away with allocating more memory in your virtual machine because you do not have Cubic running and consuming resources, the virtual machine may be taking advantage of swap space (Cubic does not count swap space in the 1.5 GB calculation, or your virtual machine configuration tool may not care if you use all of your available resources and render your host OS unresponsive.
