### ISSUE TITLE
A port to windows 

### ISSUE THREAD

**Issue by Servercraft8** [PJ-Singh-001/Cubic#83]
Hey y was wondering if you can make port to windows?

**Comment by PJ-Singh-001** [comment]
Servercraft8,

Thank you for the interest and the request.

Cubic was written as a native [GTK](https://gtk.org) application for [Gnome](https://www.gnome.org) desktops, but it can run on most distros based on Ubuntu, regardless of the desktop environment used.

Even though GTK is available for Windows, it will not be possible to port Cubic's functionality to Windows because...
1. Cubic uses a lot of Linux specific capabilities that are not available in Windows.
2. You _must_ use a Linux file system (such as `ext`) to customize a Linux OS. Windows can not read or write Linux files, or handle the necessary Linux file permissions.

However, there may be a few options available to you...
1. It is possible to run Cubic in WSL. See [How to run Cubic in WSL?](https://github.com/PJ-Singh-001/Cubic/issues/18)
2. It is also possible to run Cubic in Docker. See [Runing Cubic on Docker](https://github.com/PJ-Singh-001/Cubic/issues/66#issuecomment-1163745353). (Although you may need to adapt the solution to Docker on Windows).
3. Install Ubuntu in a virtual machine such as [VirtualBox](https://www.virtualbox.org/). Then install and run Cubic in Ubuntu. Make sure you allocate enough memory and disk space (~30GB) to your virtual machine.

**Comment by PJ-Singh-001** [comment]
I'm closing this question with the above comment as the resolution.
