### ISSUE TITLE
Cubic on Ubuntu Server 

### ISSUE THREAD

**Issue by sudo-joe** [PJ-Singh-001/Cubic#84]
Hello forum,

would like to make a remaster of Ubuntu Server 20.04 LTS installation. But to my knowledge,
Cubic requires a GUI.

Would it be possible(and advisable) to install additional packages on Ubuntu-Server in oder to be able to have Cubic worked on it? 

If yes, what packages would be required?

Thank you!

Joe

**Comment by PJ-Singh-001** [comment]
Cubic is designed to run in a standard Desktop install of Ubuntu, so the dependencies that Cubic specifies are only additional packages that are not installed by default on Ubuntu.

The easiest way is to run Cubic is to install the Ubuntu Gnome Desktop onto Ubuntu Server:

    sudo apt install ubuntu-desktop

You may also try the `ubuntu-desktop-minimal` package which should avoid installing the usual Ubuntu applications (such as Rythmbox, Thunderbird, etc.).

    sudo apt install ubuntu-desktop-minimal

After you install either of these packages, you will get a traditional Ubuntu Desktop with the graphical login screen.

If you are looking for the minimal packages you would need just to run a GUI application such as Cubic, that is hard to say. Certainly, packages needed for GTK3 GUIs will be necessary, and you will also need a window manager.

This is an interesting question. If I get some time, I may experiment to see what the minimal set of packages could be, but I can not make this a priority right now, because I am sure it would be very time consuming to figure out.

**Comment by PJ-Singh-001** [comment]
Since I have not heard back from you, I'll assume that the above approach answers your question.
