### ISSUE TITLE
Unable to create the customized disk image using outdated version of Cubic

### ISSUE THREAD

**Issue by likehengqq** [PJ-Singh-001/Cubic#87]
**Describe the question**

A clear and concise description of what the question is.

The image created by cubic is used. then,Unable to create the customized disk image

**What you have tried**

Steps you already took.

**Expected behavior**

**OS Information (please complete the following information):**
 - OS/Distro Name:ubuntu
 - OS Version :Ubuntu 18.04

**Cubic Information (please complete the following information):**
 - Cubic Version: [e.g. 2021.12.67 from the About dialog, or 2021.12-67-release from `dpkg -l`]
 - ISO Customizing: [e.g. ubuntu-21.10-desktop-amd64.iso]
 - Download Link:  The download link for the ISO you are customizing

**Screenshots**

**Comment by PJ-Singh-001** [comment]
The version of Cubic you are using is quite old.

Update to the current version, 2022.06.72.

    sudo apt-add-repository universe
    sudo apt-add-repository ppa:cubic-wizard/release
    sudo apt update
    sudo apt install --no-install-recommends cubic

Also, make sure your OS is updated as well. Cubic only [works on Ubuntu 18.04.5 and above](https://github.com/PJ-Singh-001/Cubic/wiki/Install-Cubic). If you've updated all of your Ubuntu packages in 18.04 you should be fine.

If you continue to have issues, you may run Cubic from the command-line, in order to capture the log and error information.

    cubic --verbose

Then open new issue and include the log output, so I can see what the problem is.

**Comment by PJ-Singh-001** [comment]
The version of Cubic you are using is quite old.

Update to the current version, 2022.06.72.

    sudo apt-add-repository universe
    sudo apt-add-repository ppa:cubic-wizard/release
    sudo apt update
    sudo apt install --no-install-recommends cubic

Also, make sure your OS is updated as well. Cubic only [works on Ubuntu 18.04.5 and above](https://github.com/PJ-Singh-001/Cubic/wiki/Install-Cubic). If you've updated all of your Ubuntu packages in 18.04 you should be fine.

If you continue to have issues, you may run Cubic from the command-line, in order to capture the log and error information.

    cubic --verbose

Then open new issue and include the log output, so I can see what the problem is.
