### ISSUE TITLE
"apt update" done in cubic chroot environment -> iso generated -> iso does Not complete installation

### ISSUE THREAD

**Issue by melvinga** [PJ-Singh-001/Cubic#91]
**Describe the bug**

Cubic versions tried: 2022.01.70, 2022.06.72
Source iso used: (1) ubuntu-18.04.5-live-server-amd64.iso (2) ubuntu-20.04.4-live-server-amd64.iso (3) ubuntu-22.04-live-server-amd64.iso
Commands executed in cubic chroot environment: apt update
Issue: While installing iso to create a vm, during the copying of files from iso to vm as part of installation, installation crashes and goes back to beginning of iso installation (Select Language page). This repeats whenever we retry.

**To Reproduce**

Host OS version (in which cubic GUI app is installed): Any of (1) Ubuntu 18.04.6 (2) Ubuntu 20.04.4 (3) Ubuntu 22.04.
Source iso used: (1) ubuntu-18.04.5-live-server-amd64.iso (2) ubuntu-20.04.4-live-server-amd64.iso (3) ubuntu-22.04-live-server-amd64.iso
Create a new project folder for cubic to rule out chances of any errors in previous project folder.
Commands executed in cubic chroot environment: apt update
Generate the iso from cubic using default options.
Using the iso generated, create a vm in proxmox 7.1-7 (or esxi 6.7). VM is assigned 2 cpu cores and 2048MB ram, 16 GB hard disk space. (In proxmox, NUMA option is selected. In exsi, 2 cores per 1 socket is selected).
Proceed with installing iso normally, where installation steps start from where user has to Select Language. Use entire harddisk is selected, And unticked setup of LVM.
User credentials entered:
1) Your name: ubuntu
2) Server name: trial
3) Username: ubuntu
4) password: 1234
Ticked "Install OpenSSH"
After entering all necessary details, the iso installation proceeds to copying files from the iso to the vm. During that, the installation crashes (generally after "installing kernel" is shown in installation screen). A popup comes saying:
"Sorry, there was a problem completing the installation.
Information is being collected from the system that will help the developers diagnose the report."

And within a few seconds, the iso installation goes back to the beginning where users have to Select Language.
This repeats in every trial.

**Expected behavior**

ISO installation completes without errors. After reboot, it shows linux user login prompts. Once correct credentials are entered, user is logged in successfully.

**OS Information (please complete the following information):**
 - OS/Distro Name: Ubuntu
 - OS Version: Tried with base OS (into which cubic GUI is installed): Ubuntu 18.04.6, Ubuntu 20.04.4, Ubuntu 22.04. All desktop versions. All have the same issue as above.

**Cubic Information (please complete the following information):**
 - Cubic Version: 2022.01.70, 2022.06.72
 - ISO Customizing: (1) ubuntu-18.04.5-live-server-amd64.iso (2) ubuntu-20.04.4-live-server-amd64.iso (3) ubuntu-22.04-live-server-amd64.iso
 - Download Link:  (1) https://old-releases.ubuntu.com/releases/18.04.5/ubuntu-18.04.5-live-server-amd64.iso (2) https://releases.ubuntu.com/20.04/ubuntu-20.04.4-live-server-amd64.iso (3) https://hr.releases.ubuntu.com/22.04/ubuntu-22.04-live-server-amd64.iso

**Cubic Log:**

[cubic-verbose-2022Aug10T1125ist.log](https://github.com/PJ-Singh-001/Cubic/files/9297239/cubic-verbose-2022Aug10T1125ist.log)

**Screenshots**

![cubic_aptupdateinchroot_isodoesNotcompletedinstallation_cubic2022 06 72_2022Aug10T1125ist](https://user-images.githubusercontent.com/7609946/183827941-6b74720f-de9f-439e-a2e2-e0216546a298.png)

**Comment by PJ-Singh-001** [comment]
Thank you for the detailed bug report.

When you get the message, "Sorry, there was a problem completing the installation," is there an install log that you have access to and can share?

**Comment by melvinga** [comment]
> Thank you for the detailed bug report.
> 
> When you get the message, "Sorry, there was a problem completing the installation," is there an install log that you have access to and can share?

Thanks for responding promptly.

With Ubuntu 18.04.5 (and 18.04.6) LTS server iso as base (host vm would be Ubuntu 18.04.5 or 18.04.6 desktop as the base iso that is used), when that popup occurs, within a few seconds it goes back to the beginning of the installation procedure that says "Select Language". No way to view the logfile in this case, i suppose.

With Ubuntu 20.04.4 LTS server iso as base (host vm would be Ubuntu 20.04.4 desktop as the base iso that is used), that popup develops into another popup that gives an option to see the log. It seems rather a very long log file. Attached below are screenshot of ending part of that rather long report:
![Screenshot from 2022-08-11 10-20-10](https://user-images.githubusercontent.com/7609946/184066644-2736f913-105b-4723-bd37-37c69bb9887d.png)
![Screenshot from 2022-08-11 10-20-01](https://user-images.githubusercontent.com/7609946/184066647-bb0c0363-b50d-4bbc-bf27-36985837bf86.png)
![Screenshot from 2022-08-11 10-19-51](https://user-images.githubusercontent.com/7609946/184066650-15bb82f4-ab19-48c4-ae47-4b949e388430.png)
![Screenshot from 2022-08-11 10-19-41](https://user-images.githubusercontent.com/7609946/184066652-240e1dae-1fa0-463d-8cf2-26a2e148ca2f.png)
![Screenshot from 2022-08-11 10-19-32](https://user-images.githubusercontent.com/7609946/184066653-ea6babe2-ff19-427c-8786-a5c9c2d896c5.png)
![Screenshot from 2022-08-11 10-19-20](https://user-images.githubusercontent.com/7609946/184066656-4d0f868f-c9f3-4cc3-ad99-dba0e8798bc3.png)
![Screenshot from 2022-08-11 10-19-10](https://user-images.githubusercontent.com/7609946/184066657-0e42bb37-6e1c-4256-b3fc-0c6a7314c2be.png)
![Screenshot from 2022-08-11 10-18-59](https://user-images.githubusercontent.com/7609946/184066658-e9c5e646-07be-460c-818d-480a13241047.png)
![Screenshot from 2022-08-11 10-18-48](https://user-images.githubusercontent.com/7609946/184066660-54aca236-9ef7-49ef-b5ac-250ac8dcf568.png)
![Screenshot from 2022-08-11 10-18-23](https://user-images.githubusercontent.com/7609946/184066661-674e855f-7bb3-47b6-983b-09b07ea9a383.png)

I don't know how to copy it outside. Please guide me if you are familiar with how to get this log file out of the vm.
Also, is there any specific section in the log file you would like me to get a screenshot of?

**Comment by PJ-Singh-001** [comment]
I preformed a test and I did not experience this "looping" issue.
However, there seem to be issues customizing the Server ISO, in general (See https://github.com/PJ-Singh-001/Cubic/issues/106).
Issue #106 is the priority, because even if you were able to get past this "looping" issue, you would probably run into issue #106.

**Comment by PJ-Singh-001** [comment]
Cubic version 2023.03.79 should resolve this issue.

I tested the following:

- Cubic version: **2023.03.79**
- OS used to run Cubic: **Ubuntu Desktop 22.04.2**
- ISO customized in Cubic: **ubuntu-22.04.2-live-server-amd64.iso**

Use the following steps when Customizing Ubuntu Server:

 1. Install Cubic 2023.03.79+
 2. On [Cubic's Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), execute the following (per your original report):

        apt update
        apt upgrade

 3. On [Cubic's Kernel tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#kernel-tab), select the default/original bootstrap kernel (this is important)
 4. Generate the customized ISO in Cubic
 5. Boot into the customized ISO
 6. Select "Try or install Ubuntu Server" from the ISO's GRUB menu
 7. Select "Ubuntu Server (minimized)" when prompted to "Choose the base for the installation". (This is important because Cubic customizes the minimal install on the [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page)).
 8. Select "Install OpenSSH Server" (per your original report)
 9. Proceed with the installation

(Note: I have also closed Issue #106, [Ubuntu 22.04 Server apt upgrade changes are not applied after installation of the customized OS](https://github.com/PJ-Singh-001/Cubic/issues/106), with the same resolution).

If you still have problems, please open a new issue and include detailed information.
