### ISSUE TITLE
Is there anyway of making 32bit version of Ubuntu using Cubic?

### ISSUE THREAD

**Issue by noalternative67** [PJ-Singh-001/Cubic#92]
Is there anyway of making 32bit version of Ubuntu using Cubic?

**Comment by PJ-Singh-001** [comment]
While Cubic is running, it uses the same kernel as your host machine, although it is sandboxed to prevent your customizations from affecting your host OS.

Cubic does not have any builds for non-64 bit systems, since (as I recall) Ubuntu 17.10 was the last version of Ubuntu that supported 32-bit architectures, and Cubic requires at least Ubuntu 18.04.5 to install and run.

Theoretically, if you had a 32-bit Ubuntu *based* OS installed on your host machine, and this system had all of the dependencies Cubic requires, you could install Cubic on this system and run it. (Note that the Cubic software is exactly the same for all Ubuntu versions. For example, the Cubic software you install on Ubuntu 18.04.5 is *exactly* the same as the Cubic software on Ubuntu 22.04, because I've written the same codebase to run on a wide range of Ubuntu versions). Therefor, you will be fine if you install the latest version of Cubic (version 2022.06.72 as of today). Adding the following to the `sources.list` for your 32-bit OS should do the trick:

    deb [arch=amd64] https://ppa.launchpadcontent.net/cubic-wizard/release/ubuntu/ jammy main

You will also need a 32-bit `universe` repository for Cubic dependencies.

Even though Cubic must be installed on Ubuntu 18.04.5 *or greater*, you can customize almost all older versions of Ubuntu using Cubic. For example, I have tested customizing the Ubuntu 14.04 ISO while running Cubic in Ubuntu 21.04. As long as your Ubuntu based distro has active reposotories that include 32-bit packages for the version of the OS you are customizing, you should be able to add or remove packages as needed.

As an example, Linux Mint still supports a 32-bit version: it is Linux Mint 19.3, and is supported until April 2023. Therefore, if your host computer were running Linux Mint 19.3 32-bit (with all packages updated, so they are up to the level of Ubuntu 18.04.5), you could then install Cubic. After that, you could customize almost any 32-bit version of Ubuntu.

(Note that folks have complained about not being able to customize Ubuntu 20.XX while using Ubuntu 18.04, so you may not be able to customize a *too new* version of Ubuntu, but older versions and slightly newer versions should be fine to customize. I suspect this has something to do with kernel incompatibility between 18.04 and 20.XX, but I haven't found a work-around for this yet).

If you chose to do this experiment, I would be interested in your experience.

**Comment by PJ-Singh-001** [comment]
Good news:

The process is simpler than I had thought...

I was able to customize `linuxmint-19.3-xfce-32bit.iso` in Cubic running on Ubuntu 21.04 x64.

Although typing `arch` in the Cubic virtual environment showed `x86_64` (because Cubic's terminal always uses the same kernel version as the host machine), `apt` intelligently installed the 32-bit versions of packages. (I did not need to append the package name with the `:i386` architecture).

Simply install Cubic into a version of Ubuntu greater than or equal to 18.04.5.
Then open Cubic and chose to customize your 32-bit ISO.

**Comment by PJ-Singh-001** [comment]
By the way, when you say, "making 32bit version of Ubuntu," this would not be possible by starting with a modern 64 bit version of Ubuntu, since as I mentioned previously, Canonical stopped supporting 32-bit with Ubuntu version 17.04.

Therefore, your approach should be to start with an Ubuntu based Distro that does still support 32-bit architecture.

Also, when you say "Ubuntu," I assume you mean the "Ubuntu GNOME desktop."

Here are the general steps you should follow:
1. Customize the ISO for an Ubuntu based Distro that still supports 32-bit
2. Uninstall the Distro's default desktop
3. Install the Ubuntu GNOME desktop

As an example, you can do the following for `linuxmint-19.3-xfce-32bit.iso`:

    apt update
    apt autoremove --purge xfdesktop4
    apt install ubuntu-desktop

Tip: You may want to use `linuxmint-19.3-cinnamon-32bit.iso` as your original ISO.
