### ISSUE TITLE
stuck at 10%

### ISSUE THREAD

**Issue by GIH-LOL** [PJ-Singh-001/Cubic#97]
Cubic Custom Ubuntu ISO Creator stuck at 10.0% compressing the customized Linux file system for >5 minutes until it says: "Error: Unable to create the customized Linux file system."

![image](https://user-images.githubusercontent.com/107813422/187714989-78500e48-54f7-45f0-98d1-2d3650a67b30.png)

**Comment by PJ-Singh-001** [comment]
What is the OS and version your are running?
What is the version of Cubic your are running?
What is the ISO you are customizing?

This typically happens when you've run out of disk space, but let's see if there is some other problem...

 1. What is the output of the following *before* running Cubic.

        df -h

2. Then, run Cubic from the command line using the `--verbose` flag.

        cubic --verbose

3. When the error occurs, copy and paste the log output here, so I can examine it.

4. Also, let me know what is the output of the following *after* the error.

        df -h

**Comment by PJ-Singh-001** [comment]
I have not heard back from you, so I will assume you no longer have this issue.
